// accounts.ts — acc_accounts ผังบัญชีมาตรฐานไทย ~32 บัญชี
// ตาม spec §8 seed list (รหัส 1000–5900, is_system:true)
// บัญชี auto-post บังคับ: 5100/5110/5120/2210/2220/2230/2240/1010/1020/1590 (ค่าเสื่อมสะสม)/5800

import type { AccAccount } from "./types";
import { MOCK_ORG_ID } from "./org-settings";

const ORG = MOCK_ORG_ID;
const NOW = "2026-01-01T00:00:00.000Z";

export const mockAccounts: AccAccount[] = [
  // ====== สินทรัพย์ (Asset) ======
  {
    id: "acc-1000",
    org_id: ORG,
    code: "1000",
    name: "สินทรัพย์หมุนเวียน",
    account_type: "asset",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1010",
    org_id: ORG,
    code: "1010",
    name: "เงินสด",
    account_type: "asset",
    parent_id: "acc-1000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1020",
    org_id: ORG,
    code: "1020",
    name: "เงินฝากธนาคาร",
    account_type: "asset",
    parent_id: "acc-1000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1100",
    org_id: ORG,
    code: "1100",
    name: "ลูกหนี้การค้า",
    account_type: "asset",
    parent_id: "acc-1000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1130",
    org_id: ORG,
    code: "1130",
    name: "สินค้าคงเหลือ",
    account_type: "asset",
    parent_id: "acc-1000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1160",
    org_id: ORG,
    code: "1160",
    name: "ภาษีซื้อ (VAT ซื้อ)",
    account_type: "asset",
    parent_id: "acc-1000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1200",
    org_id: ORG,
    code: "1200",
    name: "สินทรัพย์ไม่หมุนเวียน",
    account_type: "asset",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1500",
    org_id: ORG,
    code: "1500",
    name: "ที่ดิน อาคาร และอุปกรณ์",
    account_type: "asset",
    parent_id: "acc-1200",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1510",
    org_id: ORG,
    code: "1510",
    name: "อุปกรณ์และเครื่องใช้สำนักงาน",
    account_type: "asset",
    parent_id: "acc-1200",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1520",
    org_id: ORG,
    code: "1520",
    name: "ยานพาหนะ",
    account_type: "asset",
    parent_id: "acc-1200",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-1590",
    org_id: ORG,
    code: "1590",
    name: "ค่าเสื่อมราคาสะสม (contra asset)",
    account_type: "asset",
    parent_id: "acc-1200",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },

  // ====== หนี้สิน (Liability) ======
  {
    id: "acc-2000",
    org_id: ORG,
    code: "2000",
    name: "หนี้สินหมุนเวียน",
    account_type: "liability",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2100",
    org_id: ORG,
    code: "2100",
    name: "เจ้าหนี้การค้า",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2210",
    org_id: ORG,
    code: "2210",
    name: "ภาษีหัก ณ ที่จ่ายค้างจ่าย (PND1)",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2220",
    org_id: ORG,
    code: "2220",
    name: "ประกันสังคมค้างจ่าย (SSO)",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2230",
    org_id: ORG,
    code: "2230",
    name: "กองทุนสำรองเลี้ยงชีพค้างจ่าย (PVD)",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2240",
    org_id: ORG,
    code: "2240",
    name: "เงินหักอื่นค้างจ่าย",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2250",
    org_id: ORG,
    code: "2250",
    name: "ภาษีขาย (VAT ขาย)",
    account_type: "liability",
    parent_id: "acc-2000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2300",
    org_id: ORG,
    code: "2300",
    name: "หนี้สินไม่หมุนเวียน",
    account_type: "liability",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-2310",
    org_id: ORG,
    code: "2310",
    name: "เงินกู้ยืมระยะยาว",
    account_type: "liability",
    parent_id: "acc-2300",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },

  // ====== ส่วนของเจ้าของ (Equity) ======
  {
    id: "acc-3000",
    org_id: ORG,
    code: "3000",
    name: "ส่วนของเจ้าของ",
    account_type: "equity",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-3100",
    org_id: ORG,
    code: "3100",
    name: "ทุน",
    account_type: "equity",
    parent_id: "acc-3000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-3200",
    org_id: ORG,
    code: "3200",
    name: "กำไรสะสม",
    account_type: "equity",
    parent_id: "acc-3000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },

  // ====== รายได้ (Income) ======
  {
    id: "acc-4000",
    org_id: ORG,
    code: "4000",
    name: "รายได้",
    account_type: "income",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-4100",
    org_id: ORG,
    code: "4100",
    name: "รายได้จากการขาย/บริการ",
    account_type: "income",
    parent_id: "acc-4000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-4200",
    org_id: ORG,
    code: "4200",
    name: "รายได้อื่น",
    account_type: "income",
    parent_id: "acc-4000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },

  // ====== ค่าใช้จ่าย (Expense) ======
  {
    id: "acc-5000",
    org_id: ORG,
    code: "5000",
    name: "ค่าใช้จ่าย",
    account_type: "expense",
    parent_id: null,
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5100",
    org_id: ORG,
    code: "5100",
    name: "เงินเดือนและค่าจ้าง (gross รวม OT/เบี้ย — I1)",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5110",
    org_id: ORG,
    code: "5110",
    name: "ค่าใช้จ่าย SSO นายจ้าง",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5120",
    org_id: ORG,
    code: "5120",
    name: "ค่าใช้จ่าย PVD นายจ้าง",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5200",
    org_id: ORG,
    code: "5200",
    name: "ค่าเช่า",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5300",
    org_id: ORG,
    code: "5300",
    name: "ค่าสาธารณูปโภค",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5400",
    org_id: ORG,
    code: "5400",
    name: "ค่าวัสดุสิ้นเปลือง",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5500",
    org_id: ORG,
    code: "5500",
    name: "ค่าการตลาดและโฆษณา",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5600",
    org_id: ORG,
    code: "5600",
    name: "ค่าใช้จ่ายในการบริหาร",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5800",
    org_id: ORG,
    code: "5800",
    name: "ค่าเสื่อมราคา",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
  {
    id: "acc-5900",
    org_id: ORG,
    code: "5900",
    name: "ต้นทุนขาย/บริการ (COGS)",
    account_type: "expense",
    parent_id: "acc-5000",
    is_active: true,
    is_system: true,
    created_at: NOW,
  },
];

/** map id → AccAccount (สะดวก join ใน UI) */
export const accountById: Record<string, AccAccount> = Object.fromEntries(
  mockAccounts.map((a) => [a.id, a]),
);

/** map code → AccAccount */
export const accountByCode: Record<string, AccAccount> = Object.fromEntries(
  mockAccounts.map((a) => [a.code, a]),
);
