// entries.ts — acc_entries ~30 รายรับ/รายจ่าย cockpit
// กระจายหลายหมวด/แหล่งที่มา ช่วง 3 เดือนล่าสุด (เม.ย.–มิ.ย. 2569)
// รองรับ A1 dashboard StatCard + A2 filter/list + L3 weekly digest

import type { AccEntry, AccEntrySummary } from "./types";
import { MOCK_ORG_ID } from "./org-settings";

const ORG = MOCK_ORG_ID;

export const mockEntries: AccEntry[] = [
  // ---- เมษายน 2569 (April 2026) ----
  {
    id: "ent-001",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-04-02",
    amount: 45000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าออกแบบโลโก้และคอร์ปอเรทไอเดนทิตี้ บ.ไทยดีไซน์",
    contact_id: "cnt-c01",
    source: "document",
    source_ref_id: "doc-inv01",
    wht_rate: 3,
    wht_amount: 1350.0,
    journal_entry_id: "jv-001",
    created_at: "2026-04-02T09:00:00.000Z",
    contact_name: "บริษัท ไทยดีไซน์ สตูดิโอ จำกัด",
  },
  {
    id: "ent-002",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-04-03",
    amount: 18000.0,
    category: "ค่าเช่า",
    description: "ค่าเช่าสำนักงาน เดือนเมษายน",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-04-03T10:00:00.000Z",
  },
  {
    id: "ent-003",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-04-05",
    amount: 3850.0,
    category: "ค่าสาธารณูปโภค",
    description: "ค่าไฟฟ้า-น้ำประปา เดือนมีนาคม",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-04-05T09:30:00.000Z",
  },
  {
    id: "ent-004",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-04-08",
    amount: 28500.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ออกแบบเว็บไซต์และ UX บ.ครีเอทีฟ เน็ตเวิร์ค",
    contact_id: "cnt-b01",
    source: "document",
    source_ref_id: "doc-inv02",
    wht_rate: 3,
    wht_amount: 855.0,
    journal_entry_id: "jv-002",
    created_at: "2026-04-08T10:00:00.000Z",
    contact_name: "บริษัท ครีเอทีฟ เน็ตเวิร์ค จำกัด",
  },
  {
    id: "ent-005",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-04-10",
    amount: 9800.0,
    category: "ค่าวัสดุสิ้นเปลือง",
    description: "ซื้อกระดาษ หมึกพิมพ์ และอุปกรณ์สำนักงาน",
    contact_id: "cnt-v01",
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-04-10T11:00:00.000Z",
    contact_name: "บริษัท ซัพพลายดี จำกัด",
  },
  {
    id: "ent-006",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-04-15",
    amount: 58500.0,
    category: "เงินเดือนและค่าจ้าง",
    description: "เงินเดือนพนักงาน เดือนเมษายน 2569 (auto-post จาก HRM)",
    contact_id: null,
    source: "payroll",
    source_ref_id: "payroll-run-apr-2026",
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: "jv-payroll-apr",
    created_at: "2026-04-30T18:00:00.000Z",
  },
  {
    id: "ent-007",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-04-18",
    amount: 12000.0,
    category: "ค่าการตลาดและโฆษณา",
    description: "ค่าโฆษณา Facebook และ Google Ads เดือนเมษายน",
    contact_id: "cnt-v03",
    source: "manual",
    source_ref_id: null,
    wht_rate: 3,
    wht_amount: 360.0,
    journal_entry_id: null,
    created_at: "2026-04-18T14:00:00.000Z",
    contact_name: "บริษัท ออนไลน์โฆษณา จำกัด",
  },
  {
    id: "ent-008",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-04-20",
    amount: 15000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าถ่ายภาพสินค้า package เล็ก (10 ภาพ)",
    contact_id: "cnt-c02",
    source: "document",
    source_ref_id: "doc-rc01",
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: "jv-003",
    created_at: "2026-04-20T13:00:00.000Z",
    contact_name: "ร้านกาแฟ บ้านเช้า",
  },
  {
    id: "ent-009",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-04-25",
    amount: 8000.0,
    category: "รายได้อื่น",
    description: "รายได้ดอกเบี้ยเงินฝาก",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: 15,
    wht_amount: 1200.0,
    journal_entry_id: null,
    created_at: "2026-04-25T09:00:00.000Z",
  },

  // ---- พฤษภาคม 2569 (May 2026) ----
  {
    id: "ent-010",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-05-02",
    amount: 75000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าออกแบบและพัฒนาระบบ POS บ.วังทองก่อสร้าง",
    contact_id: "cnt-c03",
    source: "document",
    source_ref_id: "doc-inv03",
    wht_rate: 3,
    wht_amount: 2250.0,
    journal_entry_id: "jv-004",
    created_at: "2026-05-02T10:00:00.000Z",
    contact_name: "ห้างหุ้นส่วน วังทองก่อสร้าง",
  },
  {
    id: "ent-011",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-03",
    amount: 18000.0,
    category: "ค่าเช่า",
    description: "ค่าเช่าสำนักงาน เดือนพฤษภาคม",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-05-03T09:00:00.000Z",
  },
  {
    id: "ent-012",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-05",
    amount: 4200.0,
    category: "ค่าสาธารณูปโภค",
    description: "ค่าไฟฟ้า-น้ำประปา เดือนเมษายน",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-05-05T09:30:00.000Z",
  },
  {
    id: "ent-013",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-05-10",
    amount: 22000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ออกแบบ packaging สินค้า 3 แบบ คุณสมชาย",
    contact_id: "cnt-c04",
    source: "document",
    source_ref_id: "doc-inv04",
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: "jv-005",
    created_at: "2026-05-10T11:00:00.000Z",
    contact_name: "คุณสมชาย วงศ์สุข (บุคคลธรรมดา)",
  },
  {
    id: "ent-014",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-12",
    amount: 6500.0,
    category: "ค่าใช้จ่ายในการบริหาร",
    description: "ค่า Software subscription (Adobe CC รายปี/12)",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-05-12T13:00:00.000Z",
  },
  {
    id: "ent-015",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-15",
    amount: 58500.0,
    category: "เงินเดือนและค่าจ้าง",
    description: "เงินเดือนพนักงาน เดือนพฤษภาคม 2569 (auto-post จาก HRM)",
    contact_id: null,
    source: "payroll",
    source_ref_id: "payroll-run-may-2026",
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: "jv-payroll-may",
    created_at: "2026-05-31T18:00:00.000Z",
  },
  {
    id: "ent-016",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-20",
    amount: 35000.0,
    category: "ต้นทุนขาย/บริการ (COGS)",
    description: "ค่าจ้างฟรีแลนซ์รายโปรเจกต์ (ทำ POS บ.วังทอง)",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: 3,
    wht_amount: 1050.0,
    journal_entry_id: null,
    created_at: "2026-05-20T14:00:00.000Z",
  },
  {
    id: "ent-017",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-05-22",
    amount: 12000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าจัดทำ content และโพสต์ social media (เดือน)",
    contact_id: "cnt-b01",
    source: "line",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-05-22T10:00:00.000Z",
    contact_name: "บริษัท ครีเอทีฟ เน็ตเวิร์ค จำกัด",
  },
  {
    id: "ent-018",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-05-25",
    amount: 5800.0,
    category: "ค่าวัสดุสิ้นเปลือง",
    description: "ซื้อวัสดุสำนักงานและอุปกรณ์ IT เพิ่มเติม",
    contact_id: "cnt-v01",
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-05-25T10:00:00.000Z",
    contact_name: "บริษัท ซัพพลายดี จำกัด",
  },

  // ---- มิถุนายน 2569 (June 2026) ----
  {
    id: "ent-019",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-06-02",
    amount: 55000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าออกแบบระบบ dashboard analytics รอบ Q2",
    contact_id: "cnt-c01",
    source: "document",
    source_ref_id: "doc-inv05",
    wht_rate: 3,
    wht_amount: 1650.0,
    journal_entry_id: null,
    created_at: "2026-06-02T09:00:00.000Z",
    contact_name: "บริษัท ไทยดีไซน์ สตูดิโอ จำกัด",
  },
  {
    id: "ent-020",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-03",
    amount: 18000.0,
    category: "ค่าเช่า",
    description: "ค่าเช่าสำนักงาน เดือนมิถุนายน",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-03T09:00:00.000Z",
  },
  {
    id: "ent-021",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-05",
    amount: 3650.0,
    category: "ค่าสาธารณูปโภค",
    description: "ค่าไฟฟ้า-น้ำประปา เดือนพฤษภาคม",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-05T09:30:00.000Z",
  },
  {
    id: "ent-022",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-06-06",
    amount: 18000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าบริการรายเดือน retainer fee บ.ครีเอทีฟ",
    contact_id: "cnt-b01",
    source: "document",
    source_ref_id: "doc-inv06",
    wht_rate: 3,
    wht_amount: 540.0,
    journal_entry_id: null,
    created_at: "2026-06-06T10:00:00.000Z",
    contact_name: "บริษัท ครีเอทีฟ เน็ตเวิร์ค จำกัด",
  },
  {
    id: "ent-023",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-08",
    amount: 8500.0,
    category: "ค่าการตลาดและโฆษณา",
    description: "ค่าบู๊ธออกงาน Creative Festival 2026",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-08T11:00:00.000Z",
  },
  {
    id: "ent-024",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-06-10",
    amount: 9500.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าบริการ /รายจ่าย ผ่าน LINE (บันทึกอัตโนมัติ)",
    contact_id: null,
    source: "line",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-10T14:00:00.000Z",
  },
  {
    id: "ent-025",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-12",
    amount: 2200.0,
    category: "ค่าใช้จ่ายในการบริหาร",
    description: "ค่าโทรศัพท์และอินเทอร์เน็ต",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-12T09:00:00.000Z",
  },
  {
    id: "ent-026",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-15",
    amount: 7200.0,
    category: "ค่าวัสดุสิ้นเปลือง",
    description: "ซื้อกาแฟ วัสดุสำหรับถ่ายทำรีวิว",
    contact_id: "cnt-v02",
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-15T10:30:00.000Z",
    contact_name: "ร้านค้าวัสดุก่อสร้าง พงษ์เจริญ",
  },
  {
    id: "ent-027",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-06-16",
    amount: 32000.0,
    category: "รายได้จากการขาย/บริการ",
    description: "ค่าออกแบบ brochure และ catalog ปีใหม่",
    contact_id: "cnt-c03",
    source: "ai",
    source_ref_id: null,
    wht_rate: 3,
    wht_amount: 960.0,
    journal_entry_id: null,
    created_at: "2026-06-16T11:00:00.000Z",
    contact_name: "ห้างหุ้นส่วน วังทองก่อสร้าง",
  },
  {
    id: "ent-028",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-20",
    amount: 58500.0,
    category: "เงินเดือนและค่าจ้าง",
    description: "เงินเดือนพนักงาน เดือนมิถุนายน 2569 (auto-post จาก HRM)",
    contact_id: null,
    source: "payroll",
    source_ref_id: "payroll-run-jun-2026",
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: "jv-payroll-jun",
    created_at: "2026-06-20T18:00:00.000Z",
  },
  {
    id: "ent-029",
    org_id: ORG,
    kind: "expense",
    entry_date: "2026-06-22",
    amount: 15000.0,
    category: "ค่าการตลาดและโฆษณา",
    description: "ค่าจ้างอินฟลูเอนเซอร์ (WHT 3%)",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: 3,
    wht_amount: 450.0,
    journal_entry_id: null,
    created_at: "2026-06-22T10:00:00.000Z",
  },
  {
    id: "ent-030",
    org_id: ORG,
    kind: "income",
    entry_date: "2026-06-24",
    amount: 6800.0,
    category: "รายได้อื่น",
    description: "ขายอุปกรณ์สำนักงานเก่า",
    contact_id: null,
    source: "manual",
    source_ref_id: null,
    wht_rate: null,
    wht_amount: null,
    journal_entry_id: null,
    created_at: "2026-06-24T15:00:00.000Z",
  },
];

/** สรุปรายรับ-รายจ่าย (helper สำหรับ dashboard StatCard) */
export function summarizeEntries(
  entries: AccEntry[],
  monthYear?: { year: number; month: number },
): AccEntrySummary {
  const filtered = monthYear
    ? entries.filter((e) => {
        const d = new Date(e.entry_date);
        return d.getFullYear() === monthYear.year && d.getMonth() + 1 === monthYear.month;
      })
    : entries;

  const total_income = filtered
    .filter((e) => e.kind === "income")
    .reduce((s, e) => s + e.amount, 0);

  const total_expense = filtered
    .filter((e) => e.kind === "expense")
    .reduce((s, e) => s + e.amount, 0);

  return {
    total_income,
    total_expense,
    net: total_income - total_expense,
    income_count: filtered.filter((e) => e.kind === "income").length,
    expense_count: filtered.filter((e) => e.kind === "expense").length,
  };
}

/** สรุปเดือนมิถุนายน 2569 (เดือนปัจจุบัน) สำหรับ dashboard */
export const currentMonthSummary = summarizeEntries(mockEntries, {
  year: 2026,
  month: 6,
});

/** สรุปทั้งหมด (3 เดือน) */
export const allTimeSummary = summarizeEntries(mockEntries);
