// pricing.ts — golf_price_items catalog (green fee weekday/weekend, แคดดี้, รถ, ตะกร้าลูก)
// PRICING RULE (LOCKED §3.3): ราคาฐาน = member_type='all' · ส่วนลดสมาชิกมาจาก plan.green_fee_discount_pct
// เท่านั้น · member_type='member'/'vip' = fallback ราคาตรง (ไม่หัก %) เมื่อไม่มี plan active
//
// หมายเหตุ key: id ของ gf-we-morning/gf-we-noon/gf-wd/bucket-l-eve ตรงกับ
// GolfPricingSuggestion.input.items[].key ใน ai-mocks.ts (AI-3 pre-fill ปุ่ม "นำไปตั้งราคา")
// gf-we-morning/gf-we-noon = ราคาฐานเดียวกัน (2,500 ฿) วันนี้ยังไม่แยกช่วงเวลาจริง — AI-3 เป็น
// insight วิเคราะห์ util ต่อช่วงเพื่อ "เสนอ" แยกราคาในอนาคต ไม่ใช่ราคาที่ใช้จริงคนละราคาแล้ว
import type { GolfPriceItem } from "./types";

const now = "2026-01-05T02:00:00.000Z";

export const golfPriceItems: GolfPriceItem[] = [
  // --- green fee (tee_time) ---
  {
    id: "gf-we-morning",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันหยุด ช่วงเช้า 06:00–09:00)",
    applies_to: "tee_time",
    day_type: "weekend",
    member_type: "all",
    price: 2500,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "gf-we-noon",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันหยุด ช่วงบ่าย 12:00–15:00)",
    applies_to: "tee_time",
    day_type: "weekend",
    member_type: "all",
    price: 2500,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "gf-wd",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันธรรมดา)",
    applies_to: "tee_time",
    day_type: "weekday",
    member_type: "all",
    price: 1800,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  // --- fallback rows (member/vip ไม่มี plan active — ราคาตรง ไม่หัก %) ---
  {
    id: "gf-we-member",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันหยุด) — ราคาสมาชิก (ไม่มีแพ็กเกจ)",
    applies_to: "tee_time",
    day_type: "weekend",
    member_type: "member",
    price: 2200,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "gf-wd-member",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันธรรมดา) — ราคาสมาชิก (ไม่มีแพ็กเกจ)",
    applies_to: "tee_time",
    day_type: "weekday",
    member_type: "member",
    price: 1600,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "gf-we-vip",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันหยุด) — ราคา VIP",
    applies_to: "tee_time",
    day_type: "weekend",
    member_type: "vip",
    price: 2000,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "gf-wd-vip",
    org_id: "org-golf-greenvalley",
    category: "green_fee",
    name: "กรีนฟี 18 หลุม (วันธรรมดา) — ราคา VIP",
    applies_to: "tee_time",
    day_type: "weekday",
    member_type: "vip",
    price: 1500,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  // --- caddie / cart ---
  {
    id: "caddie-fee",
    org_id: "org-golf-greenvalley",
    category: "caddie",
    name: "แคดดี้",
    applies_to: "tee_time",
    day_type: "all",
    member_type: "all",
    price: 300,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "caddie-fee-old",
    org_id: "org-golf-greenvalley",
    category: "caddie",
    name: "แคดดี้ (ราคาเก่า — เลิกใช้)",
    applies_to: "tee_time",
    day_type: "all",
    member_type: "all",
    price: 250,
    unit: "ต่อคน",
    bucket_size: null,
    is_active: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cart-fee",
    org_id: "org-golf-greenvalley",
    category: "cart",
    name: "รถกอล์ฟ",
    applies_to: "tee_time",
    day_type: "all",
    member_type: "all",
    price: 800,
    unit: "ต่อคัน",
    bucket_size: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  // --- range bucket (driving_range) ---
  {
    id: "bucket-s",
    org_id: "org-golf-greenvalley",
    category: "range_bucket",
    name: "ตะกร้าเล็ก 30 ลูก",
    applies_to: "driving_range",
    day_type: "all",
    member_type: "all",
    price: 100,
    unit: "ต่อตะกร้า",
    bucket_size: 30,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bucket-m",
    org_id: "org-golf-greenvalley",
    category: "range_bucket",
    name: "ตะกร้ากลาง 50 ลูก",
    applies_to: "driving_range",
    day_type: "all",
    member_type: "all",
    price: 150,
    unit: "ต่อตะกร้า",
    bucket_size: 50,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bucket-l",
    org_id: "org-golf-greenvalley",
    category: "range_bucket",
    name: "ตะกร้าใหญ่ 100 ลูก",
    applies_to: "driving_range",
    day_type: "all",
    member_type: "all",
    price: 300,
    unit: "ต่อตะกร้า",
    bucket_size: 100,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bucket-l-eve",
    org_id: "org-golf-greenvalley",
    category: "range_bucket",
    name: "ตะกร้าใหญ่ 100 ลูก (ไดร์ฟ เย็น 17:00–20:00)",
    applies_to: "driving_range",
    day_type: "weekday",
    member_type: "all",
    price: 300,
    unit: "ต่อตะกร้า",
    bucket_size: 100,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];
