// activities.ts — timeline (mattii_activities) — ทำครบเส้นให้ออเดอร์เด่น (ord-28 flagship demo, ord-16/ord-30
// reprint, ord-10 ค้าง CF, ord-31/ord-32 cancelled/on_hold) + system-level (สต๊อกใกล้หมด)
// ออเดอร์อื่นมี timeline แบบย่อ (ไม่ทำครบทุกออเดอร์ทุก transition — ให้เห็น pattern พอเพียง)
import type { MattiiActivity } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function act(
  a: Omit<MattiiActivity, "org_id" | "created_at" | "occurred_at"> & {
    ageDays: number;
    hour?: number;
  },
): MattiiActivity {
  const { ageDays, hour, ...rest } = a;
  const ts = daysAgo(ageDays, hour ?? 10);
  return { ...rest, org_id: MOCK_ORG_ID, occurred_at: ts, created_at: ts };
}

export const activities: MattiiActivity[] = [
  // ---- ord-28: flagship demo เต็มเส้น ----
  act({
    id: "act-28-01",
    order_id: "ord-28",
    activity_type: "system",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: "draft",
    message: "สร้างออเดอร์จากแชท TikTok — AI ช่วยสรุปสเปกจากรูปที่ลูกค้าส่ง",
    meta: {},
    ageDays: 16,
  }),
  act({
    id: "act-28-02",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: "quoted",
    to_status: "confirmed",
    message: "ลูกค้ายืนยันราคา 1,030 ฿",
    meta: {},
    ageDays: 15,
  }),
  act({
    id: "act-28-03",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-design-2",
    actor_label: "ภูริช (ทีมแบบ)",
    from_status: "confirmed",
    to_status: "designing",
    message: "เข้าคิวงานแบบ",
    meta: {},
    ageDays: 15,
  }),
  act({
    id: "act-28-04",
    order_id: "ord-28",
    activity_type: "file_upload",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: null,
    message: "อัปโหลดไฟล์ลาย v1 (ไฟล์ลูกค้าส่งมา)",
    meta: { version: 1 },
    ageDays: 15,
  }),
  act({
    id: "act-28-05",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-design-2",
    actor_label: "ภูริช (ทีมแบบ)",
    from_status: "designing",
    to_status: "awaiting_cf",
    message: "ส่งขอ CF เวอร์ชัน 1",
    meta: {},
    ageDays: 14,
  }),
  act({
    id: "act-28-06",
    order_id: "ord-28",
    activity_type: "cf_result",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: "awaiting_cf",
    to_status: "designing",
    message: "ลูกค้าขอแก้: อยากให้สีพื้นอ่อนลงให้เข้ากับโลโก้ร้าน",
    meta: { revision: 1 },
    ageDays: 11,
  }),
  act({
    id: "act-28-07",
    order_id: "ord-28",
    activity_type: "file_upload",
    actor_id: "stf-design-2",
    actor_label: "ภูริช (ทีมแบบ)",
    from_status: null,
    to_status: null,
    message: "อัปโหลดไฟล์ลาย v2 (แก้สีพื้นตามคำขอ)",
    meta: { version: 2 },
    ageDays: 10,
  }),
  act({
    id: "act-28-08",
    order_id: "ord-28",
    activity_type: "cf_result",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: "awaiting_cf",
    to_status: "cf_approved",
    message: "ลูกค้ายืนยันลาย v2 แล้ว — ใช้พิมพ์",
    meta: { approved_version: 2 },
    ageDays: 8,
  }),
  act({
    id: "act-28-09",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-prod-1",
    actor_label: "สมชาย (ทีมผลิต)",
    from_status: "cf_approved",
    to_status: "printing",
    message: "เข้าคิวเครื่องพิมพ์ผ้า PRN-01",
    meta: { machine: "PRN-01" },
    ageDays: 6,
  }),
  act({
    id: "act-28-10",
    order_id: "ord-28",
    activity_type: "note",
    actor_id: "stf-prod-1",
    actor_label: "สมชาย (ทีมผลิต)",
    from_status: null,
    to_status: null,
    message: "QC ไม่ผ่าน: สีเพี้ยน 1 ผืน — เข้าคิวพิมพ์ซ้ำทันที",
    meta: { defect_type: "color_off" },
    ageDays: 5,
  }),
  act({
    id: "act-28-11",
    order_id: "ord-28",
    activity_type: "stock",
    actor_id: null,
    actor_label: "ระบบ",
    from_status: null,
    to_status: null,
    message: "บันทึกผืนที่เสียเป็นของเสีย (waste) 0.621 ตร.ม. ผ้ากำมะหยี่",
    meta: { material: "mat-01" },
    ageDays: 5,
  }),
  act({
    id: "act-28-12",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: "printing",
    to_status: "qc",
    message: "พิมพ์ซ้ำเสร็จแล้ว — QC ผ่าน",
    meta: {},
    ageDays: 3,
  }),
  act({
    id: "act-28-13",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: "stf-prod-1",
    actor_label: "สมชาย (ทีมผลิต)",
    from_status: "packing",
    to_status: "ready_to_ship",
    message: "แพ็คเสร็จ 1 กล่อง 1.4 กก.",
    meta: {},
    ageDays: 2,
  }),
  act({
    id: "act-28-14",
    order_id: "ord-28",
    activity_type: "shipment",
    actor_id: "stf-prod-1",
    actor_label: "สมชาย (ทีมผลิต)",
    from_status: "ready_to_ship",
    to_status: "shipped",
    message: "ซิงก์เลขพัสดุ J&T สำเร็จ: JT2026TH0088001",
    meta: { tracking_no: "JT2026TH0088001" },
    ageDays: 2,
  }),
  act({
    id: "act-28-15",
    order_id: "ord-28",
    activity_type: "status_change",
    actor_id: null,
    actor_label: "ระบบ",
    from_status: "shipped",
    to_status: "delivered",
    message: "ซิงก์สถานะจาก J&T: ส่งสำเร็จ",
    meta: {},
    ageDays: 1,
  }),
  act({
    id: "act-28-16",
    order_id: "ord-28",
    activity_type: "payment",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: null,
    to_status: null,
    message: "เก็บเงินปลายทาง 1,030 ฿ สำเร็จ",
    meta: { amount: 1030 },
    ageDays: 1,
  }),

  // ---- ord-16: เลยกำหนดส่ง + reprint ----
  act({
    id: "act-16-01",
    order_id: "ord-16",
    activity_type: "status_change",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: "printing",
    to_status: "qc",
    message: "พิมพ์เสร็จรอบแรก",
    meta: {},
    ageDays: 5,
  }),
  act({
    id: "act-16-02",
    order_id: "ord-16",
    activity_type: "note",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: null,
    to_status: null,
    message: "QC ไม่ผ่าน: สีเพี้ยนชัดเจน ต้องพิมพ์ซ้ำ",
    meta: { defect_type: "color_off" },
    ageDays: 5,
  }),
  act({
    id: "act-16-03",
    order_id: "ord-16",
    activity_type: "status_change",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: "qc",
    to_status: "printing",
    message: "เข้าคิวพิมพ์ซ้ำเร่งด่วน",
    meta: {},
    ageDays: 5,
  }),
  act({
    id: "act-16-04",
    order_id: "ord-16",
    activity_type: "note",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: null,
    message: "เลยกำหนดส่งแล้ว — แจ้งลูกค้าขอโทษและอัปเดตความคืบหน้า",
    meta: {},
    ageDays: 0,
  }),

  // ---- ord-10: ค้างรอ CF นานผิดปกติ ----
  act({
    id: "act-10-01",
    order_id: "ord-10",
    activity_type: "status_change",
    actor_id: "stf-design-2",
    actor_label: "ภูริช (ทีมแบบ)",
    from_status: "designing",
    to_status: "awaiting_cf",
    message: "ส่งขอ CF เวอร์ชัน 1",
    meta: {},
    ageDays: 19,
  }),
  act({
    id: "act-10-02",
    order_id: "ord-10",
    activity_type: "cf_result",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: "awaiting_cf",
    to_status: "designing",
    message: "ลูกค้าขอแก้: พื้นครีมอ่อนกว่านี้อีกหน่อย",
    meta: { revision: 1 },
    ageDays: 15,
  }),
  act({
    id: "act-10-03",
    order_id: "ord-10",
    activity_type: "status_change",
    actor_id: "stf-design-2",
    actor_label: "ภูริช (ทีมแบบ)",
    from_status: "designing",
    to_status: "awaiting_cf",
    message: "ส่งขอ CF เวอร์ชัน 2 — รอลูกค้าตอบมา 9 วันแล้ว",
    meta: {},
    ageDays: 9,
  }),
  act({
    id: "act-10-04",
    order_id: "ord-10",
    activity_type: "note",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: null,
    message: "ทักตามลูกค้าอีกครั้ง — ยังไม่ตอบ ใกล้เลยกำหนดส่งแล้ว",
    meta: {},
    ageDays: 1,
  }),

  // ---- ord-30: กำไรติดลบ พิมพ์ซ้ำ 2 รอบ ----
  act({
    id: "act-30-01",
    order_id: "ord-30",
    activity_type: "note",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: null,
    to_status: null,
    message: "QC ไม่ผ่านรอบ 1: ลายเบี้ยวไม่ตรงกึ่งกลาง",
    meta: { defect_type: "misalign" },
    ageDays: 8,
  }),
  act({
    id: "act-30-02",
    order_id: "ord-30",
    activity_type: "note",
    actor_id: "stf-prod-1",
    actor_label: "สมชาย (ทีมผลิต)",
    from_status: null,
    to_status: null,
    message: "QC ไม่ผ่านรอบ 2: ผ้าตำหนิจากโรงงาน — พิมพ์ซ้ำอีกครั้ง",
    meta: { defect_type: "material_defect" },
    ageDays: 7,
  }),
  act({
    id: "act-30-03",
    order_id: "ord-30",
    activity_type: "status_change",
    actor_id: "stf-prod-2",
    actor_label: "อรุณี (ทีมผลิต)",
    from_status: "qc",
    to_status: "packing",
    message: "พิมพ์ซ้ำรอบ 2 ผ่าน QC แล้ว",
    meta: {},
    ageDays: 4,
  }),
  act({
    id: "act-30-04",
    order_id: "ord-30",
    activity_type: "note",
    actor_id: "stf-owner",
    actor_label: "สมพงษ์ (เจ้าของ)",
    from_status: null,
    to_status: null,
    message: "ออเดอร์นี้ต้นทุนบานปลายจากพิมพ์ซ้ำ 2 รอบ กำไรติดลบ ต้องทบทวนสาเหตุ QC",
    meta: {},
    ageDays: 1,
  }),

  // ---- ord-31: cancelled ----
  act({
    id: "act-31-01",
    order_id: "ord-31",
    activity_type: "payment",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: null,
    message: "รับมัดจำ 300 ฿",
    meta: { amount: 300 },
    ageDays: 9,
  }),
  act({
    id: "act-31-02",
    order_id: "ord-31",
    activity_type: "status_change",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: "quoted",
    to_status: "cancelled",
    message: "ลูกค้ายกเลิก: เปลี่ยนใจไปสั่งร้านอื่น",
    meta: {},
    ageDays: 8,
  }),
  act({
    id: "act-31-03",
    order_id: "ord-31",
    activity_type: "payment",
    actor_id: "stf-sale-1",
    actor_label: "พิมพ์ใจ (Sale)",
    from_status: null,
    to_status: null,
    message: "คืนเงินมัดจำ 300 ฿ เรียบร้อย",
    meta: { amount: -300 },
    ageDays: 8,
  }),

  // ---- ord-32: on_hold ----
  act({
    id: "act-32-01",
    order_id: "ord-32",
    activity_type: "status_change",
    actor_id: "stf-design-1",
    actor_label: "ชนากานต์ (ทีมแบบ)",
    from_status: "confirmed",
    to_status: "designing",
    message: "เริ่มออกแบบลาย",
    meta: {},
    ageDays: 9,
  }),
  act({
    id: "act-32-02",
    order_id: "ord-32",
    activity_type: "status_change",
    actor_id: "stf-sale-2",
    actor_label: "ณัฐพล (Sale)",
    from_status: "designing",
    to_status: "on_hold",
    message: "ลูกค้าขอพักออเดอร์รอโอนเงินก้อนใหญ่สิ้นเดือน",
    meta: {},
    ageDays: 2,
  }),

  // ---- system-level: วัสดุใกล้หมด ----
  act({
    id: "act-sys-01",
    order_id: null,
    activity_type: "stock",
    actor_id: null,
    actor_label: "ระบบ",
    from_status: null,
    to_status: null,
    message:
      "ผ้าพรมกำมะหยี่ (MAT-FAB-01) ต่ำกว่าจุดสั่งซื้อแล้ว — คงเหลือ 45.5 ตร.ม. จุดสั่งซื้อ 60 ตร.ม.",
    meta: { material_id: "mat-01" },
    ageDays: 0,
  }),
  act({
    id: "act-sys-02",
    order_id: null,
    activity_type: "stock",
    actor_id: null,
    actor_label: "ระบบ",
    from_status: null,
    to_status: null,
    message:
      "หมึกซับลิเมชัน CMYK (MAT-INK-01) ต่ำกว่าจุดสั่งซื้อ — คงเหลือ 8.5 ลิตร จุดสั่งซื้อ 15 ลิตร เสี่ยงหมดกลางสายพิมพ์",
    meta: { material_id: "mat-04" },
    ageDays: 0,
  }),
  act({
    id: "act-sys-03",
    order_id: null,
    activity_type: "system",
    actor_id: null,
    actor_label: "ระบบ",
    from_status: null,
    to_status: null,
    message: "เครื่องตัด & เย็บโพ้งขอบพรม (CS-01) เข้าสู่สถานะซ่อมบำรุง",
    meta: { machine_id: "mac-cut" },
    ageDays: 0,
  }),
];
