// conversations.ts — กล่องแชทรวม (mock ZAAPI) 10 ห้อง ครบ 3 ช่องทาง + messages
import type { MattiiConversation, MattiiMessage } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

export const conversations: MattiiConversation[] = [
  {
    id: "conv-01",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-01",
    channel: "line",
    external_thread_id: "zaapi-line-th-1001",
    subject_preview: "รบกวนสอบถามพรมลายแมวส้มค่ะ",
    status: "closed",
    assigned_staff_id: "stf-sale-1",
    unread_count: 0,
    last_message_at: daysAgo(1, 10, 30),
    linked_order_id: "ord-01",
    created_at: daysAgo(1, 9, 0),
    updated_at: daysAgo(1, 10, 30),
  },
  {
    id: "conv-02",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-02",
    channel: "facebook",
    external_thread_id: "zaapi-fb-th-1002",
    subject_preview: "อยากได้พรมลายดอกไม้พาสเทลค่ะ",
    status: "pending",
    assigned_staff_id: "stf-sale-1",
    unread_count: 1,
    last_message_at: daysAgo(0, 8, 15),
    linked_order_id: "ord-02",
    created_at: daysAgo(0, 8, 0),
    updated_at: daysAgo(0, 8, 15),
  },
  {
    id: "conv-03",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-03",
    channel: "tiktok",
    external_thread_id: "zaapi-tt-th-1003",
    subject_preview: "ลดได้อีกไหมครับ สั่ง 2 ผืน",
    status: "open",
    assigned_staff_id: "stf-sale-2",
    unread_count: 2,
    last_message_at: daysAgo(3, 14, 0),
    linked_order_id: "ord-03",
    created_at: daysAgo(3, 13, 0),
    updated_at: daysAgo(3, 14, 0),
  },
  {
    id: "conv-04",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-04",
    channel: "line",
    external_thread_id: "zaapi-line-th-1004",
    subject_preview: "สั่งแผ่นรองจานพิมพ์โลโก้ร้านกาแฟ",
    status: "closed",
    assigned_staff_id: "stf-sale-1",
    unread_count: 0,
    last_message_at: daysAgo(2, 16, 0),
    linked_order_id: "ord-04",
    created_at: daysAgo(2, 15, 0),
    updated_at: daysAgo(2, 16, 0),
  },
  {
    id: "conv-05",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-15",
    channel: "tiktok",
    external_thread_id: "zaapi-tt-th-1005",
    subject_preview: "รอบผลิตเข้าคิวหรือยังคะ",
    status: "closed",
    assigned_staff_id: "stf-sale-2",
    unread_count: 0,
    last_message_at: daysAgo(12, 9, 0),
    linked_order_id: "ord-15",
    created_at: daysAgo(13, 10, 0),
    updated_at: daysAgo(12, 9, 0),
  },
  {
    id: "conv-06",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-16",
    channel: "facebook",
    external_thread_id: "zaapi-fb-th-1006",
    subject_preview: "งานด่วนนี้เลยกำหนดหรือยังคะ",
    status: "open",
    assigned_staff_id: "stf-sale-1",
    unread_count: 3,
    last_message_at: daysAgo(0, 11, 0),
    linked_order_id: "ord-16",
    created_at: daysAgo(14, 9, 0),
    updated_at: daysAgo(0, 11, 0),
  },
  {
    id: "conv-07",
    org_id: MOCK_ORG_ID,
    customer_id: "cus-24",
    channel: "tiktok",
    external_thread_id: "zaapi-tt-th-1007",
    subject_preview: "ขอบคุณค่ะ ได้รับพรมแล้ว สวยมาก",
    status: "closed",
    assigned_staff_id: "stf-sale-1",
    unread_count: 0,
    last_message_at: daysAgo(1, 18, 0),
    linked_order_id: "ord-28",
    created_at: daysAgo(16, 9, 0),
    updated_at: daysAgo(1, 18, 0),
  },
  {
    id: "conv-08",
    org_id: MOCK_ORG_ID,
    customer_id: null,
    channel: "line",
    external_thread_id: "zaapi-line-th-1008",
    subject_preview: "พรมเช็ดเท้าราคาเท่าไหร่คะ",
    status: "open",
    assigned_staff_id: "stf-sale-2",
    unread_count: 1,
    last_message_at: daysAgo(0, 13, 20),
    linked_order_id: null,
    created_at: daysAgo(0, 13, 0),
    updated_at: daysAgo(0, 13, 20),
  },
  {
    id: "conv-09",
    org_id: MOCK_ORG_ID,
    customer_id: null,
    channel: "facebook",
    external_thread_id: "zaapi-fb-th-1009",
    subject_preview: "สั่ง 10 ผืนลดได้เท่าไหร่ครับ",
    status: "pending",
    assigned_staff_id: "stf-sale-1",
    unread_count: 0,
    last_message_at: daysAgo(1, 15, 0),
    linked_order_id: null,
    created_at: daysAgo(1, 14, 0),
    updated_at: daysAgo(1, 15, 0),
  },
  {
    // ★ conv-10 = ห้องตัวอย่างสำหรับ AI mock "สรุปแชท → ร่างออเดอร์" (§5.1) — เนื้อหาตั้งใจให้ AI มั่นใจ
    // ส่วนสินค้า/ลาย แต่ "ขนาด" กับ "จำนวน" ยังคลุมเครือ (ลูกค้าไม่ได้ระบุชัด) → ai-mocks.ts ควร mock ผลลัพธ์
    // เป็น draft ที่มี 2 ช่องต้องตรวจ (size, qty) ให้ Sale ยืนยันก่อนบันทึกเสมอ (ห้ามบันทึกอัตโนมัติ)
    id: "conv-10",
    org_id: MOCK_ORG_ID,
    customer_id: null,
    channel: "tiktok",
    external_thread_id: "zaapi-tt-th-1010",
    subject_preview: "ทำลายรูปสัตว์เลี้ยงได้ไหมคะ",
    status: "open",
    assigned_staff_id: "stf-sale-2",
    unread_count: 2,
    last_message_at: daysAgo(0, 7, 45),
    linked_order_id: null,
    created_at: daysAgo(0, 7, 30),
    updated_at: daysAgo(0, 7, 45),
  },
];

function msg(m: Omit<MattiiMessage, "org_id" | "created_at" | "updated_at">): MattiiMessage {
  return { ...m, org_id: MOCK_ORG_ID, created_at: m.sent_at, updated_at: m.sent_at };
}

export const messages: MattiiMessage[] = [
  // conv-01
  msg({
    id: "msg-01-1",
    conversation_id: "conv-01",
    direction: "inbound",
    sender_name: "พลอยไพลิน",
    body: "สวัสดีค่ะ รบกวนสอบถามพรมลายแมวส้มพื้นครีมค่ะ อยากได้ขนาด 60x90",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 9, 0),
  }),
  msg({
    id: "msg-01-2",
    conversation_id: "conv-01",
    direction: "inbound",
    sender_name: "พลอยไพลิน",
    body: "รูปลายที่อยากได้ค่ะ",
    attachment_url: "/mock/mattii/chat/cat-orange-ref.jpg",
    attachment_kind: "image",
    sent_at: daysAgo(1, 9, 5),
  }),
  msg({
    id: "msg-01-3",
    conversation_id: "conv-01",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "สวัสดีค่ะ ขนาด 60x90 ราคา 490 บาทค่ะ พิมพ์ลายเต็มผืนตามรูปได้เลยค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 9, 20),
  }),
  msg({
    id: "msg-01-4",
    conversation_id: "conv-01",
    direction: "inbound",
    sender_name: "พลอยไพลิน",
    body: "โอเคค่ะ สั่งเลยค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 10, 30),
  }),

  // conv-02
  msg({
    id: "msg-02-1",
    conversation_id: "conv-02",
    direction: "inbound",
    sender_name: "อรวรรณ",
    body: "อยากได้พรมห้องนั่งเล่นลายดอกไม้พาสเทลค่ะ ขนาด 80x120",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 8, 0),
  }),
  msg({
    id: "msg-02-2",
    conversation_id: "conv-02",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "ได้ค่ะ ขนาดนี้ราคา 990 บาทค่ะ มีลายดอกไม้พาสเทลให้เลือกหลายแบบเลยค่ะ ส่งตัวอย่างให้ดูนะคะ",
    attachment_url: "/mock/mattii/catalog/pastel-flower-samples.jpg",
    attachment_kind: "image",
    sent_at: daysAgo(0, 8, 10),
  }),
  msg({
    id: "msg-02-3",
    conversation_id: "conv-02",
    direction: "inbound",
    sender_name: "อรวรรณ",
    body: "สวยค่ะ เดี๋ยวขอดูก่อนนะคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 8, 15),
  }),

  // conv-03
  msg({
    id: "msg-03-1",
    conversation_id: "conv-03",
    direction: "inbound",
    sender_name: "ธนภรณ์",
    body: "สนใจพรมหน้าบ้านไมโครไฟเบอร์ค่ะ สั่ง 2 ผืน ลายการ์ตูนหมี",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(3, 13, 0),
  }),
  msg({
    id: "msg-03-2",
    conversation_id: "conv-03",
    direction: "outbound",
    sender_name: "ณัฐพล (Sale)",
    body: "ขนาด 60x90 ผืนละ 450 บาทค่ะ สั่ง 2 ผืน รวม 900 บาท",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(3, 13, 30),
  }),
  msg({
    id: "msg-03-3",
    conversation_id: "conv-03",
    direction: "inbound",
    sender_name: "ธนภรณ์",
    body: "ลดได้อีกไหมคะ สั่ง 2 ผืนพร้อมกันเลย",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(3, 13, 45),
  }),
  msg({
    id: "msg-03-4",
    conversation_id: "conv-03",
    direction: "outbound",
    sender_name: "ณัฐพล (Sale)",
    body: "ลดให้ 50 บาทค่ะ เหลือ 850 บาทรวมทั้งหมดนะคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(3, 14, 0),
  }),

  // conv-04
  msg({
    id: "msg-04-1",
    conversation_id: "conv-04",
    direction: "inbound",
    sender_name: "สุภาพร",
    body: "อยากทำแผ่นรองจานพิมพ์โลโก้ร้านกาแฟค่ะ 4 ผืน",
    attachment_url: "/mock/mattii/chat/coffee-logo.png",
    attachment_kind: "image",
    sent_at: daysAgo(2, 15, 0),
  }),
  msg({
    id: "msg-04-2",
    conversation_id: "conv-04",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "ได้ค่ะ ขนาด 40x60 ผืนละ 290 บาท 4 ผืนรวม 1,160 บาทค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(2, 15, 30),
  }),
  msg({
    id: "msg-04-3",
    conversation_id: "conv-04",
    direction: "inbound",
    sender_name: "สุภาพร",
    body: "โอเคค่ะ สั่งเลย",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(2, 16, 0),
  }),

  // conv-05
  msg({
    id: "msg-05-1",
    conversation_id: "conv-05",
    direction: "inbound",
    sender_name: "อภิสิทธิ์",
    body: "ออเดอร์ MT-2026-0075 เข้าคิวพิมพ์รึยังคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(13, 10, 0),
  }),
  msg({
    id: "msg-05-2",
    conversation_id: "conv-05",
    direction: "outbound",
    sender_name: "ณัฐพล (Sale)",
    body: "เข้าคิวเครื่องพิมพ์ผ้าแล้วค่ะ คาดว่าเสร็จใน 2 วันค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(12, 9, 0),
  }),

  // conv-06
  msg({
    id: "msg-06-1",
    conversation_id: "conv-06",
    direction: "inbound",
    sender_name: "สุรชัย",
    body: "ของด่วนที่สั่งไว้ เลยกำหนดส่งหรือยังคะ กังวลมากเลย",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 10, 0),
  }),
  msg({
    id: "msg-06-2",
    conversation_id: "conv-06",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "ขออภัยด้วยค่ะ ตอนแรกพิมพ์แล้ว QC ไม่ผ่านสีเพี้ยน ตอนนี้กำลังพิมพ์ซ้ำเร่งด่วนให้ค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 10, 30),
  }),
  msg({
    id: "msg-06-3",
    conversation_id: "conv-06",
    direction: "inbound",
    sender_name: "สุรชัย",
    body: "โอเคค่ะ รบกวนเร่งให้หน่อยนะคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 11, 0),
  }),

  // conv-07
  msg({
    id: "msg-07-1",
    conversation_id: "conv-07",
    direction: "inbound",
    sender_name: "มะลิวัลย์",
    body: "อยากได้พรมเช็ดเท้าลายแมวส้ม โลโก้ร้านกาแฟบ้านมะลิด้วยค่ะ 2 ผืน",
    attachment_url: "/mock/mattii/chat/baanmali-logo.png",
    attachment_kind: "image",
    sent_at: daysAgo(16, 9, 0),
  }),
  msg({
    id: "msg-07-2",
    conversation_id: "conv-07",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "รับเลยค่ะ ทีมกราฟิกจะออกแบบให้ดูก่อนนะคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(16, 9, 30),
  }),
  msg({
    id: "msg-07-3",
    conversation_id: "conv-07",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "ของถึงแล้วนะคะ เก็บเงินปลายทางเรียบร้อยค่ะ ขอบคุณค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 17, 0),
  }),
  msg({
    id: "msg-07-4",
    conversation_id: "conv-07",
    direction: "inbound",
    sender_name: "มะลิวัลย์",
    body: "ขอบคุณค่ะ ได้รับพรมแล้ว สวยมาก จะสั่งอีกแน่นอนค่ะ",
    attachment_url: "/mock/mattii/chat/baanmali-received.jpg",
    attachment_kind: "image",
    sent_at: daysAgo(1, 18, 0),
  }),

  // conv-08 (ยังไม่มีออเดอร์)
  msg({
    id: "msg-08-1",
    conversation_id: "conv-08",
    direction: "inbound",
    sender_name: "ลูกค้า LINE",
    body: "พรมเช็ดเท้าราคาเริ่มต้นเท่าไหร่คะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 13, 0),
  }),
  msg({
    id: "msg-08-2",
    conversation_id: "conv-08",
    direction: "outbound",
    sender_name: "ณัฐพล (Sale)",
    body: "เริ่มต้น 290 บาทค่ะ ขนาด 40x60 เลือกลายเองหรือให้ทีมออกแบบให้ก็ได้ค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 13, 15),
  }),
  msg({
    id: "msg-08-3",
    conversation_id: "conv-08",
    direction: "inbound",
    sender_name: "ลูกค้า LINE",
    body: "ขอดูตัวอย่างลายหน่อยค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 13, 20),
  }),

  // conv-09 (ยังไม่มีออเดอร์)
  msg({
    id: "msg-09-1",
    conversation_id: "conv-09",
    direction: "inbound",
    sender_name: "ลูกค้า Facebook",
    body: "สั่ง 10 ผืนพร้อมกันลดได้เท่าไหร่ครับ ทำแจกลูกค้าร้าน",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 14, 0),
  }),
  msg({
    id: "msg-09-2",
    conversation_id: "conv-09",
    direction: "outbound",
    sender_name: "พิมพ์ใจ (Sale)",
    body: "สั่ง 10 ผืนขึ้นไปมีส่วนลดค่ะ รบกวนแจ้งขนาด+ลายที่ต้องการก่อนนะคะ จะคำนวณราคาให้ค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(1, 15, 0),
  }),

  // conv-10 (ยังไม่มีออเดอร์)
  msg({
    id: "msg-10-1",
    conversation_id: "conv-10",
    direction: "inbound",
    sender_name: "ลูกค้า TikTok",
    body: "ทำลายรูปสัตว์เลี้ยงตัวเองได้ไหมคะ อยากเอารูปหมาที่บ้านมาพิมพ์",
    attachment_url: "/mock/mattii/chat/pet-photo-ref.jpg",
    attachment_kind: "image",
    sent_at: daysAgo(0, 7, 30),
  }),
  msg({
    id: "msg-10-2",
    conversation_id: "conv-10",
    direction: "outbound",
    sender_name: "ณัฐพล (Sale)",
    body: "ได้เลยค่ะ ส่งรูปคมชัดมาได้เลย ทีมกราฟิกจะจัดองค์ประกอบให้สวยงามค่ะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 7, 40),
  }),
  msg({
    id: "msg-10-3",
    conversation_id: "conv-10",
    direction: "inbound",
    sender_name: "ลูกค้า TikTok",
    body: "โอเคค่ะ เดี๋ยวส่งรูปที่ชัดกว่านี้ให้นะคะ",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 7, 45),
  }),
  msg({
    id: "msg-10-4",
    conversation_id: "conv-10",
    direction: "inbound",
    sender_name: "ลูกค้า TikTok",
    body: "เอาแบบพรมเช็ดเท้ากำมะหยี่นะคะ แต่ยังไม่แน่ใจว่าจะเอาขนาดไหนดี กับจำนวนก็ยังไม่ตัดสินใจค่ะ เดี๋ยวถามที่บ้านก่อน",
    attachment_url: null,
    attachment_kind: null,
    sent_at: daysAgo(0, 7, 50),
  }),
];
