// customers.ts — ลูกค้า 27 ราย กระจายหลายจังหวัด/ช่องทาง/tier
// total_orders + total_spent คำนวณให้ตรงกับ orders.ts เป๊ะ (ดู Review note ท้ายไฟล์)
import type { MattiiCustomer } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function cus(
  c: Omit<MattiiCustomer, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiCustomer {
  const { ageDays, ...rest } = c;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 3)),
  };
}

export const customers: MattiiCustomer[] = [
  cus({
    id: "cus-01",
    code: "CUS-0101",
    display_name: "บ้านมะลิ x น้องพลอย",
    full_name: "พลอยไพลิน เจริญสุข",
    phone: "081-234-5601",
    primary_channel: "line",
    channel_handles: { line: "ploy_baanmali" },
    tier: "regular",
    address_line: "88/12 หมู่บ้านสวนทอง",
    subdistrict: "บางบัวทอง",
    district: "บางบัวทอง",
    province: "นนทบุรี",
    postcode: "11110",
    total_orders: 2,
    total_spent: 1580,
    note: "ลูกค้าประจำ ชอบลายแมวส้ม สั่งซ้ำหลายรอบ",
    ageDays: 90,
  }),
  cus({
    id: "cus-02",
    code: "CUS-0102",
    display_name: "ร้านดอกไม้พาสเทล",
    full_name: "อรวรรณ ใจงาม",
    phone: "089-112-2345",
    primary_channel: "facebook",
    channel_handles: { facebook: "PastelFlowerShop" },
    tier: "new",
    address_line: "23 ถ.นิมมานเหมินท์",
    subdistrict: "สุเทพ",
    district: "เมืองเชียงใหม่",
    province: "เชียงใหม่",
    postcode: "50200",
    total_orders: 2,
    total_spent: 1330,
    note: null,
    ageDays: 12,
  }),
  cus({
    id: "cus-03",
    code: "CUS-0103",
    display_name: "หมีน้อยช็อป",
    full_name: "ธนภรณ์ สินสมบูรณ์",
    phone: "092-333-1188",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@meenoi.shop" },
    tier: "new",
    address_line: "56 ถ.มิตรภาพ",
    subdistrict: "ในเมือง",
    district: "เมืองขอนแก่น",
    province: "ขอนแก่น",
    postcode: "40000",
    total_orders: 2,
    total_spent: 1190,
    note: "ต่อราคาก่อนปิดการขาย",
    ageDays: 6,
  }),
  cus({
    id: "cus-04",
    code: "CUS-0104",
    display_name: "คาเฟ่ริมคลอง",
    full_name: "สุภาพร วงศ์เจริญ",
    phone: "085-777-9900",
    primary_channel: "line",
    channel_handles: { line: "cafe_rimklong" },
    tier: "new",
    address_line: "199 ถ.เจริญนคร",
    subdistrict: "คลองต้นไทร",
    district: "คลองสาน",
    province: "กรุงเทพมหานคร",
    postcode: "10600",
    total_orders: 2,
    total_spent: 1460,
    note: "สั่งแผ่นรองจานพิมพ์โลโก้ร้าน",
    ageDays: 5,
  }),
  cus({
    id: "cus-05",
    code: "CUS-0105",
    display_name: "บ้านมะลิโฮมสเตย์",
    full_name: "วิภาวดี มงคลชัย",
    phone: "081-999-2211",
    primary_channel: "facebook",
    channel_handles: { facebook: "Baanmali.Homestay" },
    tier: "regular",
    address_line: "45 ถ.เจริญกรุง",
    subdistrict: "บางรัก",
    district: "บางรัก",
    province: "กรุงเทพมหานคร",
    postcode: "10500",
    total_orders: 2,
    total_spent: 1380,
    note: "ลูกค้าประจำ สั่งพรมชื่อบ้านหลายผืน",
    ageDays: 60,
  }),
  cus({
    id: "cus-06",
    code: "CUS-0106",
    display_name: "ห้องเด็กไดโนเสาร์",
    full_name: "กมลชนก ทองแท้",
    phone: "086-222-3344",
    primary_channel: "line",
    channel_handles: { line: "kamon_dino" },
    tier: "new",
    address_line: "12 ถ.สุขาภิบาล 3",
    subdistrict: "บางชัน",
    district: "คลองสามวา",
    province: "กรุงเทพมหานคร",
    postcode: "10510",
    total_orders: 2,
    total_spent: 1070,
    note: null,
    ageDays: 4,
  }),
  cus({
    id: "cus-07",
    code: "CUS-0107",
    display_name: "แมวส้มสตูดิโอ",
    full_name: "ปิยะดา ศรีสวัสดิ์",
    phone: "093-456-7788",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@orangecat.studio" },
    tier: "new",
    address_line: "77 ถ.ประชาอุทิศ",
    subdistrict: "ทุ่งครุ",
    district: "ทุ่งครุ",
    province: "กรุงเทพมหานคร",
    postcode: "10140",
    total_orders: 2,
    total_spent: 970,
    note: "ยังไม่ได้รับชำระ แต่เดินสถานะไปแล้ว (ทดสอบ ไม่บล็อก)",
    ageDays: 6,
  }),
  cus({
    id: "cus-08",
    code: "CUS-0108",
    display_name: "ภูเขาสตูดิโอ",
    full_name: "ณัฐวุฒิ ไพรงาม",
    phone: "084-555-6677",
    primary_channel: "facebook",
    channel_handles: { facebook: "MountainStudio.th" },
    tier: "vip",
    address_line: "3 ถ.ห้วยแก้ว",
    subdistrict: "ช้างเผือก",
    district: "เมืองเชียงใหม่",
    province: "เชียงใหม่",
    postcode: "50300",
    total_orders: 2,
    total_spent: 1480,
    note: "ลูกค้า VIP งานกราฟิกละเอียดสูง",
    ageDays: 75,
  }),
  cus({
    id: "cus-09",
    code: "CUS-0109",
    display_name: "นวดแผนไทยสายลม",
    full_name: "จิราภรณ์ แสงทอง",
    phone: "090-888-1122",
    primary_channel: "line",
    channel_handles: { line: "saailom_massage" },
    tier: "regular",
    address_line: "9 ถ.สายลม",
    subdistrict: "สามเสนใน",
    district: "พญาไท",
    province: "กรุงเทพมหานคร",
    postcode: "10400",
    total_orders: 2,
    total_spent: 1630,
    note: "สั่งพรมโลโก้ร้านนวดหลายสาขา",
    ageDays: 55,
  }),
  cus({
    id: "cus-10",
    code: "CUS-0110",
    display_name: "ร้านกาแฟบ้านสวน",
    full_name: "อนุสรณ์ พูนสุข",
    phone: "087-321-6655",
    primary_channel: "facebook",
    channel_handles: { facebook: "BaanSuanCafe" },
    tier: "vip",
    address_line: "168 ถ.เลียบคลอง 6",
    subdistrict: "คลองหก",
    district: "คลองหลวง",
    province: "ปทุมธานี",
    postcode: "12120",
    total_orders: 2,
    total_spent: 1330,
    note: "รอ CF นานผิดปกติ ต้องติดตาม",
    ageDays: 20,
  }),
  cus({
    id: "cus-11",
    code: "CUS-0111",
    display_name: "นกฮูกน้อยช็อป",
    full_name: "ศศิธร บุญมาก",
    phone: "091-234-8899",
    primary_channel: "line",
    channel_handles: { line: "nokhoo.shop" },
    tier: "new",
    address_line: "34 ถ.ศรีนครินทร์",
    subdistrict: "หนองบอน",
    district: "ประเวศ",
    province: "กรุงเทพมหานคร",
    postcode: "10250",
    total_orders: 2,
    total_spent: 940,
    note: null,
    ageDays: 8,
  }),
  cus({
    id: "cus-12",
    code: "CUS-0112",
    display_name: "ดอกไม้ริมทาง",
    full_name: "รัตนาภรณ์ ศรีจันทร์",
    phone: "062-111-5566",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@flower.roadside" },
    tier: "new",
    address_line: "21 ถ.เพชรเกษม",
    subdistrict: "หาดใหญ่",
    district: "หาดใหญ่",
    province: "สงขลา",
    postcode: "90110",
    total_orders: 2,
    total_spent: 880,
    note: null,
    ageDays: 3,
  }),
  cus({
    id: "cus-13",
    code: "CUS-0113",
    display_name: "ฟาร์มลูกสุนัขน่ารัก",
    full_name: "ธีรเดช คงมั่น",
    phone: "089-777-4433",
    primary_channel: "line",
    channel_handles: { line: "puppy.farm.th" },
    tier: "new",
    address_line: "56 หมู่ 4",
    subdistrict: "บ้านฉาง",
    district: "บ้านฉาง",
    province: "ระยอง",
    postcode: "21130",
    total_orders: 2,
    total_spent: 1240,
    note: null,
    ageDays: 6,
  }),
  cus({
    id: "cus-14",
    code: "CUS-0114",
    display_name: "กาแล็กซี่ดีไซน์",
    full_name: "พีรพัฒน์ วิศิษฏ์ศิลป์",
    phone: "094-555-8877",
    primary_channel: "facebook",
    channel_handles: { facebook: "GalaxyDesign.th" },
    tier: "vip",
    address_line: "8 ถ.บายพาส",
    subdistrict: "ในเมือง",
    district: "เมืองนครราชสีมา",
    province: "นครราชสีมา",
    postcode: "30000",
    total_orders: 1,
    total_spent: 1970,
    note: "งานสั่งตัดพิเศษ ราคาสูง",
    ageDays: 8,
  }),
  cus({
    id: "cus-15",
    code: "CUS-0115",
    display_name: "แมวส้มมินิมาร์ท",
    full_name: "อภิสิทธิ์ ทองมี",
    phone: "085-222-9911",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@orangecat.minimart" },
    tier: "regular",
    address_line: "10 ถ.เฉลิมพระเกียรติ",
    subdistrict: "หนองปรือ",
    district: "บางละมุง",
    province: "ชลบุรี",
    postcode: "20150",
    total_orders: 1,
    total_spent: 1030,
    note: "ยังไม่ได้รับชำระ แต่เข้าคิวพิมพ์แล้ว",
    ageDays: 12,
  }),
  cus({
    id: "cus-16",
    code: "CUS-0116",
    display_name: "ป่าเขียวรีสอร์ท",
    full_name: "สุรชัย ป่าไพร",
    phone: "081-666-3322",
    primary_channel: "facebook",
    channel_handles: { facebook: "PaKhiaoResort" },
    tier: "regular",
    address_line: "99 หมู่ 2",
    subdistrict: "แม่แรม",
    district: "แม่ริม",
    province: "เชียงใหม่",
    postcode: "50180",
    total_orders: 1,
    total_spent: 1040,
    note: "งานด่วน เลยกำหนดส่งแล้ว — ตามงานให้ไว",
    ageDays: 14,
  }),
  cus({
    id: "cus-17",
    code: "CUS-0117",
    display_name: "การ์ดวันเกิด บาย นิว",
    full_name: "นิภาพร รักดี",
    phone: "086-999-7744",
    primary_channel: "line",
    channel_handles: { line: "new.birthdaycard" },
    tier: "new",
    address_line: "5 ถ.เทศบาล",
    subdistrict: "ในเมือง",
    district: "เมืองอุบลราชธานี",
    province: "อุบลราชธานี",
    postcode: "34000",
    total_orders: 2,
    total_spent: 950,
    note: "งานด่วน ใกล้กำหนดส่ง",
    ageDays: 5,
  }),
  cus({
    id: "cus-18",
    code: "CUS-0118",
    display_name: "ผีเสื้อสีสันช็อป",
    full_name: "ชลธิชา แสนสุข",
    phone: "092-444-8811",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@butterfly.colorful" },
    tier: "new",
    address_line: "31 ถ.ทับเที่ยง",
    subdistrict: "ทับเที่ยง",
    district: "เมืองตรัง",
    province: "ตรัง",
    postcode: "92000",
    total_orders: 1,
    total_spent: 830,
    note: null,
    ageDays: 9,
  }),
  cus({
    id: "cus-19",
    code: "CUS-0119",
    display_name: "รถแข่งจิ๋ว",
    full_name: "กิตติศักดิ์ ชัยมงคล",
    phone: "083-222-6611",
    primary_channel: "facebook",
    channel_handles: { facebook: "MiniRaceCar.th" },
    tier: "new",
    address_line: "14 ถ.มิตรภาพ",
    subdistrict: "ในเมือง",
    district: "เมืองอุดรธานี",
    province: "อุดรธานี",
    postcode: "41000",
    total_orders: 2,
    total_spent: 680,
    note: null,
    ageDays: 7,
  }),
  cus({
    id: "cus-20",
    code: "CUS-0120",
    display_name: "มะม่วงบ้านสวน",
    full_name: "ปรียานุช ทองสุข",
    phone: "090-333-5588",
    primary_channel: "line",
    channel_handles: { line: "mamuang.homefarm" },
    tier: "new",
    address_line: "6 หมู่ 7",
    subdistrict: "บางกร่าง",
    district: "เมืองนนทบุรี",
    province: "นนทบุรี",
    postcode: "11000",
    total_orders: 2,
    total_spent: 880,
    note: null,
    ageDays: 9,
  }),
  cus({
    id: "cus-21",
    code: "CUS-0121",
    display_name: "ครบรอบ 10 ปี",
    full_name: "ธัญญารัตน์ ไชยวงศ์",
    phone: "088-111-4499",
    primary_channel: "line",
    channel_handles: { line: "10th.anniversary" },
    tier: "new",
    address_line: "40 ถ.เพชรเกษม",
    subdistrict: "บางแค",
    district: "บางแค",
    province: "กรุงเทพมหานคร",
    postcode: "10160",
    total_orders: 1,
    total_spent: 340,
    note: null,
    ageDays: 3,
  }),
  cus({
    id: "cus-22",
    code: "CUS-0122",
    display_name: "สตรีทอาร์ตกราฟฟิตี้",
    full_name: "วรากร ศิลป์ดี",
    phone: "064-777-2233",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@street.graffiti.art" },
    tier: "new",
    address_line: "18 ถ.นิพัทธ์อุทิศ",
    subdistrict: "หาดใหญ่",
    district: "หาดใหญ่",
    province: "สงขลา",
    postcode: "90110",
    total_orders: 1,
    total_spent: 800,
    note: "ยังค้างชำระบางส่วนแม้ส่งของแล้ว",
    ageDays: 15,
  }),
  cus({
    id: "cus-23",
    code: "CUS-0123",
    display_name: "แฟนคลับทีมฟุตบอล",
    full_name: "ประวิทย์ เก่งกีฬา",
    phone: "081-555-4477",
    primary_channel: "facebook",
    channel_handles: { facebook: "FootballFanClub.th" },
    tier: "new",
    address_line: "27 ถ.สุขุมวิท",
    subdistrict: "บางนา",
    district: "บางนา",
    province: "กรุงเทพมหานคร",
    postcode: "10260",
    total_orders: 1,
    total_spent: 1420,
    note: null,
    ageDays: 18,
  }),
  cus({
    id: "cus-24",
    code: "CUS-0124",
    display_name: "ร้านกาแฟบ้านมะลิ (TikTok)",
    full_name: "มะลิวัลย์ เจริญพร",
    phone: "095-888-2244",
    primary_channel: "tiktok",
    channel_handles: { tiktok: "@baanmali.coffee" },
    tier: "regular",
    address_line: "77/8 ถ.รัชดาภิเษก",
    subdistrict: "ดินแดง",
    district: "ดินแดง",
    province: "กรุงเทพมหานคร",
    postcode: "10400",
    total_orders: 1,
    total_spent: 1030,
    note: "ออเดอร์ตัวอย่าง demo เต็มเส้น: แชท→ผลิตซ้ำ→ส่งสำเร็จ",
    ageDays: 16,
  }),
  cus({
    id: "cus-25",
    code: "CUS-0125",
    display_name: "จักรวาลกาแล็กซี่ 2",
    full_name: "อรรถพล ดาวเรือง",
    phone: "089-222-6677",
    primary_channel: "line",
    channel_handles: { line: "galaxy.universe2" },
    tier: "new",
    address_line: "50 ถ.สรรพสิทธิ์",
    subdistrict: "ในเมือง",
    district: "เมืองอุบลราชธานี",
    province: "อุบลราชธานี",
    postcode: "34000",
    total_orders: 1,
    total_spent: 1540,
    note: "ออเดอร์กำไรติดลบ — พิมพ์ซ้ำ 2 รอบ ต้นทุนบานปลาย",
    ageDays: 22,
  }),
  cus({
    id: "cus-26",
    code: "CUS-0126",
    display_name: "ลูกแมวส้มน้อย",
    full_name: "เบญจวรรณ พงษ์ไพร",
    phone: "082-333-9922",
    primary_channel: "facebook",
    channel_handles: { facebook: "OrangeKitten.shop" },
    tier: "new",
    address_line: "63 ถ.เจริญราษฎร์",
    subdistrict: "บางโคล่",
    district: "บางคอแหลม",
    province: "กรุงเทพมหานคร",
    postcode: "10120",
    total_orders: 1,
    total_spent: 0,
    note: "ยกเลิกออเดอร์ + คืนเงินมัดจำแล้ว",
    ageDays: 10,
  }),
  cus({
    id: "cus-27",
    code: "CUS-0127",
    display_name: "รอสีที่ใช่",
    full_name: "กัญญารัตน์ มีสุข",
    phone: "086-444-1177",
    primary_channel: "line",
    channel_handles: { line: "waiting.rightcolor" },
    tier: "new",
    address_line: "15 ถ.มหิดล",
    subdistrict: "หายยา",
    district: "เมืองเชียงใหม่",
    province: "เชียงใหม่",
    postcode: "50100",
    total_orders: 1,
    total_spent: 540,
    note: "พักออเดอร์ไว้ รอโอนเงินก้อนใหญ่สิ้นเดือน",
    ageDays: 11,
  }),
];

// หมายเหตุ: cus-26 total_spent=0 เพราะออเดอร์ถูกยกเลิก+คืนเงินมัดจำแล้ว (total_amount เดิม 340 ฿
// แต่ไม่นับเป็นยอดซื้อสะสมจริงเนื่องจากไม่ได้ส่งของ) — ตรงกับ orders.ts (O31 cancelled, refunded)
