// design.ts — งานแบบลาย + เวอร์ชันไฟล์ (mattii_design_jobs + mattii_design_versions)
// สร้างอัตโนมัติทุกออเดอร์ที่ผ่าน quoted→confirmed แล้ว (ไม่รวม ord-31 ที่ยกเลิกตั้งแต่ quoted)
import type { MattiiDesignJob, MattiiDesignVersion } from "./types";
import { MOCK_ORG_ID, daysAgo, dateOnlyFromNow } from "./helpers";

function job(
  j: Omit<MattiiDesignJob, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiDesignJob {
  const { ageDays, ...rest } = j;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const designJobs: MattiiDesignJob[] = [
  job({
    id: "dsj-05",
    order_id: "ord-05",
    job_no: "DSN-0065",
    design_source: "customer_file",
    status: "queued",
    assigned_designer_id: null,
    brief: "พิมพ์ตามไฟล์ลูกค้า ชื่อบ้าน 'บ้านมะลิ'",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-3),
    started_at: null,
    approved_at: null,
    ageDays: 4,
  }),
  job({
    id: "dsj-06",
    order_id: "ord-06",
    job_no: "DSN-0066",
    design_source: "customer_file",
    status: "queued",
    assigned_designer_id: null,
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายไดโนเสาร์",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-2),
    started_at: null,
    approved_at: null,
    ageDays: 3,
  }),

  job({
    id: "dsj-07",
    order_id: "ord-07",
    job_no: "DSN-0067",
    design_source: "customer_file",
    status: "in_progress",
    assigned_designer_id: "stf-design-1",
    brief: "จัดองค์ประกอบไฟล์ลูกค้า ลายแมวส้มพื้นครีม ให้พอดีขนาด 40x60",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-4),
    started_at: daysAgo(4),
    approved_at: null,
    ageDays: 5,
  }),
  job({
    id: "dsj-08",
    order_id: "ord-08",
    job_no: "DSN-0068",
    design_source: "in_house",
    status: "in_progress",
    assigned_designer_id: "stf-design-2",
    brief: "ออกแบบลายภูเขาสีพาสเทล ตามธีมที่ลูกค้า VIP ชอบ",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-4),
    started_at: daysAgo(4),
    approved_at: null,
    ageDays: 4,
  }),
  job({
    id: "dsj-09",
    order_id: "ord-09",
    job_no: "DSN-0069",
    design_source: "in_house",
    status: "in_progress",
    assigned_designer_id: "stf-design-1",
    brief: "ออกแบบโลโก้ร้านนวดลงพรมหน้าบ้าน",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-3),
    started_at: daysAgo(3),
    approved_at: null,
    ageDays: 3,
  }),

  job({
    id: "dsj-10",
    order_id: "ord-10",
    job_no: "DSN-0070",
    design_source: "in_house",
    status: "waiting_cf",
    assigned_designer_id: "stf-design-2",
    brief: "ลายแมวส้มพื้นครีม ลูกค้าขอแก้สีพื้นรอบแรก",
    cf_status: "sent",
    revision_count: 1,
    approved_version_id: null,
    due_at: daysAgo(-1),
    started_at: daysAgo(19),
    approved_at: null,
    ageDays: 20,
  }),
  job({
    id: "dsj-11",
    order_id: "ord-11",
    job_no: "DSN-0071",
    design_source: "in_house",
    status: "waiting_cf",
    assigned_designer_id: "stf-design-1",
    brief: "ออกแบบลายนกฮูกน่ารักโทนพาสเทล",
    cf_status: "sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-2),
    started_at: daysAgo(7),
    approved_at: null,
    ageDays: 8,
  }),
  job({
    id: "dsj-12",
    order_id: "ord-12",
    job_no: "DSN-0072",
    design_source: "customer_file",
    status: "waiting_cf",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายดอกไม้พาสเทล",
    cf_status: "sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: daysAgo(-6),
    started_at: daysAgo(2),
    approved_at: null,
    ageDays: 3,
  }),

  job({
    id: "dsj-13",
    order_id: "ord-13",
    job_no: "DSN-0073",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "ออกแบบลายลูกสุนัข 3 แบบให้เลือก",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-13-1",
    due_at: daysAgo(-2),
    started_at: daysAgo(5),
    approved_at: daysAgo(1),
    ageDays: 6,
  }),
  job({
    id: "dsj-14",
    order_id: "ord-14",
    job_no: "DSN-0074",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "ออกแบบลายจักรวาลกาแล็กซี่ สำหรับพรมสั่งตัดพิเศษ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-14-1",
    due_at: daysAgo(-2),
    started_at: daysAgo(6),
    approved_at: daysAgo(1),
    ageDays: 7,
  }),

  job({
    id: "dsj-15",
    order_id: "ord-15",
    job_no: "DSN-0075",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายแมวส้มพื้นครีม",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-15-1",
    due_at: daysAgo(-11),
    started_at: daysAgo(12),
    approved_at: daysAgo(3),
    ageDays: 12,
  }),
  job({
    id: "dsj-16",
    order_id: "ord-16",
    job_no: "DSN-0076",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายป่าเขียวชะอุ่ม",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-16-1",
    due_at: daysAgo(-12),
    started_at: daysAgo(13),
    approved_at: daysAgo(6),
    ageDays: 13,
  }),
  job({
    id: "dsj-17",
    order_id: "ord-17",
    job_no: "DSN-0077",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "ออกแบบคำอวยพรวันเกิดด่วน",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-17-1",
    due_at: daysAgo(-3),
    started_at: daysAgo(4),
    approved_at: daysAgo(1),
    ageDays: 4,
  }),

  job({
    id: "dsj-18",
    order_id: "ord-18",
    job_no: "DSN-0078",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายผีเสื้อสีสัน",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-18-1",
    due_at: daysAgo(-7),
    started_at: daysAgo(8),
    approved_at: daysAgo(2),
    ageDays: 8,
  }),
  job({
    id: "dsj-19",
    order_id: "ord-19",
    job_no: "DSN-0079",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายรถแข่ง",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-19-1",
    due_at: daysAgo(-5),
    started_at: daysAgo(6),
    approved_at: daysAgo(2),
    ageDays: 6,
  }),

  job({
    id: "dsj-20",
    order_id: "ord-20",
    job_no: "DSN-0080",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายชื่อสัตว์เลี้ยง 'มะม่วง'",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-20-1",
    due_at: daysAgo(-7),
    started_at: daysAgo(8),
    approved_at: daysAgo(3),
    ageDays: 8,
  }),
  job({
    id: "dsj-21",
    order_id: "ord-21",
    job_no: "DSN-0081",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า โลโก้ร้านอาหาร (สั่งซ้ำ)",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-21-1",
    due_at: daysAgo(-6),
    started_at: daysAgo(7),
    approved_at: daysAgo(3),
    ageDays: 7,
  }),

  job({
    id: "dsj-22",
    order_id: "ord-22",
    job_no: "DSN-0082",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายการ์ตูนแมวเหมียว",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-22-1",
    due_at: daysAgo(-8),
    started_at: daysAgo(9),
    approved_at: daysAgo(4),
    ageDays: 9,
  }),
  job({
    id: "dsj-23",
    order_id: "ord-23",
    job_no: "DSN-0083",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายวันเกิดครบรอบ ด่วน",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-23-1",
    due_at: daysAgo(-4),
    started_at: daysAgo(5),
    approved_at: daysAgo(2),
    ageDays: 5,
  }),

  job({
    id: "dsj-24",
    order_id: "ord-24",
    job_no: "DSN-0084",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "ออกแบบลายภูเขาสีพาสเทล VIP",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-24-1",
    due_at: daysAgo(-14),
    started_at: daysAgo(15),
    approved_at: daysAgo(9),
    ageDays: 15,
  }),
  job({
    id: "dsj-25",
    order_id: "ord-25",
    job_no: "DSN-0085",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายกราฟฟิตี้สตรีท",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-25-1",
    due_at: daysAgo(-13),
    started_at: daysAgo(14),
    approved_at: daysAgo(8),
    ageDays: 14,
  }),
  job({
    id: "dsj-26",
    order_id: "ord-26",
    job_no: "DSN-0086",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "ออกแบบลายผลไม้สีสด",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-26-1",
    due_at: daysAgo(-12),
    started_at: daysAgo(13),
    approved_at: daysAgo(7),
    ageDays: 13,
  }),

  job({
    id: "dsj-27",
    order_id: "ord-27",
    job_no: "DSN-0087",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายทีมฟุตบอลที่ชอบ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-27-1",
    due_at: daysAgo(6),
    started_at: daysAgo(7),
    approved_at: daysAgo(6),
    ageDays: 7,
  }),
  job({
    id: "dsj-28",
    order_id: "ord-28",
    job_no: "DSN-0088",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายแมวส้มพื้นครีม + โลโก้ร้านกาแฟบ้านมะลิ",
    cf_status: "approved",
    revision_count: 1,
    approved_version_id: "dvr-28-2",
    due_at: daysAgo(5),
    started_at: daysAgo(7),
    approved_at: daysAgo(5),
    ageDays: 8,
  }),
  job({
    id: "dsj-29",
    order_id: "ord-29",
    job_no: "DSN-0089",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายนกยูงหลากสี",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-29-1",
    due_at: daysAgo(-11),
    started_at: daysAgo(12),
    approved_at: daysAgo(6),
    ageDays: 12,
  }),
  job({
    id: "dsj-30",
    order_id: "ord-30",
    job_no: "DSN-0090",
    design_source: "in_house",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "ออกแบบลายจักรวาลกาแล็กซี่พิเศษ ผืนใหญ่ 100x150",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-30-1",
    due_at: daysAgo(8),
    started_at: daysAgo(10),
    approved_at: daysAgo(7),
    ageDays: 11,
  }),

  job({
    id: "dsj-32",
    order_id: "ord-32",
    job_no: "DSN-0092",
    design_source: "in_house",
    status: "in_progress",
    assigned_designer_id: "stf-design-1",
    brief: "ออกแบบลาย รอลูกค้าตัดสินใจสี — งานพักไว้",
    cf_status: "not_sent",
    revision_count: 0,
    approved_version_id: null,
    due_at: dateOnlyFromNow(9),
    started_at: daysAgo(9),
    approved_at: null,
    ageDays: 10,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O43 — งานแบบเรียบง่าย เวอร์ชันเดียวผ่านทันที ----
  job({
    id: "dsj-33",
    order_id: "ord-33",
    job_no: "DSN-0093",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายการ์ตูนแมว",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-33-1",
    due_at: daysAgo(3),
    started_at: daysAgo(4),
    approved_at: daysAgo(3),
    ageDays: 5,
  }),
  job({
    id: "dsj-34",
    order_id: "ord-34",
    job_no: "DSN-0094",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายรถไฟ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-34-1",
    due_at: daysAgo(4),
    started_at: daysAgo(5),
    approved_at: daysAgo(4),
    ageDays: 6,
  }),
  job({
    id: "dsj-35",
    order_id: "ord-35",
    job_no: "DSN-0095",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายลูกโป่ง",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-35-1",
    due_at: daysAgo(5),
    started_at: daysAgo(6),
    approved_at: daysAgo(5),
    ageDays: 7,
  }),
  job({
    id: "dsj-36",
    order_id: "ord-36",
    job_no: "DSN-0096",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายผีเสื้อ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-36-1",
    due_at: daysAgo(4),
    started_at: daysAgo(5),
    approved_at: daysAgo(4),
    ageDays: 6,
  }),
  job({
    id: "dsj-37",
    order_id: "ord-37",
    job_no: "DSN-0097",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า โลโก้ร้านเบเกอรี่",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-37-1",
    due_at: daysAgo(5),
    started_at: daysAgo(6),
    approved_at: daysAgo(5),
    ageDays: 7,
  }),
  job({
    id: "dsj-38",
    order_id: "ord-38",
    job_no: "DSN-0098",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายดอกซากุระ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-38-1",
    due_at: daysAgo(4),
    started_at: daysAgo(5),
    approved_at: daysAgo(4),
    ageDays: 6,
  }),
  job({
    id: "dsj-39",
    order_id: "ord-39",
    job_no: "DSN-0099",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายดวงจันทร์",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-39-1",
    due_at: daysAgo(3),
    started_at: daysAgo(4),
    approved_at: daysAgo(3),
    ageDays: 5,
  }),
  job({
    id: "dsj-40",
    order_id: "ord-40",
    job_no: "DSN-0100",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายรุ้งกินน้ำ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-40-1",
    due_at: daysAgo(2),
    started_at: daysAgo(3),
    approved_at: daysAgo(2),
    ageDays: 4,
  }),
  job({
    id: "dsj-41",
    order_id: "ord-41",
    job_no: "DSN-0101",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายผึ้งน้อย",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-41-1",
    due_at: daysAgo(1),
    started_at: daysAgo(2),
    approved_at: daysAgo(1),
    ageDays: 3,
  }),
  job({
    id: "dsj-42",
    order_id: "ord-42",
    job_no: "DSN-0102",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-2",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายเรือใบ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-42-1",
    due_at: daysAgo(2),
    started_at: daysAgo(3),
    approved_at: daysAgo(2),
    ageDays: 4,
  }),
  job({
    id: "dsj-43",
    order_id: "ord-43",
    job_no: "DSN-0103",
    design_source: "customer_file",
    status: "approved",
    assigned_designer_id: "stf-design-1",
    brief: "พิมพ์ตามไฟล์ลูกค้า ลายนกพิราบ",
    cf_status: "approved",
    revision_count: 0,
    approved_version_id: "dvr-43-1",
    due_at: daysAgo(1),
    started_at: daysAgo(2),
    approved_at: daysAgo(1),
    ageDays: 3,
  }),
];

function ver(
  v: Omit<MattiiDesignVersion, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiDesignVersion {
  const { ageDays, ...rest } = v;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const designVersions: MattiiDesignVersion[] = [
  ver({
    id: "dvr-07-1",
    design_job_id: "dsj-07",
    version_no: 1,
    file_name: "mattii-cat-orange-v1.png",
    file_url: "/mock/mattii/design/cat-orange-v1.png",
    preview_url: "/mock/mattii/design/preview-cat-orange-v1.jpg",
    file_size_kb: 4200,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "not_sent",
    cf_sent_at: null,
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: "กำลังจัดองค์ประกอบให้พอดีขนาด",
    ageDays: 4,
  }),
  ver({
    id: "dvr-08-1",
    design_job_id: "dsj-08",
    version_no: 1,
    file_name: "mattii-mountain-pastel-v1.png",
    file_url: "/mock/mattii/design/mountain-pastel-v1.png",
    preview_url: "/mock/mattii/design/preview-mountain-v1.jpg",
    file_size_kb: 5100,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "not_sent",
    cf_sent_at: null,
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: null,
    ageDays: 3,
  }),
  ver({
    id: "dvr-09-1",
    design_job_id: "dsj-09",
    version_no: 1,
    file_name: "mattii-massage-logo-v1.png",
    file_url: "/mock/mattii/design/massage-logo-v1.png",
    preview_url: "/mock/mattii/design/preview-massage-v1.jpg",
    file_size_kb: 3600,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "not_sent",
    cf_sent_at: null,
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: null,
    ageDays: 2,
  }),

  ver({
    id: "dvr-10-1",
    design_job_id: "dsj-10",
    version_no: 1,
    file_name: "mattii-cat-orange-v1.png",
    file_url: "/mock/mattii/design/cat-orange-v1.png",
    preview_url: "/mock/mattii/design/preview-cat-orange-v1.jpg",
    file_size_kb: 4400,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "rejected",
    cf_sent_at: daysAgo(19),
    cf_responded_at: daysAgo(15),
    customer_feedback: "อยากให้พื้นครีมอ่อนกว่านี้อีกหน่อยค่ะ",
    is_print_ready: false,
    note: null,
    ageDays: 19,
  }),
  ver({
    id: "dvr-10-2",
    design_job_id: "dsj-10",
    version_no: 2,
    file_name: "mattii-cat-orange-v2.png",
    file_url: "/mock/mattii/design/cat-orange-v2.png",
    preview_url: "/mock/mattii/design/preview-cat-orange-v2.jpg",
    file_size_kb: 4450,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "sent",
    cf_sent_at: daysAgo(9),
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: "แก้พื้นครีมให้อ่อนลงตามคำขอ — รอลูกค้าตอบ",
    ageDays: 9,
  }),
  ver({
    id: "dvr-11-1",
    design_job_id: "dsj-11",
    version_no: 1,
    file_name: "mattii-owl-cute-v1.png",
    file_url: "/mock/mattii/design/owl-cute-v1.png",
    preview_url: "/mock/mattii/design/preview-owl-v1.jpg",
    file_size_kb: 3900,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "sent",
    cf_sent_at: daysAgo(6),
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: null,
    ageDays: 6,
  }),
  ver({
    id: "dvr-12-1",
    design_job_id: "dsj-12",
    version_no: 1,
    file_name: "mattii-flower-pastel-v1.png",
    file_url: "/mock/mattii/design/flower-pastel-v1.png",
    preview_url: "/mock/mattii/design/preview-flower-v1.jpg",
    file_size_kb: 3200,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "sent",
    cf_sent_at: daysAgo(1),
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 1,
  }),

  ver({
    id: "dvr-13-1",
    design_job_id: "dsj-13",
    version_no: 1,
    file_name: "mattii-puppy-v1.png",
    file_url: "/mock/mattii/design/puppy-v1.png",
    preview_url: "/mock/mattii/design/preview-puppy-v1.jpg",
    file_size_kb: 4100,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(2),
    cf_responded_at: daysAgo(1),
    customer_feedback: "สวยมากค่ะ ชอบ! ใช้อันนี้เลย",
    is_print_ready: true,
    note: null,
    ageDays: 2,
  }),
  ver({
    id: "dvr-14-1",
    design_job_id: "dsj-14",
    version_no: 1,
    file_name: "mattii-galaxy-v1.png",
    file_url: "/mock/mattii/design/galaxy-v1.png",
    preview_url: "/mock/mattii/design/preview-galaxy-v1.jpg",
    file_size_kb: 6200,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(2),
    cf_responded_at: daysAgo(1),
    customer_feedback: "ใช่เลยค่ะ อนุมัติ!",
    is_print_ready: true,
    note: null,
    ageDays: 2,
  }),

  ver({
    id: "dvr-15-1",
    design_job_id: "dsj-15",
    version_no: 1,
    file_name: "mattii-cat-orange-v1.png",
    file_url: "/mock/mattii/design/cat-orange-v1.png",
    preview_url: "/mock/mattii/design/preview-cat-orange-v1.jpg",
    file_size_kb: 4300,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(4),
    cf_responded_at: daysAgo(3),
    customer_feedback: "โอเคค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 12,
  }),
  ver({
    id: "dvr-16-1",
    design_job_id: "dsj-16",
    version_no: 1,
    file_name: "mattii-forest-green-v1.png",
    file_url: "/mock/mattii/design/forest-green-v1.png",
    preview_url: "/mock/mattii/design/preview-forest-v1.jpg",
    file_size_kb: 5500,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(7),
    cf_responded_at: daysAgo(6),
    customer_feedback: "ได้เลยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 13,
  }),
  ver({
    id: "dvr-17-1",
    design_job_id: "dsj-17",
    version_no: 1,
    file_name: "mattii-bday-message-v1.png",
    file_url: "/mock/mattii/design/bday-message-v1.png",
    preview_url: "/mock/mattii/design/preview-bday-v1.jpg",
    file_size_kb: 2900,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(2),
    cf_responded_at: daysAgo(1),
    customer_feedback: "สวยค่ะ ใช้เลย",
    is_print_ready: true,
    note: null,
    ageDays: 4,
  }),

  ver({
    id: "dvr-18-1",
    design_job_id: "dsj-18",
    version_no: 1,
    file_name: "mattii-butterfly-v1.png",
    file_url: "/mock/mattii/design/butterfly-v1.png",
    preview_url: "/mock/mattii/design/preview-butterfly-v1.jpg",
    file_size_kb: 4700,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(3),
    cf_responded_at: daysAgo(2),
    customer_feedback: "ok ค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 8,
  }),
  ver({
    id: "dvr-19-1",
    design_job_id: "dsj-19",
    version_no: 1,
    file_name: "mattii-race-car-v1.png",
    file_url: "/mock/mattii/design/race-car-v1.png",
    preview_url: "/mock/mattii/design/preview-race-v1.jpg",
    file_size_kb: 3300,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(3),
    cf_responded_at: daysAgo(2),
    customer_feedback: "เยี่ยมเลยครับ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 6,
  }),

  ver({
    id: "dvr-20-1",
    design_job_id: "dsj-20",
    version_no: 1,
    file_name: "mattii-pet-name-mamuang-v1.png",
    file_url: "/mock/mattii/design/pet-mamuang-v1.png",
    preview_url: "/mock/mattii/design/preview-mamuang-v1.jpg",
    file_size_kb: 3100,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(4),
    cf_responded_at: daysAgo(3),
    customer_feedback: "น่ารักมากค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 8,
  }),
  ver({
    id: "dvr-21-1",
    design_job_id: "dsj-21",
    version_no: 1,
    file_name: "mattii-restaurant-logo-v1.png",
    file_url: "/mock/mattii/design/restaurant-logo-v1.png",
    preview_url: "/mock/mattii/design/preview-restaurant-v1.jpg",
    file_size_kb: 2800,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(4),
    cf_responded_at: daysAgo(3),
    customer_feedback: "ใช้แบบเดิมได้เลยค่ะ",
    is_print_ready: true,
    note: "ลูกค้าประจำ ใช้ไฟล์เดิม",
    ageDays: 7,
  }),

  ver({
    id: "dvr-22-1",
    design_job_id: "dsj-22",
    version_no: 1,
    file_name: "mattii-cat-cartoon-v1.png",
    file_url: "/mock/mattii/design/cat-cartoon-v1.png",
    preview_url: "/mock/mattii/design/preview-catcartoon-v1.jpg",
    file_size_kb: 3400,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(5),
    cf_responded_at: daysAgo(4),
    customer_feedback: "โอเคเลยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 9,
  }),
  ver({
    id: "dvr-23-1",
    design_job_id: "dsj-23",
    version_no: 1,
    file_name: "mattii-anniversary-v1.png",
    file_url: "/mock/mattii/design/anniversary-v1.png",
    preview_url: "/mock/mattii/design/preview-anniversary-v1.jpg",
    file_size_kb: 2600,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(3),
    cf_responded_at: daysAgo(2),
    customer_feedback: "ใช่เลยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง งานด่วน",
    ageDays: 5,
  }),

  ver({
    id: "dvr-24-1",
    design_job_id: "dsj-24",
    version_no: 1,
    file_name: "mattii-mountain-pastel-v1.png",
    file_url: "/mock/mattii/design/mountain-pastel-v1.png",
    preview_url: "/mock/mattii/design/preview-mountain-v1.jpg",
    file_size_kb: 5300,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(10),
    cf_responded_at: daysAgo(9),
    customer_feedback: "สวยมากค่ะ",
    is_print_ready: true,
    note: null,
    ageDays: 15,
  }),
  ver({
    id: "dvr-25-1",
    design_job_id: "dsj-25",
    version_no: 1,
    file_name: "mattii-street-graffiti-v1.png",
    file_url: "/mock/mattii/design/street-graffiti-v1.png",
    preview_url: "/mock/mattii/design/preview-graffiti-v1.jpg",
    file_size_kb: 6800,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(9),
    cf_responded_at: daysAgo(8),
    customer_feedback: "เจ๋งมากครับ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 14,
  }),
  ver({
    id: "dvr-26-1",
    design_job_id: "dsj-26",
    version_no: 1,
    file_name: "mattii-fruit-colorful-v1.png",
    file_url: "/mock/mattii/design/fruit-colorful-v1.png",
    preview_url: "/mock/mattii/design/preview-fruit-v1.jpg",
    file_size_kb: 4900,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(8),
    cf_responded_at: daysAgo(7),
    customer_feedback: "สดใสน่ารักดีค่ะ",
    is_print_ready: true,
    note: null,
    ageDays: 13,
  }),

  ver({
    id: "dvr-27-1",
    design_job_id: "dsj-27",
    version_no: 1,
    file_name: "mattii-football-team-v1.png",
    file_url: "/mock/mattii/design/football-team-v1.png",
    preview_url: "/mock/mattii/design/preview-football-v1.jpg",
    file_size_kb: 5700,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(7),
    cf_responded_at: daysAgo(6),
    customer_feedback: "เยี่ยมครับ ทีมโปรดผมเลย",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 7,
  }),

  ver({
    id: "dvr-28-1",
    design_job_id: "dsj-28",
    version_no: 1,
    file_name: "mattii-cat-baanmali-v1.png",
    file_url: "/mock/mattii/design/cat-baanmali-v1.png",
    preview_url: "/mock/mattii/design/preview-baanmali-v1.jpg",
    file_size_kb: 4600,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "rejected",
    cf_sent_at: daysAgo(7),
    cf_responded_at: daysAgo(6),
    customer_feedback: "อยากให้สีพื้นอ่อนลงอีกหน่อยค่ะ ให้เข้ากับโลโก้ร้าน",
    is_print_ready: false,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 7,
  }),
  ver({
    id: "dvr-28-2",
    design_job_id: "dsj-28",
    version_no: 2,
    file_name: "mattii-cat-baanmali-v2.png",
    file_url: "/mock/mattii/design/cat-baanmali-v2.png",
    preview_url: "/mock/mattii/design/preview-baanmali-v2.jpg",
    file_size_kb: 4650,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(6),
    cf_responded_at: daysAgo(5),
    customer_feedback: "สวยเลยค่ะ อนุมัติ! เป็นเวอร์ชันที่ใช้พิมพ์",
    is_print_ready: true,
    note: "แก้สีพื้นอ่อนลงตามคำขอ",
    ageDays: 6,
  }),

  ver({
    id: "dvr-29-1",
    design_job_id: "dsj-29",
    version_no: 1,
    file_name: "mattii-peacock-colorful-v1.png",
    file_url: "/mock/mattii/design/peacock-v1.png",
    preview_url: "/mock/mattii/design/preview-peacock-v1.jpg",
    file_size_kb: 3700,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(7),
    cf_responded_at: daysAgo(6),
    customer_feedback: "สวยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 12,
  }),
  ver({
    id: "dvr-30-1",
    design_job_id: "dsj-30",
    version_no: 1,
    file_name: "mattii-galaxy-special-v1.png",
    file_url: "/mock/mattii/design/galaxy-special-v1.png",
    preview_url: "/mock/mattii/design/preview-galaxyspecial-v1.jpg",
    file_size_kb: 7200,
    dpi: 300,
    uploaded_by_id: "stf-design-2",
    uploaded_by_role: "designer",
    cf_status: "approved",
    cf_sent_at: daysAgo(8),
    cf_responded_at: daysAgo(7),
    customer_feedback: "ใช่เลยค่ะ",
    is_print_ready: true,
    note: null,
    ageDays: 11,
  }),

  ver({
    id: "dvr-32-1",
    design_job_id: "dsj-32",
    version_no: 1,
    file_name: "mattii-cat-waitcolor-v1.png",
    file_url: "/mock/mattii/design/cat-waitcolor-v1.png",
    preview_url: "/mock/mattii/design/preview-waitcolor-v1.jpg",
    file_size_kb: 3000,
    dpi: 300,
    uploaded_by_id: "stf-design-1",
    uploaded_by_role: "designer",
    cf_status: "not_sent",
    cf_sent_at: null,
    cf_responded_at: null,
    customer_feedback: null,
    is_print_ready: false,
    note: "งานพักไว้ รอลูกค้าตัดสินใจโทนสี",
    ageDays: 9,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O43 ----
  ver({
    id: "dvr-33-1",
    design_job_id: "dsj-33",
    version_no: 1,
    file_name: "mattii-cat-cartoon2-v1.png",
    file_url: "/mock/mattii/design/cat-cartoon2-v1.png",
    preview_url: "/mock/mattii/design/preview-cat2-v1.jpg",
    file_size_kb: 3100,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(4),
    cf_responded_at: daysAgo(3),
    customer_feedback: "โอเคค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 4,
  }),
  ver({
    id: "dvr-34-1",
    design_job_id: "dsj-34",
    version_no: 1,
    file_name: "mattii-train-v1.png",
    file_url: "/mock/mattii/design/train-v1.png",
    preview_url: "/mock/mattii/design/preview-train-v1.jpg",
    file_size_kb: 2900,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(5),
    cf_responded_at: daysAgo(4),
    customer_feedback: "น่ารักดีครับ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 5,
  }),
  ver({
    id: "dvr-35-1",
    design_job_id: "dsj-35",
    version_no: 1,
    file_name: "mattii-balloon-v1.png",
    file_url: "/mock/mattii/design/balloon-v1.png",
    preview_url: "/mock/mattii/design/preview-balloon-v1.jpg",
    file_size_kb: 2700,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(6),
    cf_responded_at: daysAgo(5),
    customer_feedback: "สวยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 6,
  }),
  ver({
    id: "dvr-36-1",
    design_job_id: "dsj-36",
    version_no: 1,
    file_name: "mattii-butterfly2-v1.png",
    file_url: "/mock/mattii/design/butterfly2-v1.png",
    preview_url: "/mock/mattii/design/preview-butterfly2-v1.jpg",
    file_size_kb: 3300,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(5),
    cf_responded_at: daysAgo(4),
    customer_feedback: "ชอบมากค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 5,
  }),
  ver({
    id: "dvr-37-1",
    design_job_id: "dsj-37",
    version_no: 1,
    file_name: "mattii-bakery-logo-v1.png",
    file_url: "/mock/mattii/design/bakery-logo-v1.png",
    preview_url: "/mock/mattii/design/preview-bakery-v1.jpg",
    file_size_kb: 2600,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(6),
    cf_responded_at: daysAgo(5),
    customer_feedback: "ใช้แบบนี้เลยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 6,
  }),
  ver({
    id: "dvr-38-1",
    design_job_id: "dsj-38",
    version_no: 1,
    file_name: "mattii-sakura-v1.png",
    file_url: "/mock/mattii/design/sakura-v1.png",
    preview_url: "/mock/mattii/design/preview-sakura-v1.jpg",
    file_size_kb: 3400,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(5),
    cf_responded_at: daysAgo(4),
    customer_feedback: "สวยมากค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 5,
  }),
  ver({
    id: "dvr-39-1",
    design_job_id: "dsj-39",
    version_no: 1,
    file_name: "mattii-moon-v1.png",
    file_url: "/mock/mattii/design/moon-v1.png",
    preview_url: "/mock/mattii/design/preview-moon-v1.jpg",
    file_size_kb: 3000,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(4),
    cf_responded_at: daysAgo(3),
    customer_feedback: "ใช่เลยค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 4,
  }),
  ver({
    id: "dvr-40-1",
    design_job_id: "dsj-40",
    version_no: 1,
    file_name: "mattii-rainbow-v1.png",
    file_url: "/mock/mattii/design/rainbow-v1.png",
    preview_url: "/mock/mattii/design/preview-rainbow-v1.jpg",
    file_size_kb: 3200,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(3),
    cf_responded_at: daysAgo(2),
    customer_feedback: "สดใสดีค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 3,
  }),
  ver({
    id: "dvr-41-1",
    design_job_id: "dsj-41",
    version_no: 1,
    file_name: "mattii-bee-v1.png",
    file_url: "/mock/mattii/design/bee-v1.png",
    preview_url: "/mock/mattii/design/preview-bee-v1.jpg",
    file_size_kb: 2500,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(2),
    cf_responded_at: daysAgo(1),
    customer_feedback: "น่ารักค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 2,
  }),
  ver({
    id: "dvr-42-1",
    design_job_id: "dsj-42",
    version_no: 1,
    file_name: "mattii-sailboat-v1.png",
    file_url: "/mock/mattii/design/sailboat-v1.png",
    preview_url: "/mock/mattii/design/preview-sailboat-v1.jpg",
    file_size_kb: 2800,
    dpi: 300,
    uploaded_by_id: "stf-sale-2",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(3),
    cf_responded_at: daysAgo(2),
    customer_feedback: "ชอบครับ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 3,
  }),
  ver({
    id: "dvr-43-1",
    design_job_id: "dsj-43",
    version_no: 1,
    file_name: "mattii-pigeon-v1.png",
    file_url: "/mock/mattii/design/pigeon-v1.png",
    preview_url: "/mock/mattii/design/preview-pigeon-v1.jpg",
    file_size_kb: 2700,
    dpi: 300,
    uploaded_by_id: "stf-sale-1",
    uploaded_by_role: "sale",
    cf_status: "approved",
    cf_sent_at: daysAgo(2),
    cf_responded_at: daysAgo(1),
    customer_feedback: "โอเคค่ะ",
    is_print_ready: true,
    note: "ไฟล์ลูกค้าส่งเอง",
    ageDays: 2,
  }),
];
