// integrations.ts — การเชื่อมต่อ ZAAPI / Shipnity / J&T / LINE (1 ตัวจำลอง error ตามที่ spec ต้องการ)
import type { MattiiIntegration } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

export const integrations: MattiiIntegration[] = [
  {
    id: "itg-zaapi",
    org_id: MOCK_ORG_ID,
    kind: "zaapi",
    display_name: "ZAAPI — แชทรวม 3 ช่องทาง",
    status: "connected",
    account_label: "Mattii Official",
    connected_channels: ["facebook", "line", "tiktok"],
    last_sync_at: daysAgo(0, 8, 0),
    last_error: null,
    sync_count_today: 18,
    config: {
      webhook_url: "https://app.perpos.ai/api/mattii-ops/zaapi/webhook",
      auto_reply: false,
    },
    created_at: daysAgo(200),
    updated_at: daysAgo(0),
  },
  {
    id: "itg-shipnity",
    org_id: MOCK_ORG_ID,
    kind: "shipnity",
    display_name: "Shipnity — จัดการขนส่งหลายเจ้า",
    status: "error",
    account_label: "Mattii Shop",
    connected_channels: [],
    last_sync_at: daysAgo(2, 9, 0),
    last_error: "หมดอายุ token การเชื่อมต่อ — กรุณาเชื่อมต่อใหม่",
    sync_count_today: 0,
    config: { default_carrier: "jt", auto_sync_tracking: true },
    created_at: daysAgo(200),
    updated_at: daysAgo(2),
  },
  {
    id: "itg-jt",
    org_id: MOCK_ORG_ID,
    kind: "jt",
    display_name: "J&T Express",
    status: "connected",
    account_label: "Mattii Rug Shop (JT-88213)",
    connected_channels: [],
    last_sync_at: daysAgo(0, 10, 0),
    last_error: null,
    sync_count_today: 6,
    config: { pickup_point: "สาขาบางบัวทอง" },
    created_at: daysAgo(200),
    updated_at: daysAgo(0),
  },
  {
    id: "itg-line",
    org_id: MOCK_ORG_ID,
    kind: "line_notify",
    display_name: "แจ้งเตือน LINE (ทีมงาน)",
    status: "connected",
    account_label: "Mattii Ops Bot",
    connected_channels: [],
    last_sync_at: daysAgo(0, 7, 0),
    last_error: null,
    sync_count_today: 24,
    config: {
      events: {
        new_order_from_chat: true,
        cf_approved: true,
        cf_revision_requested: true,
        qc_failed: true,
        order_at_risk_overdue: true,
        awaiting_cf_stale: true,
        material_low_stock: true,
      },
      recipients: {
        owner: ["stf-owner"],
        sale: ["stf-sale-1", "stf-sale-2"],
        production: ["stf-prod-1"],
      },
    },
    created_at: daysAgo(200),
    updated_at: daysAgo(0),
  },
];
