// materials.ts — วัสดุ 9 รายการ (2 รายการต่ำกว่า reorder_point เพื่อโชว์แถบเตือน)
import type { MattiiMaterial } from "./types";
import { MOCK_ORG_ID, daysAgo, money } from "./helpers";

function withValue(
  m: Omit<MattiiMaterial, "stock_value" | "org_id" | "created_at" | "updated_at">,
): MattiiMaterial {
  return {
    ...m,
    org_id: MOCK_ORG_ID,
    stock_value: money(m.qty_on_hand * m.unit_cost),
    created_at: daysAgo(200),
    updated_at: daysAgo(0),
  };
}

export const materials: MattiiMaterial[] = [
  withValue({
    id: "mat-01",
    code: "MAT-FAB-01",
    name: "ผ้าพรมกำมะหยี่ หน้ากว้าง 1.6 ม.",
    category: "rug_fabric",
    unit: "sqm",
    qty_on_hand: 45.5,
    reorder_point: 60,
    unit_cost: 180,
    supplier_name: "หจก. ผ้าไทยเท็กซ์ไทล์",
    location: "ชั้น A-1",
    is_active: true,
    note: "ต่ำกว่าจุดสั่งซื้อ — ควรสั่งเพิ่มด่วน (ใช้กับพรมเช็ดเท้า/ห้องนั่งเล่นแทบทุกออเดอร์)",
  }),
  withValue({
    id: "mat-02",
    code: "MAT-FAB-02",
    name: "ผ้าไมโครไฟเบอร์ หน้ากว้าง 1.5 ม.",
    category: "rug_fabric",
    unit: "sqm",
    qty_on_hand: 120,
    reorder_point: 50,
    unit_cost: 95,
    supplier_name: "บจก. ฟิลาเท็กซ์",
    location: "ชั้น A-2",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-03",
    code: "MAT-BAK-01",
    name: "ยางรองหลังกันลื่น PVC",
    category: "backing",
    unit: "sqm",
    qty_on_hand: 80,
    reorder_point: 40,
    unit_cost: 65,
    supplier_name: "หจก. ยางไทยรับเบอร์",
    location: "ชั้น B-1",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-04",
    code: "MAT-INK-01",
    name: "หมึกซับลิเมชัน CMYK (ชุด 4 สี)",
    category: "ink",
    unit: "liter",
    qty_on_hand: 8.5,
    reorder_point: 15,
    unit_cost: 950,
    supplier_name: "บจก. อิงค์เจ็ทซัพพลาย",
    location: "ตู้เก็บหมึก",
    is_active: true,
    note: "ต่ำกว่าจุดสั่งซื้อ — เสี่ยงหมดกลางสายพิมพ์",
  }),
  withValue({
    id: "mat-05",
    code: "MAT-FIL-01",
    name: "กระดาษ/ฟิล์มทรานสเฟอร์ซับลิเมชัน",
    category: "film",
    unit: "roll",
    qty_on_hand: 22,
    reorder_point: 10,
    unit_cost: 420,
    supplier_name: "บจก. อิงค์เจ็ทซัพพลาย",
    location: "ชั้น A-3",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-06",
    code: "MAT-THR-01",
    name: "ด้ายเย็บโพ้งขอบพรม (โพลีเอสเตอร์)",
    category: "other",
    unit: "roll",
    qty_on_hand: 35,
    reorder_point: 15,
    unit_cost: 45,
    supplier_name: "ร้านด้ายเจริญกิจ",
    location: "ชั้น B-2",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-07",
    code: "MAT-PKG-01",
    name: "กล่องพัสดุลูกฟูก เบอร์ 2",
    category: "packaging",
    unit: "piece",
    qty_on_hand: 340,
    reorder_point: 100,
    unit_cost: 12,
    supplier_name: "บจก. กล่องไทยแพ็ค",
    location: "โกดังหลังร้าน",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-08",
    code: "MAT-PKG-02",
    name: "ถุงซิปกันน้ำ OPP",
    category: "packaging",
    unit: "piece",
    qty_on_hand: 510,
    reorder_point: 150,
    unit_cost: 4.5,
    supplier_name: "บจก. กล่องไทยแพ็ค",
    location: "โกดังหลังร้าน",
    is_active: true,
    note: null,
  }),
  withValue({
    id: "mat-09",
    code: "MAT-PKG-03",
    name: "เทปกาวพิมพ์โลโก้ร้าน",
    category: "packaging",
    unit: "roll",
    qty_on_hand: 18,
    reorder_point: 10,
    unit_cost: 55,
    supplier_name: "ร้านบรรจุภัณฑ์ครบวงจร",
    location: "โกดังหลังร้าน",
    is_active: true,
    note: null,
  }),
];
