// order-items.ts — รายการพรมต่อออเดอร์ (1 รายการ/ออเดอร์ในชุดสาธิตนี้ — line_total ตรงกับ orders.subtotal เป๊ะ)
import type { MattiiOrderItem } from "./types";
import { MOCK_ORG_ID, daysAgo, money, fabricUsage } from "./helpers";

function item(
  it: Omit<MattiiOrderItem, "org_id" | "line_total" | "created_at" | "updated_at"> & {
    createdDaysAgo: number;
  },
): MattiiOrderItem {
  const { createdDaysAgo, ...rest } = it;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    line_total: money(rest.qty * rest.unit_price),
    created_at: daysAgo(createdDaysAgo),
    updated_at: daysAgo(Math.min(createdDaysAgo, 1)),
  };
}

export const orderItems: MattiiOrderItem[] = [
  item({
    id: "itm-01",
    order_id: "ord-01",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายแมวส้มพื้นครีม",
    qty: 1,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 1,
  }),
  item({
    id: "itm-02",
    order_id: "ord-02",
    line_no: 1,
    product_id: "prd-03",
    product_size_id: "sz-03-2",
    item_name: "พรมห้องนั่งเล่นขนสั้น",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    fabric_type: "ผ้าลูปไพล์",
    edge_finish: "overlock",
    pattern_name: "ลายดอกไม้พาสเทล",
    qty: 1,
    unit_price: 990,
    unit_cost: 430,
    fabric_usage_sqm: 1.104,
    options: { edge_color: "ครีม" },
    spec_note: null,
    createdDaysAgo: 0,
  }),
  item({
    id: "itm-03",
    order_id: "ord-03",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-2",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายการ์ตูนหมี",
    qty: 2,
    unit_price: 450,
    unit_cost: 195,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "น้ำตาล" },
    spec_note: "สั่ง 2 ผืนพร้อมกัน ต่อราคาแล้ว",
    createdDaysAgo: 3,
  }),
  item({
    id: "itm-04",
    order_id: "ord-04",
    line_no: 1,
    product_id: "prd-05",
    product_size_id: "sz-05-2",
    item_name: "แผ่นรองจานพิมพ์ลาย",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์เคลือบกันน้ำ",
    edge_finish: "raw",
    pattern_name: "โลโก้ร้านกาแฟ",
    qty: 4,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: {},
    spec_note: "ชุด 4 ผืน ใช้โลโก้เดียวกัน",
    createdDaysAgo: 2,
  }),
  item({
    id: "itm-05",
    order_id: "ord-05",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-2",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ชื่อบ้าน 'บ้านมะลิ'",
    qty: 2,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { edge_color: "เทา", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 5,
  }),
  item({
    id: "itm-06",
    order_id: "ord-06",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-1",
    item_name: "พรมข้างเตียง",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายการ์ตูนไดโนเสาร์",
    qty: 2,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 4,
  }),
  item({
    id: "itm-07",
    order_id: "ord-07",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-1",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายแมวส้มพื้นครีม",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-08",
    order_id: "ord-08",
    line_no: 1,
    product_id: "prd-03",
    product_size_id: "sz-03-1",
    item_name: "พรมห้องนั่งเล่นขนสั้น",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "ผ้าลูปไพล์",
    edge_finish: "overlock",
    pattern_name: "ลายภูเขาสีพาสเทล",
    qty: 1,
    unit_price: 690,
    unit_cost: 300,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "เทา" },
    spec_note: "ลูกค้า VIP งานละเอียดสูง",
    createdDaysAgo: 5,
  }),
  item({
    id: "itm-09",
    order_id: "ord-09",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-3",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "โลโก้ร้านนวด",
    qty: 1,
    unit_price: 750,
    unit_cost: 325,
    fabric_usage_sqm: 1.104,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 4,
  }),
  item({
    id: "itm-10",
    order_id: "ord-10",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายแมวส้มพื้นครีม (v2 รอ CF)",
    qty: 2,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: "รอ CF มานาน 9 วัน",
    createdDaysAgo: 20,
  }),
  item({
    id: "itm-11",
    order_id: "ord-11",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-2",
    item_name: "พรมข้างเตียง",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายนกฮูกน่ารัก",
    qty: 1,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 8,
  }),
  item({
    id: "itm-12",
    order_id: "ord-12",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-1",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายดอกไม้พาสเทล",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ครีม" },
    spec_note: null,
    createdDaysAgo: 3,
  }),
  item({
    id: "itm-13",
    order_id: "ord-13",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-1",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายลูกสุนัข",
    qty: 3,
    unit_price: 250,
    unit_cost: 108,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: "ชุด 3 ผืน ลายเดียวกัน",
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-14",
    order_id: "ord-14",
    line_no: 1,
    product_id: "prd-06",
    product_size_id: "sz-06-1",
    item_name: "พรมสั่งตัดพิเศษ",
    size_label: "สั่งตัดพิเศษ 120 × 180 ซม.",
    width_cm: 120,
    length_cm: 180,
    fabric_type: "ตามสั่ง (เลือกได้)",
    edge_finish: "overlock",
    pattern_name: "ลายจักรวาลกาแล็กซี่",
    qty: 1,
    unit_price: 1920,
    unit_cost: 864,
    fabric_usage_sqm: fabricUsage(120, 180),
    options: { edge_color: "ดำ" },
    spec_note: "คำนวณจาก price_per_sqm 890 × 2.16 ตร.ม.",
    createdDaysAgo: 8,
  }),
  item({
    id: "itm-15",
    order_id: "ord-15",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายแมวส้มพื้นครีม",
    qty: 2,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 13,
  }),
  item({
    id: "itm-16",
    order_id: "ord-16",
    line_no: 1,
    product_id: "prd-03",
    product_size_id: "sz-03-2",
    item_name: "พรมห้องนั่งเล่นขนสั้น",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    fabric_type: "ผ้าลูปไพล์",
    edge_finish: "overlock",
    pattern_name: "ลายป่าเขียวชะอุ่ม",
    qty: 1,
    unit_price: 990,
    unit_cost: 430,
    fabric_usage_sqm: 1.104,
    options: { edge_color: "เทา" },
    spec_note: "งานด่วน เลยกำหนดส่งแล้ว — พิมพ์ซ้ำรอบ 2",
    createdDaysAgo: 14,
  }),
  item({
    id: "itm-17",
    order_id: "ord-17",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-2",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายคำอวยพรวันเกิด",
    qty: 1,
    unit_price: 450,
    unit_cost: 195,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "น้ำตาล" },
    spec_note: "งานด่วน",
    createdDaysAgo: 5,
  }),
  item({
    id: "itm-18",
    order_id: "ord-18",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-2",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายผีเสื้อสีสัน",
    qty: 2,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { edge_color: "เทา", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 9,
  }),
  item({
    id: "itm-19",
    order_id: "ord-19",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-1",
    item_name: "พรมข้างเตียง",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายรถแข่ง",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 7,
  }),
  item({
    id: "itm-20",
    order_id: "ord-20",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายชื่อสัตว์เลี้ยง 'มะม่วง'",
    qty: 1,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 9,
  }),
  item({
    id: "itm-21",
    order_id: "ord-21",
    line_no: 1,
    product_id: "prd-05",
    product_size_id: "sz-05-1",
    item_name: "แผ่นรองจานพิมพ์ลาย",
    size_label: "30 × 45 ซม.",
    width_cm: 30,
    length_cm: 45,
    fabric_type: "ไมโครไฟเบอร์เคลือบกันน้ำ",
    edge_finish: "raw",
    pattern_name: "โลโก้ร้านอาหาร",
    qty: 6,
    unit_price: 190,
    unit_cost: 82,
    fabric_usage_sqm: 0.155,
    options: {},
    spec_note: "สั่งซ้ำรอบ 2 (ลูกค้าประจำ)",
    createdDaysAgo: 8,
  }),
  item({
    id: "itm-22",
    order_id: "ord-22",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-1",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายการ์ตูนแมวเหมียว",
    qty: 2,
    unit_price: 250,
    unit_cost: 108,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 10,
  }),
  item({
    id: "itm-23",
    order_id: "ord-23",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-1",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายวันเกิดครบรอบ",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ครีม" },
    spec_note: "งานด่วน ครบกำหนดวันนี้",
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-24",
    order_id: "ord-24",
    line_no: 1,
    product_id: "prd-03",
    product_size_id: "sz-03-1",
    item_name: "พรมห้องนั่งเล่นขนสั้น",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "ผ้าลูปไพล์",
    edge_finish: "overlock",
    pattern_name: "ลายภูเขาสีพาสเทล",
    qty: 1,
    unit_price: 690,
    unit_cost: 300,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "เทา" },
    spec_note: null,
    createdDaysAgo: 16,
  }),
  item({
    id: "itm-25",
    order_id: "ord-25",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-3",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายกราฟฟิตี้สตรีท",
    qty: 1,
    unit_price: 750,
    unit_cost: 325,
    fabric_usage_sqm: 1.104,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 15,
  }),
  item({
    id: "itm-26",
    order_id: "ord-26",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-2",
    item_name: "พรมข้างเตียง",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายผลไม้สีสด",
    qty: 2,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 14,
  }),
  item({
    id: "itm-27",
    order_id: "ord-27",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายทีมฟุตบอลที่ชอบ",
    qty: 3,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ดำ", anti_slip: "มี" },
    spec_note: "ออเดอร์ใหญ่ 3 ผืน",
    createdDaysAgo: 20,
  }),
  item({
    id: "itm-28",
    order_id: "ord-28",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายแมวส้มพื้นครีม โลโก้ร้านกาแฟ",
    qty: 2,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ครีม", anti_slip: "มี" },
    spec_note: "Demo เต็มเส้น — ดู Review note ใน orders.ts",
    createdDaysAgo: 16,
  }),
  item({
    id: "itm-29",
    order_id: "ord-29",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-1",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายนกยูงหลากสี",
    qty: 1,
    unit_price: 250,
    unit_cost: 108,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 12,
  }),
  item({
    id: "itm-30",
    order_id: "ord-30",
    line_no: 1,
    product_id: "prd-03",
    product_size_id: "sz-03-3",
    item_name: "พรมห้องนั่งเล่นขนสั้น",
    size_label: "100 × 150 ซม.",
    width_cm: 100,
    length_cm: 150,
    fabric_type: "ผ้าลูปไพล์",
    edge_finish: "overlock",
    pattern_name: "ลายจักรวาลกาแล็กซี่พิเศษ",
    qty: 1,
    unit_price: 1490,
    unit_cost: 650,
    fabric_usage_sqm: 1.725,
    options: { edge_color: "ดำ" },
    spec_note: "พิมพ์ซ้ำ 2 รอบ — ดู order_costs",
    createdDaysAgo: 22,
  }),
  item({
    id: "itm-31",
    order_id: "ord-31",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-1",
    item_name: "พรมข้างเตียง",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายลูกแมวส้มน้อย",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { anti_slip: "มี" },
    spec_note: "ยกเลิกออเดอร์แล้ว",
    createdDaysAgo: 10,
  }),
  item({
    id: "itm-32",
    order_id: "ord-32",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายรอลูกค้าตัดสินใจสี",
    qty: 1,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "เทา", anti_slip: "มี" },
    spec_note: "พักออเดอร์ไว้",
    createdDaysAgo: 11,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O43 ----
  item({
    id: "itm-33",
    order_id: "ord-33",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-1",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายการ์ตูนแมว",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 5,
  }),
  item({
    id: "itm-34",
    order_id: "ord-34",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-1",
    item_name: "พรมข้างเตียง",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายรถไฟ",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-35",
    order_id: "ord-35",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-1",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายลูกโป่ง",
    qty: 1,
    unit_price: 250,
    unit_cost: 108,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 7,
  }),
  item({
    id: "itm-36",
    order_id: "ord-36",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-2",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายผีเสื้อ",
    qty: 1,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { edge_color: "เทา" },
    spec_note: null,
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-37",
    order_id: "ord-37",
    line_no: 1,
    product_id: "prd-05",
    product_size_id: "sz-05-2",
    item_name: "แผ่นรองจานพิมพ์ลาย",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์เคลือบกันน้ำ",
    edge_finish: "raw",
    pattern_name: "โลโก้ร้านเบเกอรี่",
    qty: 2,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: {},
    spec_note: "ชุด 2 ผืน",
    createdDaysAgo: 7,
  }),
  item({
    id: "itm-38",
    order_id: "ord-38",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-2",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายดอกซากุระ",
    qty: 1,
    unit_price: 450,
    unit_cost: 195,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "น้ำตาล" },
    spec_note: null,
    createdDaysAgo: 6,
  }),
  item({
    id: "itm-39",
    order_id: "ord-39",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-3",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายดวงจันทร์",
    qty: 1,
    unit_price: 490,
    unit_cost: 210,
    fabric_usage_sqm: 0.621,
    options: { edge_color: "ดำ", anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 5,
  }),
  item({
    id: "itm-40",
    order_id: "ord-40",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-2",
    item_name: "พรมข้างเตียง",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายรุ้งกินน้ำ",
    qty: 1,
    unit_price: 390,
    unit_cost: 168,
    fabric_usage_sqm: 0.46,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 4,
  }),
  item({
    id: "itm-41",
    order_id: "ord-41",
    line_no: 1,
    product_id: "prd-02",
    product_size_id: "sz-02-1",
    item_name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายผึ้งน้อย",
    qty: 1,
    unit_price: 250,
    unit_cost: 108,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 3,
  }),
  item({
    id: "itm-42",
    order_id: "ord-42",
    line_no: 1,
    product_id: "prd-01",
    product_size_id: "sz-01-1",
    item_name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "กำมะหยี่ (velvet)",
    edge_finish: "overlock",
    pattern_name: "ลายเรือใบ",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { edge_color: "ดำ" },
    spec_note: null,
    createdDaysAgo: 4,
  }),
  item({
    id: "itm-43",
    order_id: "ord-43",
    line_no: 1,
    product_id: "prd-04",
    product_size_id: "sz-04-1",
    item_name: "พรมข้างเตียง",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    fabric_type: "ไมโครไฟเบอร์",
    edge_finish: "binding",
    pattern_name: "ลายนกพิราบ",
    qty: 1,
    unit_price: 290,
    unit_cost: 125,
    fabric_usage_sqm: 0.276,
    options: { anti_slip: "มี" },
    spec_note: null,
    createdDaysAgo: 3,
  }),
];
