// order-costs.ts — ต้นทุนต่อออเดอร์ (owner-only) เฉพาะออเดอร์ที่เข้าสู่ขั้นผลิตแล้ว (>= printing)
// SUM(amount) ต่อ order_id ต้องเท่ากับ orders.total_cost เป๊ะ (เทียบใน orders.ts)
import type { MattiiOrderCost } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function cost(
  c: Omit<MattiiOrderCost, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiOrderCost {
  const { ageDays, ...rest } = c;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(ageDays),
  };
}

export const orderCosts: MattiiOrderCost[] = [
  // ord-15 (printing, ยังไม่จ่ายเงิน) — total 590
  cost({
    id: "cost-15-1",
    order_id: "ord-15",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก+ฟิล์ม (2 ผืน)",
    amount: 420,
    source: "auto_stock",
    stock_movement_id: "mov-11",
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-15-2",
    order_id: "ord-15",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ 2 ผืน",
    amount: 100,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-15-3",
    order_id: "ord-15",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 70,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-16 (reprint, เลยกำหนด) — total 1100
  cost({
    id: "cost-16-1",
    order_id: "ord-16",
    cost_category: "material",
    label: "ตัดผ้า+หมึก รอบแรก (เสียจาก QC fail)",
    amount: 430,
    source: "auto_stock",
    stock_movement_id: "mov-12",
    note: "รอบแรกสีเพี้ยน กลายเป็นของเสีย",
    ageDays: 5,
  }),
  cost({
    id: "cost-16-2",
    order_id: "ord-16",
    cost_category: "material",
    label: "ตัดผ้า+หมึก รอบพิมพ์ซ้ำ",
    amount: 430,
    source: "auto_stock",
    stock_movement_id: "mov-13",
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-16-3",
    order_id: "ord-16",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์ซ้ำเร่งด่วน",
    amount: 150,
    source: "manual",
    stock_movement_id: null,
    note: "ค่าแรง OT เร่งงานด่วน",
    ageDays: 1,
  }),
  cost({
    id: "cost-16-4",
    order_id: "ord-16",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า 2 รอบ",
    amount: 90,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-17 (rush) — total 345
  cost({
    id: "cost-17-1",
    order_id: "ord-17",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 195,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-17-2",
    order_id: "ord-17",
    cost_category: "labor",
    label: "ค่าแรงงานด่วน",
    amount: 90,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-17-3",
    order_id: "ord-17",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 60,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-18 (qc) — total 521
  cost({
    id: "cost-18-1",
    order_id: "ord-18",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก+ฟิล์ม (2 ผืน)",
    amount: 336,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-18-2",
    order_id: "ord-18",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ",
    amount: 110,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-18-3",
    order_id: "ord-18",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 75,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-19 (qc) — total 225
  cost({
    id: "cost-19-1",
    order_id: "ord-19",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 125,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-19-2",
    order_id: "ord-19",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ",
    amount: 60,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-19-3",
    order_id: "ord-19",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 40,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),

  // ord-20 (packing) — total 350
  cost({
    id: "cost-20-1",
    order_id: "ord-20",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก+ฟิล์ม",
    amount: 210,
    source: "auto_stock",
    stock_movement_id: "mov-14",
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-20-2",
    order_id: "ord-20",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: "mov-15",
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-20-3",
    order_id: "ord-20",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 70,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-20-4",
    order_id: "ord-20",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 50,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-21 (packing) — total 722
  cost({
    id: "cost-21-1",
    order_id: "ord-21",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์เคลือบกันน้ำ+หมึก (6 ผืน)",
    amount: 492,
    source: "auto_stock",
    stock_movement_id: "mov-16",
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-21-2",
    order_id: "ord-21",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค (6 ผืน)",
    amount: 40,
    source: "auto_stock",
    stock_movement_id: "mov-17",
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-21-3",
    order_id: "ord-21",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค 6 ผืน",
    amount: 120,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-21-4",
    order_id: "ord-21",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 70,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-22 (ready_to_ship, COD) — total 396
  cost({
    id: "cost-22-1",
    order_id: "ord-22",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก (2 ผืน)",
    amount: 216,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-22-2",
    order_id: "ord-22",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-22-3",
    order_id: "ord-22",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 70,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-22-4",
    order_id: "ord-22",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 45,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-22-5",
    order_id: "ord-22",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 45,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-23 (ready_to_ship, ครบกำหนดวันนี้) — total 265
  cost({
    id: "cost-23-1",
    order_id: "ord-23",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก",
    amount: 125,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-23-2",
    order_id: "ord-23",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 10,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-23-3",
    order_id: "ord-23",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็คด่วน",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-23-4",
    order_id: "ord-23",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 35,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-23-5",
    order_id: "ord-23",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T ด่วน",
    amount: 40,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),

  // ord-24 (shipped) — total 520
  cost({
    id: "cost-24-1",
    order_id: "ord-24",
    cost_category: "material",
    label: "ตัดผ้าลูปไพล์+หมึก",
    amount: 300,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 4,
  }),
  cost({
    id: "cost-24-2",
    order_id: "ord-24",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-24-3",
    order_id: "ord-24",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 90,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-24-4",
    order_id: "ord-24",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 60,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-24-5",
    order_id: "ord-24",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 50,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-25 (shipped, ค้างชำระ) — total 565
  cost({
    id: "cost-25-1",
    order_id: "ord-25",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 325,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-25-2",
    order_id: "ord-25",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 25,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-25-3",
    order_id: "ord-25",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 95,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-25-4",
    order_id: "ord-25",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 65,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-25-5",
    order_id: "ord-25",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 55,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-26 (shipped, COD ยังไม่เก็บเงิน) — total 591
  cost({
    id: "cost-26-1",
    order_id: "ord-26",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก (2 ผืน)",
    amount: 336,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-26-2",
    order_id: "ord-26",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 30,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-26-3",
    order_id: "ord-26",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 100,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-26-4",
    order_id: "ord-26",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 65,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-26-5",
    order_id: "ord-26",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 60,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  // ord-27 (delivered) — total 940
  cost({
    id: "cost-27-1",
    order_id: "ord-27",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก (3 ผืน)",
    amount: 630,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 8,
  }),
  cost({
    id: "cost-27-2",
    order_id: "ord-27",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค (3 ผืน)",
    amount: 35,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 6,
  }),
  cost({
    id: "cost-27-3",
    order_id: "ord-27",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค 3 ผืน",
    amount: 130,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 6,
  }),
  cost({
    id: "cost-27-4",
    order_id: "ord-27",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 85,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 6,
  }),
  cost({
    id: "cost-27-5",
    order_id: "ord-27",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 60,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 4,
  }),

  // ord-28 (delivered, flagship — reprint + COD) — total 955
  cost({
    id: "cost-28-1",
    order_id: "ord-28",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก รอบแรก+พิมพ์ซ้ำ (สีเพี้ยน 1 ผืน)",
    amount: 630,
    source: "auto_stock",
    stock_movement_id: "mov-21",
    note: "รวม 1 ผืนที่เสียจาก QC fail",
    ageDays: 4,
  }),
  cost({
    id: "cost-28-2",
    order_id: "ord-28",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 30,
    source: "auto_stock",
    stock_movement_id: "mov-22",
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-28-3",
    order_id: "ord-28",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์ซ้ำ+ตัดเย็บ+แพ็ค",
    amount: 150,
    source: "manual",
    stock_movement_id: null,
    note: "รวมค่าแรงพิมพ์ซ้ำ",
    ageDays: 4,
  }),
  cost({
    id: "cost-28-4",
    order_id: "ord-28",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า 2 รอบ",
    amount: 90,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 4,
  }),
  cost({
    id: "cost-28-5",
    order_id: "ord-28",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 55,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),

  // ord-29 (delivered, COD เก็บเงินแล้ว) — total 253
  cost({
    id: "cost-29-1",
    order_id: "ord-29",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 108,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-29-2",
    order_id: "ord-29",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 15,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-29-3",
    order_id: "ord-29",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-29-4",
    order_id: "ord-29",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 35,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-29-5",
    order_id: "ord-29",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 40,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),

  // ord-30 (delivered, กำไรติดลบ — พิมพ์ซ้ำ 2 รอบ) — total 1650
  cost({
    id: "cost-30-1",
    order_id: "ord-30",
    cost_category: "material",
    label: "ตัดผ้าลูปไพล์+หมึก 3 รอบ (เสีย 2 รอบจาก QC fail)",
    amount: 720,
    source: "auto_stock",
    stock_movement_id: "mov-23",
    note: "พิมพ์ซ้ำ 2 รอบ เสียผ้า+หมึกไปมาก",
    ageDays: 6,
  }),
  cost({
    id: "cost-30-2",
    order_id: "ord-30",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์ซ้ำ 2 รอบ + rework",
    amount: 400,
    source: "manual",
    stock_movement_id: null,
    note: "ค่าแรง OT รวมพิมพ์ซ้ำ 2 รอบ",
    ageDays: 6,
  }),
  cost({
    id: "cost-30-3",
    order_id: "ord-30",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า 3 รอบ",
    amount: 250,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 6,
  }),
  cost({
    id: "cost-30-4",
    order_id: "ord-30",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T ด่วน",
    amount: 280,
    source: "auto_shipping",
    stock_movement_id: null,
    note: "ค่าส่งด่วนพิเศษชดเชยความล่าช้า",
    ageDays: 2,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O40, O42 (O41/O43 ยังไม่พิมพ์ → total_cost=0 ไม่มีต้นทุนเกิดขึ้น) ----
  cost({
    id: "cost-33-1",
    order_id: "ord-33",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก",
    amount: 125,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-33-2",
    order_id: "ord-33",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 10,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-33-3",
    order_id: "ord-33",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-33-4",
    order_id: "ord-33",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 35,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-33-5",
    order_id: "ord-33",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 40,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  cost({
    id: "cost-34-1",
    order_id: "ord-34",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 125,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-34-2",
    order_id: "ord-34",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 10,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-34-3",
    order_id: "ord-34",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-34-4",
    order_id: "ord-34",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 35,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-34-5",
    order_id: "ord-34",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 40,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),

  cost({
    id: "cost-35-1",
    order_id: "ord-35",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 108,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-35-2",
    order_id: "ord-35",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 15,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-35-3",
    order_id: "ord-35",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 50,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-35-4",
    order_id: "ord-35",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 30,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-35-5",
    order_id: "ord-35",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 35,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),

  cost({
    id: "cost-36-1",
    order_id: "ord-36",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก",
    amount: 168,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-36-2",
    order_id: "ord-36",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 15,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-36-3",
    order_id: "ord-36",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 60,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-36-4",
    order_id: "ord-36",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 40,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-36-5",
    order_id: "ord-36",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 45,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  cost({
    id: "cost-37-1",
    order_id: "ord-37",
    cost_category: "material",
    label: "ตัดผ้าเคลือบกันน้ำ+หมึก (2 ผืน)",
    amount: 250,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 3,
  }),
  cost({
    id: "cost-37-2",
    order_id: "ord-37",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-37-3",
    order_id: "ord-37",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 90,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-37-4",
    order_id: "ord-37",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-37-5",
    order_id: "ord-37",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 45,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  cost({
    id: "cost-38-1",
    order_id: "ord-38",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 195,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 2,
  }),
  cost({
    id: "cost-38-2",
    order_id: "ord-38",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-38-3",
    order_id: "ord-38",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 65,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-38-4",
    order_id: "ord-38",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 45,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-38-5",
    order_id: "ord-38",
    cost_category: "shipping",
    label: "ค่าขนส่ง J&T",
    amount: 45,
    source: "auto_shipping",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),

  cost({
    id: "cost-39-1",
    order_id: "ord-39",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก",
    amount: 210,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-39-2",
    order_id: "ord-39",
    cost_category: "material",
    label: "กล่อง/ถุงแพ็ค",
    amount: 20,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-39-3",
    order_id: "ord-39",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ+แพ็ค",
    amount: 70,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-39-4",
    order_id: "ord-39",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 50,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),

  cost({
    id: "cost-40-1",
    order_id: "ord-40",
    cost_category: "material",
    label: "ตัดผ้าไมโครไฟเบอร์+หมึก",
    amount: 168,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-40-2",
    order_id: "ord-40",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ",
    amount: 60,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),
  cost({
    id: "cost-40-3",
    order_id: "ord-40",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 40,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 1,
  }),

  cost({
    id: "cost-42-1",
    order_id: "ord-42",
    cost_category: "material",
    label: "ตัดผ้ากำมะหยี่+หมึก",
    amount: 125,
    source: "auto_stock",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-42-2",
    order_id: "ord-42",
    cost_category: "labor",
    label: "ค่าแรงพิมพ์+ตัดเย็บ",
    amount: 55,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
  cost({
    id: "cost-42-3",
    order_id: "ord-42",
    cost_category: "machine",
    label: "ค่าเครื่องพิมพ์ผ้า (ชม.)",
    amount: 35,
    source: "manual",
    stock_movement_id: null,
    note: null,
    ageDays: 0,
  }),
];
