// orders.ts — 32 ออเดอร์ กระจายครบทุกสถานะ state machine + เคสพิเศษ (ดู Review note ท้ายไฟล์)
import type { MattiiOrder } from "./types";
import { MOCK_ORG_ID, daysAgo, dateOnlyFromNow, dateOnlyAgo, money } from "./helpers";

function ord(
  o: Omit<
    MattiiOrder,
    | "org_id"
    | "outstanding_amount"
    | "gross_profit"
    | "margin_percent"
    | "created_at"
    | "updated_at"
  > & { createdDaysAgo: number },
): MattiiOrder {
  const { createdDaysAgo, ...rest } = o;
  const outstanding = money(rest.total_amount - rest.paid_amount);
  const gross_profit = money(rest.total_amount - rest.total_cost);
  const margin_percent =
    rest.total_amount > 0 ? money((gross_profit / rest.total_amount) * 100) : 0;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    outstanding_amount: outstanding,
    gross_profit,
    margin_percent,
    created_at: daysAgo(createdDaysAgo),
    updated_at: daysAgo(Math.min(createdDaysAgo, 1)),
  };
}

export const orders: MattiiOrder[] = [
  // ---- draft (2) ----
  ord({
    id: "ord-01",
    order_no: "MT-2026-0061",
    customer_id: "cus-01",
    conversation_id: "conv-01",
    source_channel: "line",
    status: "draft",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: null,
    promised_ship_date: null,
    subtotal: 490,
    discount_amount: 0,
    shipping_fee: 0,
    rush_fee: 0,
    total_amount: 490,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "รอ Sale ยืนยันราคากับลูกค้า",
    confirmed_at: null,
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 1,
  }),
  ord({
    id: "ord-02",
    order_no: "MT-2026-0062",
    customer_id: "cus-02",
    conversation_id: "conv-02",
    source_channel: "facebook",
    status: "draft",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: null,
    promised_ship_date: null,
    subtotal: 990,
    discount_amount: 0,
    shipping_fee: 0,
    rush_fee: 0,
    total_amount: 990,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: null,
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 0,
  }),

  // ---- quoted (2) ----
  ord({
    id: "ord-03",
    order_no: "MT-2026-0063",
    customer_id: "cus-03",
    conversation_id: "conv-03",
    source_channel: "tiktok",
    status: "quoted",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(10),
    promised_ship_date: null,
    subtotal: 900,
    discount_amount: 50,
    shipping_fee: 0,
    rush_fee: 0,
    total_amount: 850,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ต่อราคาแล้ว รอลูกค้าตอบตกลง",
    confirmed_at: null,
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 3,
  }),
  ord({
    id: "ord-04",
    order_no: "MT-2026-0064",
    customer_id: "cus-04",
    conversation_id: "conv-04",
    source_channel: "line",
    status: "quoted",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(9),
    promised_ship_date: null,
    subtotal: 1160,
    discount_amount: 0,
    shipping_fee: 0,
    rush_fee: 0,
    total_amount: 1160,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: null,
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 2,
  }),

  // ---- confirmed (2) ----
  ord({
    id: "ord-05",
    order_no: "MT-2026-0065",
    customer_id: "cus-05",
    conversation_id: null,
    source_channel: "facebook",
    status: "confirmed",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(8),
    promised_ship_date: dateOnlyFromNow(7),
    subtotal: 780,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 830,
    paid_amount: 300,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "รับมัดจำแล้ว รอส่งเข้าคิวแบบ",
    confirmed_at: daysAgo(4),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 5,
  }),
  ord({
    id: "ord-06",
    order_no: "MT-2026-0066",
    customer_id: "cus-06",
    conversation_id: null,
    source_channel: "line",
    status: "confirmed",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(7),
    promised_ship_date: dateOnlyFromNow(6),
    subtotal: 580,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 630,
    paid_amount: 630,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "จ่ายเต็มแล้ว",
    confirmed_at: daysAgo(3),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 4,
  }),

  // ---- designing (3) ----
  ord({
    id: "ord-07",
    order_no: "MT-2026-0067",
    customer_id: "cus-07",
    conversation_id: null,
    source_channel: "tiktok",
    status: "designing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(6),
    promised_ship_date: dateOnlyFromNow(5),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ยังไม่ได้รับชำระ — ทดสอบว่าไม่บล็อกการเดินงาน",
    confirmed_at: daysAgo(5),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 6,
  }),
  ord({
    id: "ord-08",
    order_no: "MT-2026-0068",
    customer_id: "cus-08",
    conversation_id: null,
    source_channel: "facebook",
    status: "designing",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(7),
    promised_ship_date: dateOnlyFromNow(6),
    subtotal: 690,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 740,
    paid_amount: 300,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ลูกค้า VIP งานละเอียด",
    confirmed_at: daysAgo(4),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 5,
  }),
  ord({
    id: "ord-09",
    order_no: "MT-2026-0069",
    customer_id: "cus-09",
    conversation_id: null,
    source_channel: "line",
    status: "designing",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(5),
    promised_ship_date: dateOnlyFromNow(4),
    subtotal: 750,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 800,
    paid_amount: 400,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(3),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 4,
  }),

  // ---- awaiting_cf (3) — 2 ค้างนาน ----
  ord({
    id: "ord-10",
    order_no: "MT-2026-0070",
    customer_id: "cus-10",
    conversation_id: null,
    source_channel: "facebook",
    status: "awaiting_cf",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 980,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1030,
    paid_amount: 500,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ค้างรอ CF มา 9 วันแล้ว ตามลูกค้าด่วน — ใกล้เลยกำหนดส่ง",
    confirmed_at: daysAgo(18),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 20,
  }),
  ord({
    id: "ord-11",
    order_no: "MT-2026-0071",
    customer_id: "cus-11",
    conversation_id: null,
    source_channel: "line",
    status: "awaiting_cf",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: dateOnlyFromNow(2),
    subtotal: 390,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 440,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ค้างรอ CF มา 6 วันแล้ว",
    confirmed_at: daysAgo(7),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 8,
  }),
  ord({
    id: "ord-12",
    order_no: "MT-2026-0072",
    customer_id: "cus-12",
    conversation_id: null,
    source_channel: "tiktok",
    status: "awaiting_cf",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(8),
    promised_ship_date: dateOnlyFromNow(7),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 200,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(2),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 3,
  }),

  // ---- cf_approved (2) ----
  ord({
    id: "ord-13",
    order_no: "MT-2026-0073",
    customer_id: "cus-13",
    conversation_id: null,
    source_channel: "line",
    status: "cf_approved",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(5),
    promised_ship_date: dateOnlyFromNow(4),
    subtotal: 750,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 800,
    paid_amount: 800,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "รอเข้าคิวเครื่องพิมพ์",
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(1),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 6,
  }),
  ord({
    id: "ord-14",
    order_no: "MT-2026-0074",
    customer_id: "cus-14",
    conversation_id: null,
    source_channel: "facebook",
    status: "cf_approved",
    priority: "rush",
    design_source: "in_house",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(6),
    promised_ship_date: dateOnlyFromNow(5),
    subtotal: 1920,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1970,
    paid_amount: 1000,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "งานสั่งตัดพิเศษ ราคาสูง รอคิวเครื่องด่วน",
    confirmed_at: daysAgo(7),
    cf_approved_at: daysAgo(1),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 8,
  }),

  // ---- printing (3) — O16 = reprint + เลยกำหนด, O17 = ด่วนใกล้กำหนด ----
  ord({
    id: "ord-15",
    order_no: "MT-2026-0075",
    customer_id: "cus-15",
    conversation_id: "conv-05",
    source_channel: "tiktok",
    status: "printing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(4),
    promised_ship_date: dateOnlyFromNow(3),
    subtotal: 980,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1030,
    paid_amount: 0,
    total_cost: 590,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ยังไม่ได้รับชำระ แต่เข้าคิวพิมพ์แล้ว — ทดสอบว่าไม่บล็อก",
    confirmed_at: daysAgo(12),
    cf_approved_at: daysAgo(3),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 13,
  }),
  ord({
    id: "ord-16",
    order_no: "MT-2026-0076",
    customer_id: "cus-16",
    conversation_id: "conv-06",
    source_channel: "facebook",
    status: "printing",
    priority: "rush",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyAgo(1),
    promised_ship_date: dateOnlyAgo(1),
    subtotal: 990,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1040,
    paid_amount: 500,
    total_cost: 1100,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "เลยกำหนดส่งแล้ว! QC รอบแรกไม่ผ่าน (สีเพี้ยน) กำลังพิมพ์ซ้ำเร่งด่วน",
    confirmed_at: daysAgo(13),
    cf_approved_at: daysAgo(6),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 14,
  }),
  ord({
    id: "ord-17",
    order_no: "MT-2026-0077",
    customer_id: "cus-17",
    conversation_id: null,
    source_channel: "line",
    status: "printing",
    priority: "rush",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(1),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 450,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 150,
    total_amount: 650,
    paid_amount: 300,
    total_cost: 345,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "งานด่วน ใกล้กำหนดส่งมาก",
    confirmed_at: daysAgo(4),
    cf_approved_at: daysAgo(1),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 5,
  }),

  // ---- qc (2) ----
  ord({
    id: "ord-18",
    order_no: "MT-2026-0078",
    customer_id: "cus-18",
    conversation_id: null,
    source_channel: "tiktok",
    status: "qc",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: dateOnlyFromNow(2),
    subtotal: 780,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 830,
    paid_amount: 830,
    total_cost: 521,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(8),
    cf_approved_at: daysAgo(2),
    printed_at: daysAgo(1),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 9,
  }),
  ord({
    id: "ord-19",
    order_no: "MT-2026-0079",
    customer_id: "cus-19",
    conversation_id: null,
    source_channel: "facebook",
    status: "qc",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(4),
    promised_ship_date: dateOnlyFromNow(3),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 150,
    total_cost: 225,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(6),
    cf_approved_at: daysAgo(2),
    printed_at: daysAgo(0),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 7,
  }),

  // ---- packing (2) ----
  ord({
    id: "ord-20",
    order_no: "MT-2026-0080",
    customer_id: "cus-20",
    conversation_id: null,
    source_channel: "line",
    status: "packing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 490,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 540,
    paid_amount: 540,
    total_cost: 350,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(8),
    cf_approved_at: daysAgo(3),
    printed_at: daysAgo(2),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 9,
  }),
  ord({
    id: "ord-21",
    order_no: "MT-2026-0081",
    customer_id: "cus-01",
    conversation_id: null,
    source_channel: "line",
    status: "packing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 1140,
    discount_amount: 100,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1090,
    paid_amount: 1090,
    total_cost: 722,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ลูกค้าประจำ สั่งซ้ำรอบ 2",
    confirmed_at: daysAgo(7),
    cf_approved_at: daysAgo(3),
    printed_at: daysAgo(2),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 8,
  }),

  // ---- ready_to_ship (2) — O22 = COD ----
  ord({
    id: "ord-22",
    order_no: "MT-2026-0082",
    customer_id: "cus-05",
    conversation_id: null,
    source_channel: "facebook",
    status: "ready_to_ship",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(1),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 500,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 550,
    paid_amount: 0,
    total_cost: 396,
    is_cod: true,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "เก็บเงินปลายทาง",
    confirmed_at: daysAgo(9),
    cf_approved_at: daysAgo(4),
    printed_at: daysAgo(2),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 10,
  }),
  ord({
    id: "ord-23",
    order_no: "MT-2026-0083",
    customer_id: "cus-21",
    conversation_id: null,
    source_channel: "line",
    status: "ready_to_ship",
    priority: "rush",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(0),
    promised_ship_date: dateOnlyFromNow(0),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 340,
    total_cost: 265,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ครบกำหนดส่งวันนี้ — ต้องซิงก์เลขพัสดุด่วน",
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(2),
    printed_at: daysAgo(1),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 6,
  }),

  // ---- shipped (3) — O26 = COD ยังไม่เก็บเงิน ----
  ord({
    id: "ord-24",
    order_no: "MT-2026-0084",
    customer_id: "cus-08",
    conversation_id: null,
    source_channel: "facebook",
    status: "shipped",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(0),
    promised_ship_date: dateOnlyAgo(1),
    subtotal: 690,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 740,
    paid_amount: 740,
    total_cost: 520,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(15),
    cf_approved_at: daysAgo(9),
    printed_at: daysAgo(4),
    shipped_at: daysAgo(1),
    delivered_at: null,
    createdDaysAgo: 16,
  }),
  ord({
    id: "ord-25",
    order_no: "MT-2026-0085",
    customer_id: "cus-22",
    conversation_id: null,
    source_channel: "tiktok",
    status: "shipped",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 750,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 800,
    paid_amount: 400,
    total_cost: 565,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ยังค้างชำระ 400 ฿ แม้ส่งของแล้ว — ไม่มี gate",
    confirmed_at: daysAgo(14),
    cf_approved_at: daysAgo(8),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(1),
    delivered_at: null,
    createdDaysAgo: 15,
  }),
  ord({
    id: "ord-26",
    order_no: "MT-2026-0086",
    customer_id: "cus-09",
    conversation_id: null,
    source_channel: "line",
    status: "shipped",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 780,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 830,
    paid_amount: 0,
    total_cost: 591,
    is_cod: true,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "COD ยังไม่เก็บเงิน",
    confirmed_at: daysAgo(13),
    cf_approved_at: daysAgo(7),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(1),
    delivered_at: null,
    createdDaysAgo: 14,
  }),

  // ---- delivered (4) — O28 = flagship demo (reprint+COD), O30 = กำไรติดลบ ----
  ord({
    id: "ord-27",
    order_no: "MT-2026-0087",
    customer_id: "cus-23",
    conversation_id: null,
    source_channel: "facebook",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: daysAgo(1).slice(0, 10),
    promised_ship_date: daysAgo(3).slice(0, 10),
    subtotal: 1470,
    discount_amount: 100,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1420,
    paid_amount: 1420,
    total_cost: 940,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "ลูกค้าแฟนคลับทีมฟุตบอล ออเดอร์ใหญ่ 3 ผืน",
    confirmed_at: daysAgo(7),
    cf_approved_at: daysAgo(6),
    printed_at: daysAgo(4),
    shipped_at: daysAgo(3),
    delivered_at: daysAgo(2),
    createdDaysAgo: 8,
  }),
  ord({
    id: "ord-28",
    order_no: "MT-2026-0088",
    customer_id: "cus-24",
    conversation_id: "conv-07",
    source_channel: "tiktok",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: daysAgo(3).slice(0, 10),
    promised_ship_date: daysAgo(2).slice(0, 10),
    subtotal: 980,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1030,
    paid_amount: 1030,
    total_cost: 955,
    is_cod: true,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "Demo เต็มเส้น: ลูกค้าขอแก้สีพื้นรอบ CF v1 → v2 ผ่าน → QC รอบแรกไม่ผ่าน (สีเพี้ยน) → พิมพ์ซ้ำ → ส่งสำเร็จ เก็บ COD แล้ว",
    confirmed_at: daysAgo(7),
    cf_approved_at: daysAgo(5),
    printed_at: daysAgo(4),
    shipped_at: daysAgo(2),
    delivered_at: daysAgo(1),
    createdDaysAgo: 8,
  }),
  ord({
    id: "ord-29",
    order_no: "MT-2026-0089",
    customer_id: "cus-10",
    conversation_id: null,
    source_channel: "facebook",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(1),
    promised_ship_date: daysAgo(2).slice(0, 10),
    subtotal: 250,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 300,
    paid_amount: 300,
    total_cost: 253,
    is_cod: true,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "COD เก็บเงินสำเร็จแล้ว",
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(4),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(2),
    delivered_at: daysAgo(1),
    createdDaysAgo: 6,
  }),
  ord({
    id: "ord-30",
    order_no: "MT-2026-0090",
    customer_id: "cus-25",
    conversation_id: null,
    source_channel: "line",
    status: "delivered",
    priority: "rush",
    design_source: "in_house",
    sale_staff_id: "stf-sale-2",
    due_date: daysAgo(4).slice(0, 10),
    promised_ship_date: daysAgo(2).slice(0, 10),
    subtotal: 1490,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 1540,
    paid_amount: 1540,
    total_cost: 1650,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "กำไรติดลบ — พิมพ์ซ้ำ 2 รอบ เสียผ้า+หมึกไปมาก ต้นทุนบานปลาย",
    confirmed_at: daysAgo(10),
    cf_approved_at: daysAgo(7),
    printed_at: daysAgo(2),
    shipped_at: daysAgo(1),
    delivered_at: daysAgo(0),
    createdDaysAgo: 11,
  }),

  // ---- cancelled (1) ----
  ord({
    id: "ord-31",
    order_no: "MT-2026-0091",
    customer_id: "cus-26",
    conversation_id: null,
    source_channel: "facebook",
    status: "cancelled",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: null,
    promised_ship_date: null,
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: "ลูกค้าเปลี่ยนใจไปสั่งร้านอื่น",
    hold_reason: null,
    previous_status: "quoted",
    note: "รับมัดจำไปแล้ว 300 ฿ ก่อนยกเลิก — คืนเงินเรียบร้อยแล้ว",
    confirmed_at: null,
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 10,
  }),

  // ---- on_hold (1) ----
  ord({
    id: "ord-32",
    order_no: "MT-2026-0092",
    customer_id: "cus-27",
    conversation_id: null,
    source_channel: "line",
    status: "on_hold",
    priority: "normal",
    design_source: "in_house",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(10),
    promised_ship_date: null,
    subtotal: 490,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 540,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: "ลูกค้าขอพักรอโอนเงินก้อนใหญ่ช่วงสิ้นเดือน",
    previous_status: "designing",
    note: null,
    confirmed_at: daysAgo(10),
    cf_approved_at: null,
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 11,
  }),

  // ---- Contract v3: เพิ่มออเดอร์เรียบง่าย ไม่มีเรื่องซับซ้อน (O33-O43) เพื่อดึงเลข lead time /
  // อัตราพิมพ์ซ้ำ / อัตราส่งช้า ให้ใกล้ benchmark ปัจจุบัน (§ benchmarks.ts) — ทุกใบตรงเวลา จ่ายครบ
  // ---- delivered เร็ว (3) ----
  ord({
    id: "ord-33",
    order_no: "MT-2026-0093",
    customer_id: "cus-02",
    conversation_id: null,
    source_channel: "facebook",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(1),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 340,
    total_cost: 265,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(4),
    cf_approved_at: daysAgo(3),
    printed_at: daysAgo(2),
    shipped_at: daysAgo(1),
    delivered_at: daysAgo(1),
    createdDaysAgo: 5,
  }),
  ord({
    id: "ord-34",
    order_no: "MT-2026-0094",
    customer_id: "cus-03",
    conversation_id: null,
    source_channel: "tiktok",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(1),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 340,
    total_cost: 265,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(4),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(2),
    delivered_at: daysAgo(1),
    createdDaysAgo: 6,
  }),
  ord({
    id: "ord-35",
    order_no: "MT-2026-0095",
    customer_id: "cus-04",
    conversation_id: null,
    source_channel: "line",
    status: "delivered",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: daysAgo(0).slice(0, 10),
    subtotal: 250,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 300,
    paid_amount: 300,
    total_cost: 238,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(6),
    cf_approved_at: daysAgo(5),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(2),
    delivered_at: daysAgo(0),
    createdDaysAgo: 7,
  }),

  // ---- shipped ตรงเวลา (2) ----
  ord({
    id: "ord-36",
    order_no: "MT-2026-0096",
    customer_id: "cus-06",
    conversation_id: null,
    source_channel: "line",
    status: "shipped",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 390,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 440,
    paid_amount: 440,
    total_cost: 328,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(4),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(1),
    delivered_at: null,
    createdDaysAgo: 6,
  }),
  ord({
    id: "ord-37",
    order_no: "MT-2026-0097",
    customer_id: "cus-07",
    conversation_id: null,
    source_channel: "tiktok",
    status: "shipped",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: daysAgo(1).slice(0, 10),
    subtotal: 580,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 630,
    paid_amount: 630,
    total_cost: 460,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(6),
    cf_approved_at: daysAgo(5),
    printed_at: daysAgo(3),
    shipped_at: daysAgo(1),
    delivered_at: null,
    createdDaysAgo: 7,
  }),

  // ---- ready_to_ship ตรงเวลา (1) ----
  ord({
    id: "ord-38",
    order_no: "MT-2026-0098",
    customer_id: "cus-11",
    conversation_id: null,
    source_channel: "line",
    status: "ready_to_ship",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(2),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 450,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 500,
    paid_amount: 500,
    total_cost: 370,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(5),
    cf_approved_at: daysAgo(4),
    printed_at: daysAgo(2),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 6,
  }),

  // ---- packing ตรงเวลา (1) ----
  ord({
    id: "ord-39",
    order_no: "MT-2026-0099",
    customer_id: "cus-12",
    conversation_id: null,
    source_channel: "tiktok",
    status: "packing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: dateOnlyFromNow(1),
    subtotal: 490,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 540,
    paid_amount: 540,
    total_cost: 350,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(4),
    cf_approved_at: daysAgo(3),
    printed_at: daysAgo(1),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 5,
  }),

  // ---- qc — "รอ QC" เลนบอร์ดผลิต (2) ----
  ord({
    id: "ord-40",
    order_no: "MT-2026-0100",
    customer_id: "cus-13",
    conversation_id: null,
    source_channel: "line",
    status: "qc",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: dateOnlyFromNow(2),
    subtotal: 390,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 440,
    paid_amount: 440,
    total_cost: 268,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(3),
    cf_approved_at: daysAgo(2),
    printed_at: daysAgo(1),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 4,
  }),
  ord({
    id: "ord-42",
    order_no: "MT-2026-0102",
    customer_id: "cus-19",
    conversation_id: null,
    source_channel: "facebook",
    status: "qc",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(3),
    promised_ship_date: dateOnlyFromNow(2),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 340,
    total_cost: 215,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: null,
    confirmed_at: daysAgo(3),
    cf_approved_at: daysAgo(2),
    printed_at: daysAgo(0),
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 4,
  }),

  // ---- printing — print_job ยัง "queued" (รอพิมพ์ เลนบอร์ดผลิต, 2) — total_cost=0 ยังไม่ตัดสต๊อก ----
  ord({
    id: "ord-41",
    order_no: "MT-2026-0101",
    customer_id: "cus-17",
    conversation_id: null,
    source_channel: "line",
    status: "printing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-2",
    due_date: dateOnlyFromNow(4),
    promised_ship_date: dateOnlyFromNow(3),
    subtotal: 250,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 300,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "รอคิวเครื่องพิมพ์ผ้า ยังไม่เริ่ม",
    confirmed_at: daysAgo(2),
    cf_approved_at: daysAgo(1),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 3,
  }),
  ord({
    id: "ord-43",
    order_no: "MT-2026-0103",
    customer_id: "cus-20",
    conversation_id: null,
    source_channel: "line",
    status: "printing",
    priority: "normal",
    design_source: "customer_file",
    sale_staff_id: "stf-sale-1",
    due_date: dateOnlyFromNow(4),
    promised_ship_date: dateOnlyFromNow(3),
    subtotal: 290,
    discount_amount: 0,
    shipping_fee: 50,
    rush_fee: 0,
    total_amount: 340,
    paid_amount: 0,
    total_cost: 0,
    is_cod: false,
    cancel_reason: null,
    hold_reason: null,
    previous_status: null,
    note: "รอคิวเครื่องพิมพ์ผ้า ยังไม่เริ่ม",
    confirmed_at: daysAgo(2),
    cf_approved_at: daysAgo(1),
    printed_at: null,
    shipped_at: null,
    delivered_at: null,
    createdDaysAgo: 3,
  }),
];

// Review note (data-seeder): ตัวเลขทุกออเดอร์ยึดกฎ total_amount = subtotal − discount + shipping + rush,
// outstanding = total − paid, gross_profit = total − total_cost (คำนวณผ่าน helper `ord()` กันพลาดมือ).
// total_cost = 0 สำหรับออเดอร์ที่ยังไม่ถึงขั้นตัดสต๊อก (< printing) — ยังไม่มีต้นทุนเกิดขึ้นจริงตามจุดตัดสต๊อก §3.17.
