// payments.ts — ชำระเงิน/มัดจำ/COD/คืนเงิน — amount เก็บค่าบวกเสมอ (แม้ refund), UI แสดง − เอง
import type { MattiiPayment } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function pay(
  p: Omit<MattiiPayment, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiPayment {
  const { ageDays, ...rest } = p;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const payments: MattiiPayment[] = [
  pay({
    id: "pay-05-1",
    order_id: "ord-05",
    payment_no: "PAY-0065-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(4),
    slip_url: "/mock/mattii/slips/slip-0065-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 4,
  }),
  pay({
    id: "pay-06-1",
    order_id: "ord-06",
    payment_no: "PAY-0066-1",
    payment_type: "full",
    method: "transfer",
    amount: 630,
    status: "paid",
    paid_at: daysAgo(3),
    slip_url: "/mock/mattii/slips/slip-0066-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 3,
  }),
  pay({
    id: "pay-08-1",
    order_id: "ord-08",
    payment_no: "PAY-0068-1",
    payment_type: "deposit",
    method: "promptpay",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(4),
    slip_url: "/mock/mattii/slips/slip-0068-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 4,
  }),
  pay({
    id: "pay-09-1",
    order_id: "ord-09",
    payment_no: "PAY-0069-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 400,
    status: "paid",
    paid_at: daysAgo(3),
    slip_url: "/mock/mattii/slips/slip-0069-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 3,
  }),
  pay({
    id: "pay-10-1",
    order_id: "ord-10",
    payment_no: "PAY-0070-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 500,
    status: "paid",
    paid_at: daysAgo(18),
    slip_url: "/mock/mattii/slips/slip-0070-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 18,
  }),
  pay({
    id: "pay-12-1",
    order_id: "ord-12",
    payment_no: "PAY-0072-1",
    payment_type: "deposit",
    method: "promptpay",
    amount: 200,
    status: "paid",
    paid_at: daysAgo(2),
    slip_url: "/mock/mattii/slips/slip-0072-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 2,
  }),
  pay({
    id: "pay-13-1",
    order_id: "ord-13",
    payment_no: "PAY-0073-1",
    payment_type: "full",
    method: "transfer",
    amount: 800,
    status: "paid",
    paid_at: daysAgo(5),
    slip_url: "/mock/mattii/slips/slip-0073-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 5,
  }),
  pay({
    id: "pay-14-1",
    order_id: "ord-14",
    payment_no: "PAY-0074-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 1000,
    status: "paid",
    paid_at: daysAgo(7),
    slip_url: "/mock/mattii/slips/slip-0074-1.jpg",
    received_by_id: "stf-sale-2",
    note: "งานสั่งตัดพิเศษ เก็บมัดจำสูงกว่าปกติ",
    ageDays: 7,
  }),
  pay({
    id: "pay-17-1",
    order_id: "ord-17",
    payment_no: "PAY-0077-1",
    payment_type: "deposit",
    method: "promptpay",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(4),
    slip_url: "/mock/mattii/slips/slip-0077-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 4,
  }),
  pay({
    id: "pay-18-1",
    order_id: "ord-18",
    payment_no: "PAY-0078-1",
    payment_type: "full",
    method: "transfer",
    amount: 830,
    status: "paid",
    paid_at: daysAgo(8),
    slip_url: "/mock/mattii/slips/slip-0078-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 8,
  }),
  pay({
    id: "pay-19-1",
    order_id: "ord-19",
    payment_no: "PAY-0079-1",
    payment_type: "deposit",
    method: "promptpay",
    amount: 150,
    status: "paid",
    paid_at: daysAgo(6),
    slip_url: "/mock/mattii/slips/slip-0079-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 6,
  }),
  pay({
    id: "pay-20-1",
    order_id: "ord-20",
    payment_no: "PAY-0080-1",
    payment_type: "full",
    method: "transfer",
    amount: 540,
    status: "paid",
    paid_at: daysAgo(8),
    slip_url: "/mock/mattii/slips/slip-0080-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 8,
  }),
  pay({
    id: "pay-21-1",
    order_id: "ord-21",
    payment_no: "PAY-0081-1",
    payment_type: "full",
    method: "transfer",
    amount: 1090,
    status: "paid",
    paid_at: daysAgo(7),
    slip_url: "/mock/mattii/slips/slip-0081-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 7,
  }),
  pay({
    id: "pay-23-1",
    order_id: "ord-23",
    payment_no: "PAY-0083-1",
    payment_type: "full",
    method: "promptpay",
    amount: 340,
    status: "paid",
    paid_at: daysAgo(5),
    slip_url: "/mock/mattii/slips/slip-0083-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 5,
  }),
  pay({
    id: "pay-24-1",
    order_id: "ord-24",
    payment_no: "PAY-0084-1",
    payment_type: "full",
    method: "transfer",
    amount: 740,
    status: "paid",
    paid_at: daysAgo(15),
    slip_url: "/mock/mattii/slips/slip-0084-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 15,
  }),
  pay({
    id: "pay-25-1",
    order_id: "ord-25",
    payment_no: "PAY-0085-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 400,
    status: "paid",
    paid_at: daysAgo(14),
    slip_url: "/mock/mattii/slips/slip-0085-1.jpg",
    received_by_id: "stf-sale-2",
    note: "ยังไม่ได้รับส่วนที่เหลือ 400 ฿ แม้ส่งของแล้ว",
    ageDays: 14,
  }),
  pay({
    id: "pay-27-1",
    order_id: "ord-27",
    payment_no: "PAY-0087-1",
    payment_type: "full",
    method: "transfer",
    amount: 1420,
    status: "paid",
    paid_at: daysAgo(19),
    slip_url: "/mock/mattii/slips/slip-0087-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 19,
  }),
  pay({
    id: "pay-28-1",
    order_id: "ord-28",
    payment_no: "PAY-0088-1",
    payment_type: "full",
    method: "cod",
    amount: 1030,
    status: "paid",
    paid_at: daysAgo(1),
    slip_url: null,
    received_by_id: "stf-prod-2",
    note: "เก็บเงินปลายทางสำเร็จ",
    ageDays: 1,
  }),
  pay({
    id: "pay-29-1",
    order_id: "ord-29",
    payment_no: "PAY-0089-1",
    payment_type: "full",
    method: "cod",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(1),
    slip_url: null,
    received_by_id: "stf-prod-1",
    note: "เก็บเงินปลายทางสำเร็จ",
    ageDays: 1,
  }),
  pay({
    id: "pay-30-1",
    order_id: "ord-30",
    payment_no: "PAY-0090-1",
    payment_type: "full",
    method: "transfer",
    amount: 1540,
    status: "paid",
    paid_at: daysAgo(21),
    slip_url: "/mock/mattii/slips/slip-0090-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 21,
  }),
  // ord-31 — รับมัดจำก่อนยกเลิก แล้วคืนเงิน (refund = ค่าบวก แสดง − ที่ UI)
  pay({
    id: "pay-31-1",
    order_id: "ord-31",
    payment_no: "PAY-0091-1",
    payment_type: "deposit",
    method: "transfer",
    amount: 300,
    status: "refunded",
    paid_at: daysAgo(9),
    slip_url: "/mock/mattii/slips/slip-0091-1.jpg",
    received_by_id: "stf-sale-1",
    note: "รับมัดจำก่อนลูกค้าขอยกเลิก",
    ageDays: 9,
  }),
  pay({
    id: "pay-31-2",
    order_id: "ord-31",
    payment_no: "PAY-0091-2",
    payment_type: "refund",
    method: "transfer",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(8),
    slip_url: "/mock/mattii/slips/slip-0091-2.jpg",
    received_by_id: "stf-sale-1",
    note: "คืนเงินมัดจำหลังยกเลิกออเดอร์ — แสดงเป็น −300.00 ฿ ใน UI",
    ageDays: 8,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O40, O42 จ่ายครบ (O41/O43 ยังไม่จ่าย — proof ไม่บล็อกเงิน) ----
  pay({
    id: "pay-33-1",
    order_id: "ord-33",
    payment_no: "PAY-0093-1",
    payment_type: "full",
    method: "transfer",
    amount: 340,
    status: "paid",
    paid_at: daysAgo(4),
    slip_url: "/mock/mattii/slips/slip-0093-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 4,
  }),
  pay({
    id: "pay-34-1",
    order_id: "ord-34",
    payment_no: "PAY-0094-1",
    payment_type: "full",
    method: "promptpay",
    amount: 340,
    status: "paid",
    paid_at: daysAgo(5),
    slip_url: "/mock/mattii/slips/slip-0094-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 5,
  }),
  pay({
    id: "pay-35-1",
    order_id: "ord-35",
    payment_no: "PAY-0095-1",
    payment_type: "full",
    method: "transfer",
    amount: 300,
    status: "paid",
    paid_at: daysAgo(6),
    slip_url: "/mock/mattii/slips/slip-0095-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 6,
  }),
  pay({
    id: "pay-36-1",
    order_id: "ord-36",
    payment_no: "PAY-0096-1",
    payment_type: "full",
    method: "promptpay",
    amount: 440,
    status: "paid",
    paid_at: daysAgo(5),
    slip_url: "/mock/mattii/slips/slip-0096-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 5,
  }),
  pay({
    id: "pay-37-1",
    order_id: "ord-37",
    payment_no: "PAY-0097-1",
    payment_type: "full",
    method: "transfer",
    amount: 630,
    status: "paid",
    paid_at: daysAgo(6),
    slip_url: "/mock/mattii/slips/slip-0097-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 6,
  }),
  pay({
    id: "pay-38-1",
    order_id: "ord-38",
    payment_no: "PAY-0098-1",
    payment_type: "full",
    method: "transfer",
    amount: 500,
    status: "paid",
    paid_at: daysAgo(5),
    slip_url: "/mock/mattii/slips/slip-0098-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 5,
  }),
  pay({
    id: "pay-39-1",
    order_id: "ord-39",
    payment_no: "PAY-0099-1",
    payment_type: "full",
    method: "promptpay",
    amount: 540,
    status: "paid",
    paid_at: daysAgo(4),
    slip_url: "/mock/mattii/slips/slip-0099-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 4,
  }),
  pay({
    id: "pay-40-1",
    order_id: "ord-40",
    payment_no: "PAY-0100-1",
    payment_type: "full",
    method: "transfer",
    amount: 440,
    status: "paid",
    paid_at: daysAgo(3),
    slip_url: "/mock/mattii/slips/slip-0100-1.jpg",
    received_by_id: "stf-sale-2",
    note: null,
    ageDays: 3,
  }),
  pay({
    id: "pay-42-1",
    order_id: "ord-42",
    payment_no: "PAY-0102-1",
    payment_type: "full",
    method: "transfer",
    amount: 340,
    status: "paid",
    paid_at: daysAgo(3),
    slip_url: "/mock/mattii/slips/slip-0102-1.jpg",
    received_by_id: "stf-sale-1",
    note: null,
    ageDays: 3,
  }),
];
