// print-jobs.ts — คิวผลิตต่อเครื่อง (mattii_print_jobs) รวมประวัติพิมพ์ซ้ำ (ord-16 / ord-28 / ord-30 x2)
import type { MattiiPrintJob } from "./types";
import { MOCK_ORG_ID, daysAgo, daysFromNow } from "./helpers";

function pj(
  p: Omit<MattiiPrintJob, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiPrintJob {
  const { ageDays, ...rest } = p;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const printJobs: MattiiPrintJob[] = [
  pj({
    id: "prt-15-1",
    order_id: "ord-15",
    job_no: "PRT-0075-1",
    machine_id: "mac-print",
    design_version_id: "dvr-15-1",
    status: "printing",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(1),
    started_at: daysAgo(1),
    finished_at: null,
    pieces: 2,
    material_note: "ผ้ากำมะหยี่ + หมึก CMYK",
    ageDays: 1,
  }),

  pj({
    id: "prt-16-1",
    order_id: "ord-16",
    job_no: "PRT-0076-1",
    machine_id: "mac-print",
    design_version_id: "dvr-16-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(6),
    started_at: daysAgo(6),
    finished_at: daysAgo(5),
    pieces: 1,
    material_note: "ผ้าลูปไพล์ + หมึก CMYK",
    ageDays: 6,
  }),
  pj({
    id: "prt-16-2",
    order_id: "ord-16",
    job_no: "PRT-0076-2",
    machine_id: "mac-print",
    design_version_id: "dvr-16-1",
    status: "printing",
    queue_position: 1,
    is_reprint: true,
    reprint_of_job_id: "prt-16-1",
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(1),
    started_at: daysAgo(1),
    finished_at: null,
    pieces: 1,
    material_note: "พิมพ์ซ้ำจาก QC fail (สีเพี้ยน)",
    ageDays: 1,
  }),

  pj({
    id: "prt-17-1",
    order_id: "ord-17",
    job_no: "PRT-0077-1",
    machine_id: "mac-print",
    design_version_id: "dvr-17-1",
    status: "printing",
    queue_position: 2,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(0),
    started_at: daysAgo(0),
    finished_at: null,
    pieces: 1,
    material_note: "งานด่วน แทรกคิว",
    ageDays: 1,
  }),

  pj({
    id: "prt-18-1",
    order_id: "ord-18",
    job_no: "PRT-0078-1",
    machine_id: "mac-print",
    design_version_id: "dvr-18-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(2),
    started_at: daysAgo(2),
    finished_at: daysAgo(1),
    pieces: 2,
    material_note: null,
    ageDays: 8,
  }),
  pj({
    id: "prt-19-1",
    order_id: "ord-19",
    job_no: "PRT-0079-1",
    machine_id: "mac-print",
    design_version_id: "dvr-19-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(1),
    started_at: daysAgo(1),
    finished_at: daysAgo(0),
    pieces: 1,
    material_note: null,
    ageDays: 6,
  }),

  pj({
    id: "prt-20-1",
    order_id: "ord-20",
    job_no: "PRT-0080-1",
    machine_id: "mac-print",
    design_version_id: "dvr-20-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 1,
    material_note: null,
    ageDays: 8,
  }),
  pj({
    id: "prt-21-1",
    order_id: "ord-21",
    job_no: "PRT-0081-1",
    machine_id: "mac-print",
    design_version_id: "dvr-21-1",
    status: "done",
    queue_position: 2,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 6,
    material_note: null,
    ageDays: 7,
  }),

  pj({
    id: "prt-22-1",
    order_id: "ord-22",
    job_no: "PRT-0082-1",
    machine_id: "mac-print",
    design_version_id: "dvr-22-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 2,
    material_note: null,
    ageDays: 9,
  }),
  pj({
    id: "prt-23-1",
    order_id: "ord-23",
    job_no: "PRT-0083-1",
    machine_id: "mac-print",
    design_version_id: "dvr-23-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(2),
    started_at: daysAgo(2),
    finished_at: daysAgo(1),
    pieces: 1,
    material_note: "งานด่วน",
    ageDays: 5,
  }),

  pj({
    id: "prt-24-1",
    order_id: "ord-24",
    job_no: "PRT-0084-1",
    machine_id: "mac-print",
    design_version_id: "dvr-24-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(5),
    started_at: daysAgo(5),
    finished_at: daysAgo(4),
    pieces: 1,
    material_note: null,
    ageDays: 15,
  }),
  pj({
    id: "prt-25-1",
    order_id: "ord-25",
    job_no: "PRT-0085-1",
    machine_id: "mac-print",
    design_version_id: "dvr-25-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: null,
    ageDays: 14,
  }),
  pj({
    id: "prt-26-1",
    order_id: "ord-26",
    job_no: "PRT-0086-1",
    machine_id: "mac-print",
    design_version_id: "dvr-26-1",
    status: "done",
    queue_position: 2,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 2,
    material_note: null,
    ageDays: 13,
  }),

  pj({
    id: "prt-27-1",
    order_id: "ord-27",
    job_no: "PRT-0087-1",
    machine_id: "mac-print",
    design_version_id: "dvr-27-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(5),
    started_at: daysAgo(5),
    finished_at: daysAgo(4),
    pieces: 3,
    material_note: null,
    ageDays: 7,
  }),

  pj({
    id: "prt-28-1",
    order_id: "ord-28",
    job_no: "PRT-0088-1",
    machine_id: "mac-print",
    design_version_id: "dvr-28-2",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(6),
    started_at: daysAgo(6),
    finished_at: daysAgo(5),
    pieces: 2,
    material_note: null,
    ageDays: 6,
  }),
  pj({
    id: "prt-28-2",
    order_id: "ord-28",
    job_no: "PRT-0088-2",
    machine_id: "mac-print",
    design_version_id: "dvr-28-2",
    status: "done",
    queue_position: 1,
    is_reprint: true,
    reprint_of_job_id: "prt-28-1",
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(4),
    pieces: 1,
    material_note: "พิมพ์ซ้ำ 1 ผืนจาก QC fail (สีเพี้ยน)",
    ageDays: 4,
  }),

  pj({
    id: "prt-29-1",
    order_id: "ord-29",
    job_no: "PRT-0089-1",
    machine_id: "mac-print",
    design_version_id: "dvr-29-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: null,
    ageDays: 12,
  }),

  pj({
    id: "prt-30-1",
    order_id: "ord-30",
    job_no: "PRT-0090-1",
    machine_id: "mac-print",
    design_version_id: "dvr-30-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(5),
    started_at: daysAgo(5),
    finished_at: daysAgo(4),
    pieces: 1,
    material_note: null,
    ageDays: 5,
  }),
  pj({
    id: "prt-30-2",
    order_id: "ord-30",
    job_no: "PRT-0090-2",
    machine_id: "mac-print",
    design_version_id: "dvr-30-1",
    status: "done",
    queue_position: 1,
    is_reprint: true,
    reprint_of_job_id: "prt-30-1",
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: "พิมพ์ซ้ำรอบ 1 (ลายเบี้ยว)",
    ageDays: 4,
  }),
  pj({
    id: "prt-30-3",
    order_id: "ord-30",
    job_no: "PRT-0090-3",
    machine_id: "mac-print",
    design_version_id: "dvr-30-1",
    status: "done",
    queue_position: 1,
    is_reprint: true,
    reprint_of_job_id: "prt-30-2",
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 1,
    material_note: "พิมพ์ซ้ำรอบ 2 (ผ้าตำหนิ) — ผ่านในที่สุด",
    ageDays: 3,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O43 — พิมพ์ครั้งเดียวผ่าน (ไม่มี reprint) ----
  pj({
    id: "prt-33-1",
    order_id: "ord-33",
    job_no: "PRT-0093-1",
    machine_id: "mac-print",
    design_version_id: "dvr-33-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 1,
    material_note: null,
    ageDays: 3,
  }),
  pj({
    id: "prt-34-1",
    order_id: "ord-34",
    job_no: "PRT-0094-1",
    machine_id: "mac-print",
    design_version_id: "dvr-34-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: null,
    ageDays: 4,
  }),
  pj({
    id: "prt-35-1",
    order_id: "ord-35",
    job_no: "PRT-0095-1",
    machine_id: "mac-print",
    design_version_id: "dvr-35-1",
    status: "done",
    queue_position: 2,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: null,
    ageDays: 4,
  }),
  pj({
    id: "prt-36-1",
    order_id: "ord-36",
    job_no: "PRT-0096-1",
    machine_id: "mac-print",
    design_version_id: "dvr-36-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 1,
    material_note: null,
    ageDays: 4,
  }),
  pj({
    id: "prt-37-1",
    order_id: "ord-37",
    job_no: "PRT-0097-1",
    machine_id: "mac-print",
    design_version_id: "dvr-37-1",
    status: "done",
    queue_position: 2,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(4),
    started_at: daysAgo(4),
    finished_at: daysAgo(3),
    pieces: 2,
    material_note: null,
    ageDays: 4,
  }),
  pj({
    id: "prt-38-1",
    order_id: "ord-38",
    job_no: "PRT-0098-1",
    machine_id: "mac-print",
    design_version_id: "dvr-38-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(3),
    started_at: daysAgo(3),
    finished_at: daysAgo(2),
    pieces: 1,
    material_note: null,
    ageDays: 3,
  }),
  pj({
    id: "prt-39-1",
    order_id: "ord-39",
    job_no: "PRT-0099-1",
    machine_id: "mac-print",
    design_version_id: "dvr-39-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(2),
    started_at: daysAgo(2),
    finished_at: daysAgo(1),
    pieces: 1,
    material_note: null,
    ageDays: 2,
  }),
  pj({
    id: "prt-40-1",
    order_id: "ord-40",
    job_no: "PRT-0100-1",
    machine_id: "mac-print",
    design_version_id: "dvr-40-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-2",
    planned_start_at: daysAgo(2),
    started_at: daysAgo(2),
    finished_at: daysAgo(1),
    pieces: 1,
    material_note: null,
    ageDays: 2,
  }),
  pj({
    id: "prt-41-1",
    order_id: "ord-41",
    job_no: "PRT-0101-1",
    machine_id: null,
    design_version_id: "dvr-41-1",
    status: "queued",
    queue_position: 3,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: null,
    planned_start_at: daysFromNow(1),
    started_at: null,
    finished_at: null,
    pieces: 1,
    material_note: "รอคิวเครื่องพิมพ์ผ้า PRN-01",
    ageDays: 1,
  }),
  pj({
    id: "prt-42-1",
    order_id: "ord-42",
    job_no: "PRT-0102-1",
    machine_id: "mac-print",
    design_version_id: "dvr-42-1",
    status: "done",
    queue_position: 1,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: "stf-prod-1",
    planned_start_at: daysAgo(1),
    started_at: daysAgo(1),
    finished_at: daysAgo(0),
    pieces: 1,
    material_note: null,
    ageDays: 1,
  }),
  pj({
    id: "prt-43-1",
    order_id: "ord-43",
    job_no: "PRT-0103-1",
    machine_id: null,
    design_version_id: "dvr-43-1",
    status: "queued",
    queue_position: 4,
    is_reprint: false,
    reprint_of_job_id: null,
    operator_id: null,
    planned_start_at: daysFromNow(2),
    started_at: null,
    finished_at: null,
    pieces: 1,
    material_note: "รอคิวเครื่องพิมพ์ผ้า PRN-01",
    ageDays: 1,
  }),
];
