// products.ts — 6 แบบพรม + ตารางขนาด/ราคาต่อชิ้น (mattii_products + mattii_product_sizes)
import type { MattiiProduct, MattiiProductSize } from "./types";
import { MOCK_ORG_ID, daysAgo, fabricUsage } from "./helpers";

export const products: MattiiProduct[] = [
  {
    id: "prd-01",
    org_id: MOCK_ORG_ID,
    code: "RUG-DM-01",
    name: "พรมเช็ดเท้ากำมะหยี่ พิมพ์ลายเต็มผืน",
    category: "doormat",
    fabric_type: "กำมะหยี่ (velvet)",
    backing_type: "ยางกันลื่น PVC",
    edge_finish: "overlock",
    print_method: "sublimation",
    default_lead_time_days: 3,
    option_schema: [
      { key: "edge_color", label: "สีขอบ", values: ["ดำ", "เทา", "ครีม"] },
      { key: "anti_slip", label: "ยางกันลื่น", values: ["มี", "ไม่มี"] },
    ],
    image_url: "/mock/mattii/rug-doormat-velvet.jpg",
    is_active: true,
    note: "แบบขายดีที่สุด — ลูกค้าส่งลายเองเป็นส่วนใหญ่",
    created_at: daysAgo(300),
    updated_at: daysAgo(30),
  },
  {
    id: "prd-02",
    org_id: MOCK_ORG_ID,
    code: "RUG-EN-01",
    name: "พรมหน้าบ้านผ้าไมโครไฟเบอร์",
    category: "entrance",
    fabric_type: "ไมโครไฟเบอร์",
    backing_type: "ยางลาเท็กซ์",
    edge_finish: "binding",
    print_method: "sublimation",
    default_lead_time_days: 3,
    option_schema: [{ key: "edge_color", label: "สีขอบ", values: ["ดำ", "น้ำตาล", "เทา"] }],
    image_url: "/mock/mattii/rug-entrance-microfiber.jpg",
    is_active: true,
    note: null,
    created_at: daysAgo(280),
    updated_at: daysAgo(60),
  },
  {
    id: "prd-03",
    org_id: MOCK_ORG_ID,
    code: "RUG-LR-01",
    name: "พรมห้องนั่งเล่นขนสั้น",
    category: "living_room",
    fabric_type: "ผ้าลูปไพล์",
    backing_type: "ยางกันลื่น PVC",
    edge_finish: "overlock",
    print_method: "sublimation",
    default_lead_time_days: 4,
    option_schema: [{ key: "edge_color", label: "สีขอบ", values: ["ดำ", "เทา", "ครีม", "น้ำตาล"] }],
    image_url: "/mock/mattii/rug-livingroom.jpg",
    is_active: true,
    note: "ผืนใหญ่ ใช้เวลาผลิตนานกว่าแบบอื่น",
    created_at: daysAgo(250),
    updated_at: daysAgo(20),
  },
  {
    id: "prd-04",
    org_id: MOCK_ORG_ID,
    code: "RUG-BD-01",
    name: "พรมข้างเตียง",
    category: "bedroom",
    fabric_type: "ไมโครไฟเบอร์",
    backing_type: "ยางกันลื่น PVC",
    edge_finish: "binding",
    print_method: "sublimation",
    default_lead_time_days: 2,
    option_schema: [{ key: "anti_slip", label: "ยางกันลื่น", values: ["มี", "ไม่มี"] }],
    image_url: "/mock/mattii/rug-bedside.jpg",
    is_active: true,
    note: null,
    created_at: daysAgo(220),
    updated_at: daysAgo(45),
  },
  {
    id: "prd-05",
    org_id: MOCK_ORG_ID,
    code: "RUG-TM-01",
    name: "แผ่นรองจานพิมพ์ลาย",
    category: "table_mat",
    fabric_type: "ไมโครไฟเบอร์เคลือบกันน้ำ",
    backing_type: null,
    edge_finish: "raw",
    print_method: "sublimation",
    default_lead_time_days: 2,
    option_schema: [],
    image_url: "/mock/mattii/table-mat.jpg",
    is_active: true,
    note: "ขายดีเป็นเซ็ต 4-6 ผืนสำหรับร้านกาแฟ/ร้านอาหาร",
    created_at: daysAgo(180),
    updated_at: daysAgo(10),
  },
  {
    id: "prd-06",
    org_id: MOCK_ORG_ID,
    code: "RUG-CU-01",
    name: "พรมสั่งตัดพิเศษ",
    category: "custom",
    fabric_type: "ตามสั่ง (เลือกได้ตอนคุยกับลูกค้า)",
    backing_type: "ยางกันลื่น PVC",
    edge_finish: "overlock",
    print_method: "sublimation",
    default_lead_time_days: 5,
    option_schema: [{ key: "edge_color", label: "สีขอบ", values: ["ดำ", "เทา", "ครีม"] }],
    image_url: "/mock/mattii/rug-custom.jpg",
    is_active: true,
    note: "ใช้ price_per_sqm คำนวณราคา — Sale กรอกกว้าง×ยาวเอง",
    created_at: daysAgo(150),
    updated_at: daysAgo(5),
  },
];

function size(
  s: Omit<MattiiProductSize, "org_id" | "fabric_usage_sqm" | "created_at" | "updated_at"> & {
    fabric_usage_sqm?: number;
  },
): MattiiProductSize {
  return {
    ...s,
    org_id: MOCK_ORG_ID,
    fabric_usage_sqm:
      s.fabric_usage_sqm ?? (s.width_cm && s.length_cm ? fabricUsage(s.width_cm, s.length_cm) : 0),
    created_at: daysAgo(150),
    updated_at: daysAgo(10),
  };
}

export const productSizes: MattiiProductSize[] = [
  // ---- prd-01 พรมเช็ดเท้ากำมะหยี่ ----
  size({
    id: "sz-01-1",
    product_id: "prd-01",
    size_kind: "standard",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    unit_price: 290,
    base_cost: 125,
    price_per_sqm: null,
    sort_order: 1,
    is_active: true,
  }),
  size({
    id: "sz-01-2",
    product_id: "prd-01",
    size_kind: "standard",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    unit_price: 390,
    base_cost: 168,
    price_per_sqm: null,
    sort_order: 2,
    is_active: true,
  }),
  size({
    id: "sz-01-3",
    product_id: "prd-01",
    size_kind: "standard",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    unit_price: 490,
    base_cost: 210,
    price_per_sqm: null,
    sort_order: 3,
    is_active: true,
  }),
  size({
    id: "sz-01-4",
    product_id: "prd-01",
    size_kind: "custom_cut",
    size_label: "สั่งตัดพิเศษ",
    width_cm: null,
    length_cm: null,
    unit_price: 0,
    base_cost: 0,
    price_per_sqm: 980,
    fabric_usage_sqm: 0,
    sort_order: 4,
    is_active: true,
  }),

  // ---- prd-02 พรมหน้าบ้านไมโครไฟเบอร์ ----
  size({
    id: "sz-02-1",
    product_id: "prd-02",
    size_kind: "standard",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    unit_price: 250,
    base_cost: 108,
    price_per_sqm: null,
    sort_order: 1,
    is_active: true,
  }),
  size({
    id: "sz-02-2",
    product_id: "prd-02",
    size_kind: "standard",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    unit_price: 450,
    base_cost: 195,
    price_per_sqm: null,
    sort_order: 2,
    is_active: true,
  }),
  size({
    id: "sz-02-3",
    product_id: "prd-02",
    size_kind: "standard",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    unit_price: 750,
    base_cost: 325,
    price_per_sqm: null,
    sort_order: 3,
    is_active: true,
  }),
  size({
    id: "sz-02-4",
    product_id: "prd-02",
    size_kind: "custom_cut",
    size_label: "สั่งตัดพิเศษ",
    width_cm: null,
    length_cm: null,
    unit_price: 0,
    base_cost: 0,
    price_per_sqm: 820,
    fabric_usage_sqm: 0,
    sort_order: 4,
    is_active: true,
  }),

  // ---- prd-03 พรมห้องนั่งเล่นขนสั้น ----
  size({
    id: "sz-03-1",
    product_id: "prd-03",
    size_kind: "standard",
    size_label: "60 × 90 ซม.",
    width_cm: 60,
    length_cm: 90,
    unit_price: 690,
    base_cost: 300,
    price_per_sqm: null,
    sort_order: 1,
    is_active: true,
  }),
  size({
    id: "sz-03-2",
    product_id: "prd-03",
    size_kind: "standard",
    size_label: "80 × 120 ซม.",
    width_cm: 80,
    length_cm: 120,
    unit_price: 990,
    base_cost: 430,
    price_per_sqm: null,
    sort_order: 2,
    is_active: true,
  }),
  size({
    id: "sz-03-3",
    product_id: "prd-03",
    size_kind: "standard",
    size_label: "100 × 150 ซม.",
    width_cm: 100,
    length_cm: 150,
    unit_price: 1490,
    base_cost: 650,
    price_per_sqm: null,
    sort_order: 3,
    is_active: true,
  }),
  size({
    id: "sz-03-4",
    product_id: "prd-03",
    size_kind: "custom_cut",
    size_label: "สั่งตัดพิเศษ",
    width_cm: null,
    length_cm: null,
    unit_price: 0,
    base_cost: 0,
    price_per_sqm: 1050,
    fabric_usage_sqm: 0,
    sort_order: 4,
    is_active: true,
  }),

  // ---- prd-04 พรมข้างเตียง ----
  size({
    id: "sz-04-1",
    product_id: "prd-04",
    size_kind: "standard",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    unit_price: 290,
    base_cost: 125,
    price_per_sqm: null,
    sort_order: 1,
    is_active: true,
  }),
  size({
    id: "sz-04-2",
    product_id: "prd-04",
    size_kind: "standard",
    size_label: "50 × 80 ซม.",
    width_cm: 50,
    length_cm: 80,
    unit_price: 390,
    base_cost: 168,
    price_per_sqm: null,
    sort_order: 2,
    is_active: true,
  }),

  // ---- prd-05 แผ่นรองจาน ----
  size({
    id: "sz-05-1",
    product_id: "prd-05",
    size_kind: "standard",
    size_label: "30 × 45 ซม.",
    width_cm: 30,
    length_cm: 45,
    unit_price: 190,
    base_cost: 82,
    price_per_sqm: null,
    sort_order: 1,
    is_active: true,
  }),
  size({
    id: "sz-05-2",
    product_id: "prd-05",
    size_kind: "standard",
    size_label: "40 × 60 ซม.",
    width_cm: 40,
    length_cm: 60,
    unit_price: 290,
    base_cost: 125,
    price_per_sqm: null,
    sort_order: 2,
    is_active: true,
  }),

  // ---- prd-06 พรมสั่งตัดพิเศษ (custom_cut ล้วน) ----
  size({
    id: "sz-06-1",
    product_id: "prd-06",
    size_kind: "custom_cut",
    size_label: "สั่งตัดพิเศษ",
    width_cm: null,
    length_cm: null,
    unit_price: 0,
    base_cost: 0,
    price_per_sqm: 890,
    fabric_usage_sqm: 0,
    sort_order: 1,
    is_active: true,
  }),
];
