// qc.ts — QC & แพ็ค (mattii_qc_records) รวมเคส QC fail → พิมพ์ซ้ำ (ord-16 / ord-28 / ord-30 x2)
import type { MattiiQcRecord } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function qc(
  q: Omit<MattiiQcRecord, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiQcRecord {
  const { ageDays, ...rest } = q;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const qcRecords: MattiiQcRecord[] = [
  // ord-16 — QC รอบแรกไม่ผ่าน (สีเพี้ยน) ยังไม่แพ็ค เพราะกำลังพิมพ์ซ้ำ
  qc({
    id: "qc-16-1",
    order_id: "ord-16",
    print_job_id: "prt-16-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(5),
    result: "fail",
    defect_type: "color_off",
    defect_note: "สีพื้นเพี้ยนจากไฟล์ต้นฉบับชัดเจน ไม่ผ่านมาตรฐาน",
    defect_qty: 1,
    defect_cost: 430,
    photo_url: "/mock/mattii/qc/defect-color-off-16.jpg",
    packing_status: "not_packed",
    packed_by_id: null,
    packed_at: null,
    package_count: 1,
    weight_kg: null,
    ageDays: 5,
  }),

  qc({
    id: "qc-20-1",
    order_id: "ord-20",
    print_job_id: "prt-20-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 1.2,
    ageDays: 2,
  }),
  qc({
    id: "qc-21-1",
    order_id: "ord-21",
    print_job_id: "prt-21-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(1),
    package_count: 2,
    weight_kg: 3.5,
    ageDays: 2,
  }),

  qc({
    id: "qc-22-1",
    order_id: "ord-22",
    print_job_id: "prt-22-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 1.0,
    ageDays: 2,
  }),
  qc({
    id: "qc-23-1",
    order_id: "ord-23",
    print_job_id: "prt-23-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(1),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(0),
    package_count: 1,
    weight_kg: 0.6,
    ageDays: 1,
  }),

  qc({
    id: "qc-24-1",
    order_id: "ord-24",
    print_job_id: "prt-24-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(3),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 1.3,
    ageDays: 3,
  }),
  qc({
    id: "qc-25-1",
    order_id: "ord-25",
    print_job_id: "prt-25-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 1.6,
    ageDays: 2,
  }),
  qc({
    id: "qc-26-1",
    order_id: "ord-26",
    print_job_id: "prt-26-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(2),
    package_count: 2,
    weight_kg: 1.8,
    ageDays: 2,
  }),

  qc({
    id: "qc-27-1",
    order_id: "ord-27",
    print_job_id: "prt-27-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(3),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(3),
    package_count: 2,
    weight_kg: 2.5,
    ageDays: 3,
  }),

  // ord-28 — flagship demo: fail รอบแรก (สีเพี้ยน) → พิมพ์ซ้ำ → pass → packed
  qc({
    id: "qc-28-1",
    order_id: "ord-28",
    print_job_id: "prt-28-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(5),
    result: "fail",
    defect_type: "color_off",
    defect_note: "สีพื้นเพี้ยนไปจากไฟล์ v2 ที่ลูกค้า CF ไว้ 1 ผืน",
    defect_qty: 1,
    defect_cost: 210,
    photo_url: "/mock/mattii/qc/defect-color-off-28.jpg",
    packing_status: "not_packed",
    packed_by_id: null,
    packed_at: null,
    package_count: 1,
    weight_kg: null,
    ageDays: 5,
  }),
  qc({
    id: "qc-28-2",
    order_id: "ord-28",
    print_job_id: "prt-28-2",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(3),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 1.4,
    ageDays: 3,
  }),

  qc({
    id: "qc-29-1",
    order_id: "ord-29",
    print_job_id: "prt-29-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 0.5,
    ageDays: 2,
  }),

  // ord-30 — พิมพ์ซ้ำ 2 รอบ (ลายเบี้ยว แล้วผ้าตำหนิ) ก่อนจะผ่าน
  qc({
    id: "qc-30-1",
    order_id: "ord-30",
    print_job_id: "prt-30-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(4),
    result: "fail",
    defect_type: "misalign",
    defect_note: "ลายเบี้ยวไม่ตรงกึ่งกลางผืน",
    defect_qty: 1,
    defect_cost: 650,
    photo_url: "/mock/mattii/qc/defect-misalign-30.jpg",
    packing_status: "not_packed",
    packed_by_id: null,
    packed_at: null,
    package_count: 1,
    weight_kg: null,
    ageDays: 4,
  }),
  qc({
    id: "qc-30-2",
    order_id: "ord-30",
    print_job_id: "prt-30-2",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(3),
    result: "fail",
    defect_type: "material_defect",
    defect_note: "ผ้าที่ใช้พิมพ์ซ้ำมีตำหนิจากโรงงาน",
    defect_qty: 1,
    defect_cost: 650,
    photo_url: "/mock/mattii/qc/defect-material-30.jpg",
    packing_status: "not_packed",
    packed_by_id: null,
    packed_at: null,
    package_count: 1,
    weight_kg: null,
    ageDays: 3,
  }),
  qc({
    id: "qc-30-3",
    order_id: "ord-30",
    print_job_id: "prt-30-3",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 2.2,
    ageDays: 2,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O39 — QC ผ่านครั้งเดียว (O40/O42 ยังไม่ตรวจ, O41/O43 ยังไม่พิมพ์) ----
  qc({
    id: "qc-33-1",
    order_id: "ord-33",
    print_job_id: "prt-33-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(1),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 0.5,
    ageDays: 1,
  }),
  qc({
    id: "qc-34-1",
    order_id: "ord-34",
    print_job_id: "prt-34-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 0.5,
    ageDays: 2,
  }),
  qc({
    id: "qc-35-1",
    order_id: "ord-35",
    print_job_id: "prt-35-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(2),
    package_count: 1,
    weight_kg: 0.4,
    ageDays: 2,
  }),
  qc({
    id: "qc-36-1",
    order_id: "ord-36",
    print_job_id: "prt-36-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 0.6,
    ageDays: 2,
  }),
  qc({
    id: "qc-37-1",
    order_id: "ord-37",
    print_job_id: "prt-37-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(2),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-2",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 0.9,
    ageDays: 2,
  }),
  qc({
    id: "qc-38-1",
    order_id: "ord-38",
    print_job_id: "prt-38-1",
    checked_by_id: "stf-prod-2",
    checked_at: daysAgo(1),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "packed",
    packed_by_id: "stf-prod-1",
    packed_at: daysAgo(1),
    package_count: 1,
    weight_kg: 0.7,
    ageDays: 1,
  }),
  qc({
    id: "qc-39-1",
    order_id: "ord-39",
    print_job_id: "prt-39-1",
    checked_by_id: "stf-prod-1",
    checked_at: daysAgo(0),
    result: "pass",
    defect_type: null,
    defect_note: null,
    defect_qty: 0,
    defect_cost: 0,
    photo_url: null,
    packing_status: "not_packed",
    packed_by_id: null,
    packed_at: null,
    package_count: 1,
    weight_kg: null,
    ageDays: 0,
  }),
];
