// shipments.ts — จัดส่ง (mock Shipnity + J&T) สำหรับออเดอร์ตั้งแต่ ready_to_ship ขึ้นไป
import type { MattiiShipment } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

function ship(
  s: Omit<MattiiShipment, "org_id" | "created_at" | "updated_at"> & { ageDays: number },
): MattiiShipment {
  const { ageDays, ...rest } = s;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(Math.min(ageDays, 1)),
  };
}

export const shipments: MattiiShipment[] = [
  ship({
    id: "shp-22",
    order_id: "ord-22",
    carrier: "jt",
    tracking_no: null,
    status: "pending",
    shipnity_order_ref: null,
    recipient_name: "วิภาวดี มงคลชัย",
    recipient_phone: "081-999-2211",
    address_snapshot: "45 ถ.เจริญกรุง บางรัก บางรัก กรุงเทพมหานคร 10500",
    shipping_cost: 45,
    cod_amount: 550,
    cod_collected: false,
    label_created_at: null,
    picked_up_at: null,
    delivered_at: null,
    last_synced_at: null,
    tracking_events: [{ at: daysAgo(1), status: "pending", description: "รอสร้างเลขพัสดุ" }],
    ageDays: 1,
  }),
  ship({
    id: "shp-23",
    order_id: "ord-23",
    carrier: "jt",
    tracking_no: "JT2026TH0083001",
    status: "label_created",
    shipnity_order_ref: "SHN-0083",
    recipient_name: "ธัญญารัตน์ ไชยวงศ์",
    recipient_phone: "088-111-4499",
    address_snapshot: "40 ถ.เพชรเกษม บางแค บางแค กรุงเทพมหานคร 10160",
    shipping_cost: 40,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(0),
    picked_up_at: null,
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(0), status: "pending", description: "สร้างรายการส่ง" },
      { at: daysAgo(0), status: "label_created", description: "ซิงก์เลขพัสดุจาก Shipnity สำเร็จ" },
    ],
    ageDays: 0,
  }),
  ship({
    id: "shp-24",
    order_id: "ord-24",
    carrier: "jt",
    tracking_no: "JT2026TH0084001",
    status: "in_transit",
    shipnity_order_ref: "SHN-0084",
    recipient_name: "ณัฐวุฒิ ไพรงาม",
    recipient_phone: "084-555-6677",
    address_snapshot: "3 ถ.ห้วยแก้ว ช้างเผือก เมืองเชียงใหม่ เชียงใหม่ 50300",
    shipping_cost: 50,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(1),
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "in_transit", description: "อยู่ระหว่างขนส่งไปเชียงใหม่" },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-25",
    order_id: "ord-25",
    carrier: "jt",
    tracking_no: "JT2026TH0085001",
    status: "in_transit",
    shipnity_order_ref: "SHN-0085",
    recipient_name: "วรากร ศิลป์ดี",
    recipient_phone: "064-777-2233",
    address_snapshot: "18 ถ.นิพัทธ์อุทิศ หาดใหญ่ หาดใหญ่ สงขลา 90110",
    shipping_cost: 55,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(1),
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "in_transit", description: "อยู่ระหว่างขนส่งไปหาดใหญ่" },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-26",
    order_id: "ord-26",
    carrier: "jt",
    tracking_no: "JT2026TH0086001",
    status: "in_transit",
    shipnity_order_ref: "SHN-0086",
    recipient_name: "จิราภรณ์ แสงทอง",
    recipient_phone: "090-888-1122",
    address_snapshot: "9 ถ.สายลม สามเสนใน พญาไท กรุงเทพมหานคร 10400",
    shipping_cost: 60,
    cod_amount: 830,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(1),
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      {
        at: daysAgo(0),
        status: "in_transit",
        description: "อยู่ระหว่างขนส่ง — เก็บเงินปลายทาง 830 ฿",
      },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-27",
    order_id: "ord-27",
    carrier: "shipnity_other",
    tracking_no: "SHN2026OTH0087001",
    status: "delivered",
    shipnity_order_ref: "SHN-0087",
    recipient_name: "ประวิทย์ เก่งกีฬา",
    recipient_phone: "081-555-4477",
    address_snapshot: "27 ถ.สุขุมวิท บางนา บางนา กรุงเทพมหานคร 10260",
    shipping_cost: 60,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(4),
    picked_up_at: daysAgo(3),
    delivered_at: daysAgo(2),
    last_synced_at: daysAgo(2),
    tracking_events: [
      {
        at: daysAgo(4),
        status: "label_created",
        description: "สร้างเลขพัสดุแล้ว (ขนส่งอื่นผ่าน Shipnity)",
      },
      { at: daysAgo(3), status: "picked_up", description: "เข้ารับพัสดุแล้ว" },
      { at: daysAgo(2), status: "delivered", description: "ส่งสำเร็จ ลูกค้าเซ็นรับแล้ว" },
    ],
    ageDays: 4,
  }),
  ship({
    id: "shp-28",
    order_id: "ord-28",
    carrier: "jt",
    tracking_no: "JT2026TH0088001",
    status: "delivered",
    shipnity_order_ref: "SHN-0088",
    recipient_name: "มะลิวัลย์ เจริญพร",
    recipient_phone: "095-888-2244",
    address_snapshot: "77/8 ถ.รัชดาภิเษก ดินแดง ดินแดง กรุงเทพมหานคร 10400",
    shipping_cost: 55,
    cod_amount: 1030,
    cod_collected: true,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(2),
    delivered_at: daysAgo(1),
    last_synced_at: daysAgo(1),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(2), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      {
        at: daysAgo(1),
        status: "delivered",
        description: "ส่งสำเร็จ เก็บเงินปลายทาง 1,030 ฿ เรียบร้อย",
      },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-29",
    order_id: "ord-29",
    carrier: "jt",
    tracking_no: "JT2026TH0089001",
    status: "delivered",
    shipnity_order_ref: "SHN-0089",
    recipient_name: "อนุสรณ์ พูนสุข",
    recipient_phone: "087-321-6655",
    address_snapshot: "168 ถ.เลียบคลอง 6 คลองหก คลองหลวง ปทุมธานี 12120",
    shipping_cost: 40,
    cod_amount: 300,
    cod_collected: true,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(2),
    delivered_at: daysAgo(1),
    last_synced_at: daysAgo(1),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(2), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      {
        at: daysAgo(1),
        status: "delivered",
        description: "ส่งสำเร็จ เก็บเงินปลายทาง 300 ฿ เรียบร้อย",
      },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-30",
    order_id: "ord-30",
    carrier: "jt",
    tracking_no: "JT2026TH0090001",
    status: "delivered",
    shipnity_order_ref: "SHN-0090",
    recipient_name: "อรรถพล ดาวเรือง",
    recipient_phone: "089-222-6677",
    address_snapshot: "50 ถ.สรรพสิทธิ์ ในเมือง เมืองอุบลราชธานี อุบลราชธานี 34000",
    shipping_cost: 280,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(1),
    delivered_at: daysAgo(0),
    last_synced_at: daysAgo(0),
    tracking_events: [
      {
        at: daysAgo(2),
        status: "label_created",
        description: "สร้างเลขพัสดุแล้ว (ส่งด่วนพิเศษชดเชยความล่าช้า)",
      },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "delivered", description: "ส่งสำเร็จ" },
    ],
    ageDays: 2,
  }),

  // ---- Contract v3: ออเดอร์เสริม O33-O38 — ส่งตรงเวลาทั้งหมด ----
  ship({
    id: "shp-33",
    order_id: "ord-33",
    carrier: "jt",
    tracking_no: "JT2026TH0093001",
    status: "delivered",
    shipnity_order_ref: "SHN-0093",
    recipient_name: "อรวรรณ ใจงาม",
    recipient_phone: "089-112-2345",
    address_snapshot: "23 ถ.นิมมานเหมินท์ สุเทพ เมืองเชียงใหม่ เชียงใหม่ 50200",
    shipping_cost: 40,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(1),
    picked_up_at: daysAgo(1),
    delivered_at: daysAgo(1),
    last_synced_at: daysAgo(1),
    tracking_events: [
      { at: daysAgo(1), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(1), status: "delivered", description: "ส่งสำเร็จ" },
    ],
    ageDays: 1,
  }),
  ship({
    id: "shp-34",
    order_id: "ord-34",
    carrier: "jt",
    tracking_no: "JT2026TH0094001",
    status: "delivered",
    shipnity_order_ref: "SHN-0094",
    recipient_name: "ธนภรณ์ สินสมบูรณ์",
    recipient_phone: "092-333-1188",
    address_snapshot: "56 ถ.มิตรภาพ ในเมือง เมืองขอนแก่น ขอนแก่น 40000",
    shipping_cost: 40,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(2),
    delivered_at: daysAgo(1),
    last_synced_at: daysAgo(1),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(2), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(1), status: "delivered", description: "ส่งสำเร็จ" },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-35",
    order_id: "ord-35",
    carrier: "jt",
    tracking_no: "JT2026TH0095001",
    status: "delivered",
    shipnity_order_ref: "SHN-0095",
    recipient_name: "สุภาพร วงศ์เจริญ",
    recipient_phone: "085-777-9900",
    address_snapshot: "199 ถ.เจริญนคร คลองต้นไทร คลองสาน กรุงเทพมหานคร 10600",
    shipping_cost: 35,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(2),
    picked_up_at: daysAgo(2),
    delivered_at: daysAgo(0),
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(2), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(2), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "delivered", description: "ส่งสำเร็จ" },
    ],
    ageDays: 2,
  }),
  ship({
    id: "shp-36",
    order_id: "ord-36",
    carrier: "jt",
    tracking_no: "JT2026TH0096001",
    status: "in_transit",
    shipnity_order_ref: "SHN-0096",
    recipient_name: "กมลชนก ทองแท้",
    recipient_phone: "086-222-3344",
    address_snapshot: "12 ถ.สุขาภิบาล 3 บางชัน คลองสามวา กรุงเทพมหานคร 10510",
    shipping_cost: 45,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(1),
    picked_up_at: daysAgo(1),
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(1), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "in_transit", description: "อยู่ระหว่างขนส่ง" },
    ],
    ageDays: 1,
  }),
  ship({
    id: "shp-37",
    order_id: "ord-37",
    carrier: "jt",
    tracking_no: "JT2026TH0097001",
    status: "in_transit",
    shipnity_order_ref: "SHN-0097",
    recipient_name: "ปิยะดา ศรีสวัสดิ์",
    recipient_phone: "093-456-7788",
    address_snapshot: "77 ถ.ประชาอุทิศ ทุ่งครุ ทุ่งครุ กรุงเทพมหานคร 10140",
    shipping_cost: 45,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(1),
    picked_up_at: daysAgo(1),
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(1), status: "label_created", description: "สร้างเลขพัสดุแล้ว" },
      { at: daysAgo(1), status: "picked_up", description: "J&T เข้ารับพัสดุแล้ว" },
      { at: daysAgo(0), status: "in_transit", description: "อยู่ระหว่างขนส่ง" },
    ],
    ageDays: 1,
  }),
  ship({
    id: "shp-38",
    order_id: "ord-38",
    carrier: "jt",
    tracking_no: "JT2026TH0098001",
    status: "label_created",
    shipnity_order_ref: "SHN-0098",
    recipient_name: "ศศิธร บุญมาก",
    recipient_phone: "091-234-8899",
    address_snapshot: "34 ถ.ศรีนครินทร์ หนองบอน ประเวศ กรุงเทพมหานคร 10250",
    shipping_cost: 45,
    cod_amount: 0,
    cod_collected: false,
    label_created_at: daysAgo(0),
    picked_up_at: null,
    delivered_at: null,
    last_synced_at: daysAgo(0),
    tracking_events: [
      { at: daysAgo(0), status: "label_created", description: "ซิงก์เลขพัสดุจาก Shipnity สำเร็จ" },
    ],
    ageDays: 0,
  }),
];
