// staff.ts — ทีม Mattii 7 คน กระจาย 4 role
import type { MattiiStaff } from "./types";
import { MOCK_ORG_ID, daysAgo } from "./helpers";

export const staff: MattiiStaff[] = [
  {
    id: "stf-owner",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "สมพงษ์ รุ่งเรืองกิจ",
    role: "owner",
    phone: "081-234-9001",
    line_user_id: "Uowner0001mattii",
    hourly_rate: 500,
    is_active: true,
    created_at: daysAgo(400),
    updated_at: daysAgo(400),
  },
  {
    id: "stf-sale-1",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "พิมพ์ใจ สายชล",
    role: "sale",
    phone: "089-555-1122",
    line_user_id: "Usale0001mattii",
    hourly_rate: 150,
    is_active: true,
    created_at: daysAgo(300),
    updated_at: daysAgo(300),
  },
  {
    id: "stf-sale-2",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "ณัฐพล เกียรติก้อง",
    role: "sale",
    phone: "086-444-7788",
    line_user_id: "Usale0002mattii",
    hourly_rate: 150,
    is_active: true,
    created_at: daysAgo(200),
    updated_at: daysAgo(200),
  },
  {
    id: "stf-design-1",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "ชนากานต์ ศิลป์เจริญ",
    role: "designer",
    phone: "062-333-4455",
    line_user_id: "Udesign0001mattii",
    hourly_rate: 180,
    is_active: true,
    created_at: daysAgo(250),
    updated_at: daysAgo(250),
  },
  {
    id: "stf-design-2",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "ภูริช วาดฝัน",
    role: "designer",
    phone: "063-222-6699",
    line_user_id: null,
    hourly_rate: 170,
    is_active: true,
    created_at: daysAgo(120),
    updated_at: daysAgo(120),
  },
  {
    id: "stf-prod-1",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "สมชาย ช่างพิมพ์",
    role: "production",
    phone: "090-111-2233",
    line_user_id: "Uprod0001mattii",
    hourly_rate: 130,
    is_active: true,
    created_at: daysAgo(350),
    updated_at: daysAgo(350),
  },
  {
    id: "stf-prod-2",
    org_id: MOCK_ORG_ID,
    profile_id: null,
    display_name: "อรุณี ช่างเย็บ",
    role: "production",
    phone: "091-888-4433",
    line_user_id: null,
    hourly_rate: 130,
    is_active: true,
    created_at: daysAgo(180),
    updated_at: daysAgo(180),
  },
];
