// stock-movements.ts — ledger ความเคลื่อนไหวสต๊อก ครบทุก move_type (receive/consume_print/consume_pack/adjust/waste/return)
// running balance (qty_after) ไล่ตามลำดับเวลาต่อวัสดุ ลงท้ายตรงกับ materials.ts qty_on_hand เป๊ะ
// mov-11..17 / mov-21..23 ถูกอ้างจาก order-costs.ts (stock_movement_id) เป็นตัวอย่างเชื่อมโยงจริง
// รายการ "รวมตัดจากออเดอร์อื่นในเดือนนี้" คือก้อนรวมของออเดอร์ที่ไม่ได้ผูก stock_movement_id ทีละใบ (simplification เพื่อกัน fixture ยาวเกินจำเป็น)
import type { MattiiStockMovement } from "./types";
import { MOCK_ORG_ID, daysAgo, money } from "./helpers";

function mv(
  m: Omit<MattiiStockMovement, "org_id" | "total_cost" | "created_at" | "updated_at"> & {
    ageDays: number;
  },
): MattiiStockMovement {
  const { ageDays, ...rest } = m;
  return {
    ...rest,
    org_id: MOCK_ORG_ID,
    total_cost: money(Math.abs(rest.qty_delta) * rest.unit_cost_at_move),
    created_at: daysAgo(ageDays),
    updated_at: daysAgo(ageDays),
  };
}

export const stockMovements: MattiiStockMovement[] = [
  // ---- รับเข้าสต๊อกรอบเดือน (receive) ----
  mv({
    id: "mov-01",
    material_id: "mat-01",
    move_type: "receive",
    qty_delta: 100,
    qty_after: 100,
    unit_cost_at_move: 180,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกผ้ากำมะหยี่รอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-02",
    material_id: "mat-02",
    move_type: "receive",
    qty_delta: 150,
    qty_after: 150,
    unit_cost_at_move: 95,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกผ้าไมโครไฟเบอร์รอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-03",
    material_id: "mat-03",
    move_type: "receive",
    qty_delta: 100,
    qty_after: 100,
    unit_cost_at_move: 65,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกยางรองหลังรอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-04",
    material_id: "mat-04",
    move_type: "receive",
    qty_delta: 20,
    qty_after: 20,
    unit_cost_at_move: 950,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกหมึกซับลิเมชันรอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-05",
    material_id: "mat-05",
    move_type: "receive",
    qty_delta: 30,
    qty_after: 30,
    unit_cost_at_move: 420,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกฟิล์มทรานสเฟอร์รอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-06",
    material_id: "mat-06",
    move_type: "receive",
    qty_delta: 45,
    qty_after: 45,
    unit_cost_at_move: 45,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกด้ายเย็บโพ้งรอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-07",
    material_id: "mat-07",
    move_type: "receive",
    qty_delta: 400,
    qty_after: 400,
    unit_cost_at_move: 12,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกกล่องพัสดุรอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-08",
    material_id: "mat-08",
    move_type: "receive",
    qty_delta: 600,
    qty_after: 600,
    unit_cost_at_move: 4.5,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกถุงซิปกันน้ำรอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),
  mv({
    id: "mov-09",
    material_id: "mat-09",
    move_type: "receive",
    qty_delta: 25,
    qty_after: 25,
    unit_cost_at_move: 55,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าสต๊อกเทปกาวโลโก้รอบเดือน",
    occurred_at: daysAgo(28),
    ageDays: 28,
  }),

  // ---- return / adjust ระหว่างเดือน ----
  mv({
    id: "mov-28",
    material_id: "mat-08",
    move_type: "return",
    qty_delta: 15,
    qty_after: 615,
    unit_cost_at_move: 4.5,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-prod-1",
    reason: "เบิกเกินจากคลัง คืนเข้าสต๊อก",
    occurred_at: daysAgo(15),
    ageDays: 15,
  }),
  mv({
    id: "mov-27",
    material_id: "mat-06",
    move_type: "adjust",
    qty_delta: -2,
    qty_after: 43,
    unit_cost_at_move: 45,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "นับสต๊อกจริงพบขาดหาย 2 ม้วน",
    occurred_at: daysAgo(10),
    ageDays: 10,
  }),
  mv({
    id: "mov-29",
    material_id: "mat-04",
    move_type: "receive",
    qty_delta: 10,
    qty_after: 30,
    unit_cost_at_move: 950,
    order_id: null,
    print_job_id: null,
    staff_id: "stf-owner",
    reason: "รับเข้าเพิ่มระหว่างเดือน (ยังไม่พอใช้)",
    occurred_at: daysAgo(10),
    ageDays: 10,
  }),

  // ---- จุด A: ตัดตอนพิมพ์เสร็จ (consume_print) — ตัวอย่างที่ผูกกับ order_costs ---
  mv({
    id: "mov-25",
    material_id: "mat-01",
    move_type: "waste",
    qty_delta: -1.725,
    qty_after: 96.55,
    unit_cost_at_move: 180,
    order_id: "ord-30",
    print_job_id: "prt-30-1",
    staff_id: "stf-prod-2",
    reason: "ลายเบี้ยว ไม่ผ่าน QC (พิมพ์ซ้ำรอบ 1)",
    occurred_at: daysAgo(8),
    ageDays: 8,
  }),
  mv({
    id: "mov-23",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -4,
    qty_after: 92.55,
    unit_cost_at_move: 180,
    order_id: "ord-30",
    print_job_id: "prt-30-3",
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(6),
    ageDays: 6,
  }),
  mv({
    id: "mov-26",
    material_id: "mat-01",
    move_type: "waste",
    qty_delta: -1.104,
    qty_after: 91.446,
    unit_cost_at_move: 180,
    order_id: "ord-16",
    print_job_id: "prt-16-1",
    staff_id: "stf-prod-1",
    reason: "สีเพี้ยน ไม่ผ่าน QC",
    occurred_at: daysAgo(5),
    ageDays: 5,
  }),
  mv({
    id: "mov-12",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -2.389,
    qty_after: 89.057,
    unit_cost_at_move: 180,
    order_id: "ord-16",
    print_job_id: "prt-16-1",
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(5),
    ageDays: 5,
  }),
  mv({
    id: "mov-21",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -3.5,
    qty_after: 85.557,
    unit_cost_at_move: 180,
    order_id: "ord-28",
    print_job_id: "prt-28-2",
    staff_id: "stf-prod-2",
    reason: "รวมรอบแรก + พิมพ์ซ้ำ 1 ผืน",
    occurred_at: daysAgo(4),
    ageDays: 4,
  }),
  mv({
    id: "mov-16",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -2.733,
    qty_after: 82.824,
    unit_cost_at_move: 180,
    order_id: "ord-21",
    print_job_id: "prt-21-1",
    staff_id: "stf-prod-2",
    reason: null,
    occurred_at: daysAgo(2),
    ageDays: 2,
  }),
  mv({
    id: "mov-14",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -1.167,
    qty_after: 81.657,
    unit_cost_at_move: 180,
    order_id: "ord-20",
    print_job_id: "prt-20-1",
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(2),
    ageDays: 2,
  }),
  mv({
    id: "mov-13",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -2.389,
    qty_after: 79.268,
    unit_cost_at_move: 180,
    order_id: "ord-16",
    print_job_id: "prt-16-2",
    staff_id: "stf-prod-2",
    reason: "พิมพ์ซ้ำหลัง QC fail",
    occurred_at: daysAgo(1),
    ageDays: 1,
  }),
  mv({
    id: "mov-11",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -2.333,
    qty_after: 76.935,
    unit_cost_at_move: 180,
    order_id: "ord-15",
    print_job_id: "prt-15-1",
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(1),
    ageDays: 1,
  }),
  mv({
    id: "mov-31",
    material_id: "mat-01",
    move_type: "consume_print",
    qty_delta: -31.435,
    qty_after: 45.5,
    unit_cost_at_move: 180,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการตัดผ้ากำมะหยี่จากออเดอร์อื่นในเดือนนี้ (O5,O6,O18,O19,O22-O27,O29 ฯลฯ)",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),

  // ---- จุด B: ตัดตอนแพ็ค (consume_pack) — ตัวอย่างที่ผูกกับ order_costs ----
  mv({
    id: "mov-22",
    material_id: "mat-07",
    move_type: "consume_pack",
    qty_delta: -2,
    qty_after: 398,
    unit_cost_at_move: 12,
    order_id: "ord-28",
    print_job_id: null,
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(2),
    ageDays: 2,
  }),
  mv({
    id: "mov-15",
    material_id: "mat-07",
    move_type: "consume_pack",
    qty_delta: -2,
    qty_after: 396,
    unit_cost_at_move: 12,
    order_id: "ord-20",
    print_job_id: null,
    staff_id: "stf-prod-2",
    reason: null,
    occurred_at: daysAgo(1),
    ageDays: 1,
  }),
  mv({
    id: "mov-37",
    material_id: "mat-07",
    move_type: "consume_pack",
    qty_delta: -56,
    qty_after: 340,
    unit_cost_at_move: 12,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการแพ็คจากออเดอร์อื่นในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),

  mv({
    id: "mov-17",
    material_id: "mat-08",
    move_type: "consume_pack",
    qty_delta: -6,
    qty_after: 609,
    unit_cost_at_move: 4.5,
    order_id: "ord-21",
    print_job_id: null,
    staff_id: "stf-prod-1",
    reason: null,
    occurred_at: daysAgo(1),
    ageDays: 1,
  }),
  mv({
    id: "mov-38",
    material_id: "mat-08",
    move_type: "consume_pack",
    qty_delta: -99,
    qty_after: 510,
    unit_cost_at_move: 4.5,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการแพ็คจากออเดอร์อื่นในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),

  // ---- ก้อนรวมของวัสดุอื่นที่เหลือ (ไม่ได้ผูก order รายใบในชุดสาธิตนี้) ----
  mv({
    id: "mov-32",
    material_id: "mat-02",
    move_type: "consume_print",
    qty_delta: -30,
    qty_after: 120,
    unit_cost_at_move: 95,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการตัดผ้าไมโครไฟเบอร์จากหลายออเดอร์ในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
  mv({
    id: "mov-33",
    material_id: "mat-03",
    move_type: "consume_print",
    qty_delta: -20,
    qty_after: 80,
    unit_cost_at_move: 65,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการตัดยางรองหลังจากหลายออเดอร์ในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
  mv({
    id: "mov-34",
    material_id: "mat-04",
    move_type: "consume_print",
    qty_delta: -21.5,
    qty_after: 8.5,
    unit_cost_at_move: 950,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการใช้หมึกซับลิเมชันจากหลายออเดอร์ในเดือนนี้ — ใช้มากผิดปกติ ควรสั่งเพิ่มด่วน",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
  mv({
    id: "mov-35",
    material_id: "mat-05",
    move_type: "consume_print",
    qty_delta: -8,
    qty_after: 22,
    unit_cost_at_move: 420,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการใช้ฟิล์มทรานสเฟอร์จากหลายออเดอร์ในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
  mv({
    id: "mov-36",
    material_id: "mat-06",
    move_type: "consume_print",
    qty_delta: -8,
    qty_after: 35,
    unit_cost_at_move: 45,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการใช้ด้ายเย็บโพ้งจากหลายออเดอร์ในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
  mv({
    id: "mov-39",
    material_id: "mat-09",
    move_type: "consume_pack",
    qty_delta: -7,
    qty_after: 18,
    unit_cost_at_move: 55,
    order_id: null,
    print_job_id: null,
    staff_id: null,
    reason: "รวมการใช้เทปกาวโลโก้จากหลายออเดอร์ในเดือนนี้",
    occurred_at: daysAgo(0),
    ageDays: 0,
  }),
];
