BEGIN;

INSERT INTO public.pat (province_th, province_en, district_th, district_en, subdistrict_th, subdistrict_en, postcode, all_th, all_en)
VALUES
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'ปุลากง', 'Pulakong', '94150', 'ปัตตานี > ยะหริ่ง > ปุลากง > 94150', 'Pattani > Yaring > Pulakong > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'บาโลย', 'Baloi', '94190', 'ปัตตานี > ยะหริ่ง > บาโลย > 94190', 'Pattani > Yaring > Baloi > 94190'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'หนองแรต', 'Nong Raet', '94150', 'ปัตตานี > ยะหริ่ง > หนองแรต > 94150', 'Pattani > Yaring > Nong Raet > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'ราตาปันยัง', 'Rata Panyang', '94150', 'ปัตตานี > ยะหริ่ง > ราตาปันยัง > 94150', 'Pattani > Yaring > Rata Panyang > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'มะนังยง', 'Manang Yong', '94150', 'ปัตตานี > ยะหริ่ง > มะนังยง > 94150', 'Pattani > Yaring > Manang Yong > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'จะรัง', 'Charang', '94150', 'ปัตตานี > ยะหริ่ง > จะรัง > 94150', 'Pattani > Yaring > Charang > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'แหลมโพธิ์', 'Laem Pho', '94150', 'ปัตตานี > ยะหริ่ง > แหลมโพธิ์ > 94150', 'Pattani > Yaring > Laem Pho > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะหริ่ง', 'Yaring', 'สาบัน', 'Saban', '94150', 'ปัตตานี > ยะหริ่ง > สาบัน > 94150', 'Pattani > Yaring > Saban > 94150'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'ยะรัง', 'Yarang', '94160', 'ปัตตานี > ยะรัง > ยะรัง > 94160', 'Pattani > Yarang > Yarang > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'ประจัน', 'Prachan', '94160', 'ปัตตานี > ยะรัง > ประจัน > 94160', 'Pattani > Yarang > Prachan > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'ปิตูมุดี', 'Pitu Mudi', '94160', 'ปัตตานี > ยะรัง > ปิตูมุดี > 94160', 'Pattani > Yarang > Pitu Mudi > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'ระแว้ง', 'Rawaeng', '94160', 'ปัตตานี > ยะรัง > ระแว้ง > 94160', 'Pattani > Yarang > Rawaeng > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'วัด', 'Wat', '94160', 'ปัตตานี > ยะรัง > วัด > 94160', 'Pattani > Yarang > Wat > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'สะนอ', 'Sano', '94160', 'ปัตตานี > ยะรัง > สะนอ > 94160', 'Pattani > Yarang > Sano > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'สะดาวา', 'Sadawa', '94160', 'ปัตตานี > ยะรัง > สะดาวา > 94160', 'Pattani > Yarang > Sadawa > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'กระโด', 'Krado', '94160', 'ปัตตานี > ยะรัง > กระโด > 94160', 'Pattani > Yarang > Krado > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'กอลำ', 'Ko Lam', '94160', 'ปัตตานี > ยะรัง > กอลำ > 94160', 'Pattani > Yarang > Ko Lam > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'คลองใหม่', 'Khlong Mai', '94160', 'ปัตตานี > ยะรัง > คลองใหม่ > 94160', 'Pattani > Yarang > Khlong Mai > 94160'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'เมาะมาวี', 'Mo Mawi', '94160', 'ปัตตานี > ยะรัง > เมาะมาวี > 94160', 'Pattani > Yarang > Mo Mawi > 94160'),
  ('ปัตตานี', 'Pattani', 'แม่ลาน', 'Mae Lan', 'ม่วงเตี้ย', 'Muang Tia', '94180', 'ปัตตานี > แม่ลาน > ม่วงเตี้ย > 94180', 'Pattani > Mae Lan > Muang Tia > 94180'),
  ('ปัตตานี', 'Pattani', 'กะพ้อ', 'Kapho', 'ตะโละดือรามัน', 'Talo Due Raman', '94230', 'ปัตตานี > กะพ้อ > ตะโละดือรามัน > 94230', 'Pattani > Kapho > Talo Due Raman > 94230'),
  ('ปัตตานี', 'Pattani', 'แม่ลาน', 'Mae Lan', 'แม่ลาน', 'Mae Lan', '94180', 'ปัตตานี > แม่ลาน > แม่ลาน > 94180', 'Pattani > Mae Lan > Mae Lan > 94180'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'สะเตง', 'Sateng', '95000', 'ยะลา > เมืองยะลา > สะเตง > 95000', 'Yala > Mueang Yala > Sateng > 95000'),
  ('ปัตตานี', 'Pattani', 'กะพ้อ', 'Kapho', 'กะรุบี', 'Karubi', '94230', 'ปัตตานี > กะพ้อ > กะรุบี > 94230', 'Pattani > Kapho > Karubi > 94230'),
  ('ปัตตานี', 'Pattani', 'กะพ้อ', 'Kapho', 'ปล่องหอย', 'Plong Hoi', '94230', 'ปัตตานี > กะพ้อ > ปล่องหอย > 94230', 'Pattani > Kapho > Plong Hoi > 94230'),
  ('ปัตตานี', 'Pattani', 'ยะรัง', 'Yarang', 'เขาตูม', 'Khao Tum', '94160', 'ปัตตานี > ยะรัง > เขาตูม > 94160', 'Pattani > Yarang > Khao Tum > 94160'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'บุดี', 'Bu Di', '95000', 'ยะลา > เมืองยะลา > บุดี > 95000', 'Yala > Mueang Yala > Bu Di > 95000'),
  ('ปัตตานี', 'Pattani', 'แม่ลาน', 'Mae Lan', 'ป่าไร่', 'Pa Rai', '94180', 'ปัตตานี > แม่ลาน > ป่าไร่ > 94180', 'Pattani > Mae Lan > Pa Rai > 94180'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ยุโป', 'Yupo', '95000', 'ยะลา > เมืองยะลา > ยุโป > 95000', 'Yala > Mueang Yala > Yupo > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ลิดล', 'Li Don', '95160', 'ยะลา > เมืองยะลา > ลิดล > 95160', 'Yala > Mueang Yala > Li Don > 95160'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ลำพะยา', 'Lam Phaya', '95160', 'ยะลา > เมืองยะลา > ลำพะยา > 95160', 'Yala > Mueang Yala > Lam Phaya > 95160'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ท่าสาป', 'Tha Sap', '95000', 'ยะลา > เมืองยะลา > ท่าสาป > 95000', 'Yala > Mueang Yala > Tha Sap > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'เปาะเส้ง', 'Po Seng', '95000', 'ยะลา > เมืองยะลา > เปาะเส้ง > 95000', 'Yala > Mueang Yala > Po Seng > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ลำใหม่', 'Lam Mai', '95160', 'ยะลา > เมืองยะลา > ลำใหม่ > 95160', 'Yala > Mueang Yala > Lam Mai > 95160'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ยะลา', 'Yala', '95000', 'ยะลา > เมืองยะลา > ยะลา > 95000', 'Yala > Mueang Yala > Yala > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'หน้าถ้ำ', 'Na Tham', '95000', 'ยะลา > เมืองยะลา > หน้าถ้ำ > 95000', 'Yala > Mueang Yala > Na Tham > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'พร่อน', 'Phron', '95160', 'ยะลา > เมืองยะลา > พร่อน > 95160', 'Yala > Mueang Yala > Phron > 95160'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'สะเตงนอก', 'Sateng Nok', '95000', 'ยะลา > เมืองยะลา > สะเตงนอก > 95000', 'Yala > Mueang Yala > Sateng Nok > 95000'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'บันนังสาเรง', 'Bannang Sareng', '95000', 'ยะลา > เมืองยะลา > บันนังสาเรง > 95000', 'Yala > Mueang Yala > Bannang Sareng > 95000'),
  ('ยะลา', 'Yala', 'เบตง', 'Betong', 'ยะรม', 'Yarom', '95110', 'ยะลา > เบตง > ยะรม > 95110', 'Yala > Betong > Yarom > 95110'),
  ('ยะลา', 'Yala', 'เมืองยะลา', 'Mueang Yala', 'ตาเซะ', 'Tase', '95000', 'ยะลา > เมืองยะลา > ตาเซะ > 95000', 'Yala > Mueang Yala > Tase > 95000'),
  ('ยะลา', 'Yala', 'เบตง', 'Betong', 'อัยเยอร์เวง', 'Aiyoe Weng', '95110', 'ยะลา > เบตง > อัยเยอร์เวง > 95110', 'Yala > Betong > Aiyoe Weng > 95110'),
  ('ยะลา', 'Yala', 'เบตง', 'Betong', 'เบตง', 'Betong', '95110', 'ยะลา > เบตง > เบตง > 95110', 'Yala > Betong > Betong > 95110'),
  ('ยะลา', 'Yala', 'เบตง', 'Betong', 'ตาเนาะแมเราะ', 'Tano Maero', '95110', 'ยะลา > เบตง > ตาเนาะแมเราะ > 95110', 'Yala > Betong > Tano Maero > 95110'),
  ('ยะลา', 'Yala', 'เบตง', 'Betong', 'ธารน้ำทิพย์', 'Than Nam Thip', '95110', 'ยะลา > เบตง > ธารน้ำทิพย์ > 95110', 'Yala > Betong > Than Nam Thip > 95110'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'ถ้ำทะลุ', 'Tham Thalu', '95130', 'ยะลา > บันนังสตา > ถ้ำทะลุ > 95130', 'Yala > Bannang Sata > Tham Thalu > 95130'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'ตาเนาะปูเต๊ะ', 'Tano Pute', '95130', 'ยะลา > บันนังสตา > ตาเนาะปูเต๊ะ > 95130', 'Yala > Bannang Sata > Tano Pute > 95130'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'บาเจาะ', 'Bacho', '95130', 'ยะลา > บันนังสตา > บาเจาะ > 95130', 'Yala > Bannang Sata > Bacho > 95130'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'บันนังสตา', 'Bannang Sata', '95130', 'ยะลา > บันนังสตา > บันนังสตา > 95130', 'Yala > Bannang Sata > Bannang Sata > 95130'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'เขื่อนบางลาง', 'Khuean Bang Lang', '95130', 'ยะลา > บันนังสตา > เขื่อนบางลาง > 95130', 'Yala > Bannang Sata > Khuean Bang Lang > 95130'),
  ('ยะลา', 'Yala', 'บันนังสตา', 'Bannang Sata', 'ตลิ่งชัน', 'Taling Chan', '95130', 'ยะลา > บันนังสตา > ตลิ่งชัน > 95130', 'Yala > Bannang Sata > Taling Chan > 95130'),
  ('ยะลา', 'Yala', 'ธารโต', 'Than To', 'บ้านแหร', 'Ban Rae', '95150', 'ยะลา > ธารโต > บ้านแหร > 95150', 'Yala > Than To > Ban Rae > 95150'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'ยะหา', 'Yaha', '95120', 'ยะลา > ยะหา > ยะหา > 95120', 'Yala > Yaha > Yaha > 95120'),
  ('ยะลา', 'Yala', 'ธารโต', 'Than To', 'คีรีเขต', 'Khiri Khet', '95150', 'ยะลา > ธารโต > คีรีเขต > 95150', 'Yala > Than To > Khiri Khet > 95150'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'ละแอ', 'La-Ae', '95120', 'ยะลา > ยะหา > ละแอ > 95120', 'Yala > Yaha > La-Ae > 95120'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'ปะแต', 'Patae', '95120', 'ยะลา > ยะหา > ปะแต > 95120', 'Yala > Yaha > Patae > 95120'),
  ('ยะลา', 'Yala', 'ธารโต', 'Than To', 'ธารโต', 'Than To', '95150', 'ยะลา > ธารโต > ธารโต > 95150', 'Yala > Than To > Than To > 95150'),
  ('ยะลา', 'Yala', 'ธารโต', 'Than To', 'แม่หวาด', 'Mae Wat', '95170', 'ยะลา > ธารโต > แม่หวาด > 95170', 'Yala > Than To > Mae Wat > 95170'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'บาโร๊ะ', 'Baro', '95120', 'ยะลา > ยะหา > บาโร๊ะ > 95120', 'Yala > Yaha > Baro > 95120'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'ตาชี', 'Ta Chi', '95120', 'ยะลา > ยะหา > ตาชี > 95120', 'Yala > Yaha > Ta Chi > 95120'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'บาโงยซิแน', 'Ba-Ngoi Sinae', '95120', 'ยะลา > ยะหา > บาโงยซิแน > 95120', 'Yala > Yaha > Ba-Ngoi Sinae > 95120'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'กายูบอเกาะ', 'Kayu Boko', '95140', 'ยะลา > รามัน > กายูบอเกาะ > 95140', 'Yala > Raman > Kayu Boko > 95140'),
  ('ยะลา', 'Yala', 'ยะหา', 'Yaha', 'กาตอง', 'Katong', '95120', 'ยะลา > ยะหา > กาตอง > 95120', 'Yala > Yaha > Katong > 95120'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'เกะรอ', 'Ke Ro', '95140', 'ยะลา > รามัน > เกะรอ > 95140', 'Yala > Raman > Ke Ro > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'โกตาบารู', 'Kota Baru', '95140', 'ยะลา > รามัน > โกตาบารู > 95140', 'Yala > Raman > Kota Baru > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'กาลอ', 'Kalo', '95140', 'ยะลา > รามัน > กาลอ > 95140', 'Yala > Raman > Kalo > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'กาลูปัง', 'Kalupang', '95140', 'ยะลา > รามัน > กาลูปัง > 95140', 'Yala > Raman > Kalupang > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'กอตอตือร๊ะ', 'Koto Tuera', '95140', 'ยะลา > รามัน > กอตอตือร๊ะ > 95140', 'Yala > Raman > Koto Tuera > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'จะกว๊ะ', 'Cha Kwua', '95140', 'ยะลา > รามัน > จะกว๊ะ > 95140', 'Yala > Raman > Cha Kwua > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'ท่าธง', 'Tha Thong', '95140', 'ยะลา > รามัน > ท่าธง > 95140', 'Yala > Raman > Tha Thong > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'ยะต๊ะ', 'Yata', '95140', 'ยะลา > รามัน > ยะต๊ะ > 95140', 'Yala > Raman > Yata > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'บาโงย', 'Ba-Ngoi', '95140', 'ยะลา > รามัน > บาโงย > 95140', 'Yala > Raman > Ba-Ngoi > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'อาซ่อง', 'A Song', '95140', 'ยะลา > รามัน > อาซ่อง > 95140', 'Yala > Raman > A Song > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'บาลอ', 'Balo', '95140', 'ยะลา > รามัน > บาลอ > 95140', 'Yala > Raman > Balo > 95140'),
  ('ยะลา', 'Yala', 'กาบัง', 'Kabang', 'กาบัง', 'Kabang', '95120', 'ยะลา > กาบัง > กาบัง > 95120', 'Yala > Kabang > Kabang > 95120'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'วังพญา', 'Wang Phaya', '95140', 'ยะลา > รามัน > วังพญา > 95140', 'Yala > Raman > Wang Phaya > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'ตะโล๊ะหะลอ', 'Talo Halo', '95140', 'ยะลา > รามัน > ตะโล๊ะหะลอ > 95140', 'Yala > Raman > Talo Halo > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'เนินงาม', 'Noen Ngam', '95140', 'ยะลา > รามัน > เนินงาม > 95140', 'Yala > Raman > Noen Ngam > 95140'),
  ('ยะลา', 'Yala', 'รามัน', 'Raman', 'บือมัง', 'Buemang', '95140', 'ยะลา > รามัน > บือมัง > 95140', 'Yala > Raman > Buemang > 95140'),
  ('ยะลา', 'Yala', 'กาบัง', 'Kabang', 'บาละ', 'Bala', '95120', 'ยะลา > กาบัง > บาละ > 95120', 'Yala > Kabang > Bala > 95120'),
  ('ยะลา', 'Yala', 'กรงปีนัง', 'Krong Pinang', 'สะเอะ', 'Sa-Ae', '95000', 'ยะลา > กรงปีนัง > สะเอะ > 95000', 'Yala > Krong Pinang > Sa-Ae > 95000'),
  ('ยะลา', 'Yala', 'กรงปีนัง', 'Krong Pinang', 'กรงปินัง', 'Krong Pinang', '95000', 'ยะลา > กรงปีนัง > กรงปินัง > 95000', 'Yala > Krong Pinang > Krong Pinang > 95000'),
  ('ยะลา', 'Yala', 'กรงปีนัง', 'Krong Pinang', 'ปุโรง', 'Pu Rong', '95000', 'ยะลา > กรงปีนัง > ปุโรง > 95000', 'Yala > Krong Pinang > Pu Rong > 95000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'ลำภู', 'Lamphu', '96000', 'นราธิวาส > เมืองนราธิวาส > ลำภู > 96000', 'Narathiwat > Mueang Narathiwat > Lamphu > 96000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'บางปอ', 'Bang Po', '96000', 'นราธิวาส > เมืองนราธิวาส > บางปอ > 96000', 'Narathiwat > Mueang Narathiwat > Bang Po > 96000'),
  ('ยะลา', 'Yala', 'กรงปีนัง', 'Krong Pinang', 'ห้วยกระทิง', 'Huai Krathing', '95000', 'ยะลา > กรงปีนัง > ห้วยกระทิง > 95000', 'Yala > Krong Pinang > Huai Krathing > 95000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'กะลุวอ', 'Kaluwo', '96000', 'นราธิวาส > เมืองนราธิวาส > กะลุวอ > 96000', 'Narathiwat > Mueang Narathiwat > Kaluwo > 96000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'บางนาค', 'Bang Nak', '96000', 'นราธิวาส > เมืองนราธิวาส > บางนาค > 96000', 'Narathiwat > Mueang Narathiwat > Bang Nak > 96000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'มะนังตายอ', 'Manang Tayo', '96000', 'นราธิวาส > เมืองนราธิวาส > มะนังตายอ > 96000', 'Narathiwat > Mueang Narathiwat > Manang Tayo > 96000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'โคกเคียน', 'Khok Khian', '96000', 'นราธิวาส > เมืองนราธิวาส > โคกเคียน > 96000', 'Narathiwat > Mueang Narathiwat > Khok Khian > 96000'),
  ('นราธิวาส', 'Narathiwat', 'เมืองนราธิวาส', 'Mueang Narathiwat', 'กะลุวอเหนือ', 'Kaluwo Nuea', '96000', 'นราธิวาส > เมืองนราธิวาส > กะลุวอเหนือ > 96000', 'Narathiwat > Mueang Narathiwat > Kaluwo Nuea > 96000'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'นานาค', 'Na Nak', '96110', 'นราธิวาส > ตากใบ > นานาค > 96110', 'Narathiwat > Tak Bai > Na Nak > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'บางขุนทอง', 'Bang Khun Thong', '96110', 'นราธิวาส > ตากใบ > บางขุนทอง > 96110', 'Narathiwat > Tak Bai > Bang Khun Thong > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'พร่อน', 'Phron', '96110', 'นราธิวาส > ตากใบ > พร่อน > 96110', 'Narathiwat > Tak Bai > Phron > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'เจ๊ะเห', 'Che He', '96110', 'นราธิวาส > ตากใบ > เจ๊ะเห > 96110', 'Narathiwat > Tak Bai > Che He > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'โฆษิต', 'Khosit', '96110', 'นราธิวาส > ตากใบ > โฆษิต > 96110', 'Narathiwat > Tak Bai > Khosit > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'ไพรวัน', 'Phrai Wan', '96110', 'นราธิวาส > ตากใบ > ไพรวัน > 96110', 'Narathiwat > Tak Bai > Phrai Wan > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'ศาลาใหม่', 'Sala Mai', '96110', 'นราธิวาส > ตากใบ > ศาลาใหม่ > 96110', 'Narathiwat > Tak Bai > Sala Mai > 96110'),
  ('นราธิวาส', 'Narathiwat', 'ตากใบ', 'Tak Bai', 'เกาะสะท้อน', 'Ko Sathon', '96110', 'นราธิวาส > ตากใบ > เกาะสะท้อน > 96110', 'Narathiwat > Tak Bai > Ko Sathon > 96110'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'ปะลุกาสาเมาะ', 'Paluka Samo', '96170', 'นราธิวาส > บาเจาะ > ปะลุกาสาเมาะ > 96170', 'Narathiwat > Tak Bai > Paluka Samo > 96170'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'ลุโบะสาวอ', 'Lubo Sawo', '96170', 'นราธิวาส > บาเจาะ > ลุโบะสาวอ > 96170', 'Narathiwat > Tak Bai > Lubo Sawo > 96170'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'บาเจาะ', 'Bacho', '96170', 'นราธิวาส > บาเจาะ > บาเจาะ > 96170', 'Narathiwat > Tak Bai > Bacho > 96170'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'กาเยาะมาตี', 'Kayo Mati', '96170', 'นราธิวาส > บาเจาะ > กาเยาะมาตี > 96170', 'Narathiwat > Tak Bai > Kayo Mati > 96170'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'ลุโบะบายะ', 'Lubo Baya', '96180', 'นราธิวาส > ยี่งอ > ลุโบะบายะ > 96180', 'Narathiwat > Yi-ngo > Lubo Baya > 96180'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'ยี่งอ', 'Yi-Ngo', '96180', 'นราธิวาส > ยี่งอ > ยี่งอ > 96180', 'Narathiwat > Yi-ngo > Yi-Ngo > 96180'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'บาเระใต้', 'Bare Tai', '96170', 'นราธิวาส > บาเจาะ > บาเระใต้ > 96170', 'Narathiwat > Tak Bai > Bare Tai > 96170'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'จอเบาะ', 'Cho Bo', '96180', 'นราธิวาส > ยี่งอ > จอเบาะ > 96180', 'Narathiwat > Yi-ngo > Cho Bo > 96180'),
  ('นราธิวาส', 'Narathiwat', 'บาเจาะ', 'Tak Bai', 'บาเระเหนือ', 'Bare Nuea', '96170', 'นราธิวาส > บาเจาะ > บาเระเหนือ > 96170', 'Narathiwat > Tak Bai > Bare Nuea > 96170'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'ละหาร', 'Lahan', '96180', 'นราธิวาส > ยี่งอ > ละหาร > 96180', 'Narathiwat > Yi-ngo > Lahan > 96180'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'ตันหยงลิมอ', 'Tanyong Limo', '96130', 'นราธิวาส > ระแงะ > ตันหยงลิมอ > 96130', 'Narathiwat > Ra-ngae > Tanyong Limo > 96130'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'ตันหยงมัส', 'Tanyong Mat', '96130', 'นราธิวาส > ระแงะ > ตันหยงมัส > 96130', 'Narathiwat > Ra-ngae > Tanyong Mat > 96130'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'ตะปอเยาะ', 'Tapo Yo', '96180', 'นราธิวาส > ยี่งอ > ตะปอเยาะ > 96180', 'Narathiwat > Yi-ngo > Tapo Yo > 96180'),
  ('นราธิวาส', 'Narathiwat', 'ยี่งอ', 'Yi-ngo', 'ลุโบะบือซา', 'Lubo Buesa', '96180', 'นราธิวาส > ยี่งอ > ลุโบะบือซา > 96180', 'Narathiwat > Yi-ngo > Lubo Buesa > 96180'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'บองอ', 'Bo-Ngo', '96220', 'นราธิวาส > ระแงะ > บองอ > 96220', 'Narathiwat > Ra-ngae > Bo-Ngo > 96220'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'บาโงสะโต', 'Ba-Ngo Sato', '96130', 'นราธิวาส > ระแงะ > บาโงสะโต > 96130', 'Narathiwat > Ra-ngae > Ba-Ngo Sato > 96130'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'เฉลิม', 'Chaloem', '96130', 'นราธิวาส > ระแงะ > เฉลิม > 96130', 'Narathiwat > Ra-ngae > Chaloem > 96130'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'รือเสาะ', 'Rueso', '96150', 'นราธิวาส > รือเสาะ > รือเสาะ > 96150', 'Narathiwat > Rueso > Rueso > 96150'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'กาลิชา', 'Kalisa', '96130', 'นราธิวาส > ระแงะ > กาลิชา > 96130', 'Narathiwat > Ra-ngae > Kalisa > 96130'),
  ('นราธิวาส', 'Narathiwat', 'ระแงะ', 'Ra-ngae', 'มะรือโบตก', 'Marue Bo Tok', '96130', 'นราธิวาส > ระแงะ > มะรือโบตก > 96130', 'Narathiwat > Ra-ngae > Marue Bo Tok > 96130'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'สาวอ', 'Sawo', '96150', 'นราธิวาส > รือเสาะ > สาวอ > 96150', 'Narathiwat > Rueso > Sawo > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'เรียง', 'Riang', '96150', 'นราธิวาส > รือเสาะ > เรียง > 96150', 'Narathiwat > Rueso > Riang > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'สามัคคี', 'Samakkhi', '96150', 'นราธิวาส > รือเสาะ > สามัคคี > 96150', 'Narathiwat > Rueso > Samakkhi > 96150'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'ซากอ', 'Sa Ko', '96210', 'นราธิวาส > ศรีสาคร > ซากอ > 96210', 'Narathiwat > Si Sakhon > Sa Ko > 96210'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'ตะมะยูง', 'Tama Yung', '96210', 'นราธิวาส > ศรีสาคร > ตะมะยูง > 96210', 'Narathiwat > Si Sakhon > Tama Yung > 96210'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'รือเสาะออก', 'Rueso Ok', '96150', 'นราธิวาส > รือเสาะ > รือเสาะออก > 96150', 'Narathiwat > Rueso > Rueso Ok > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'สุวารี', 'Suwari', '96150', 'นราธิวาส > รือเสาะ > สุวารี > 96150', 'Narathiwat > Rueso > Suwari > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'ลาโละ', 'La Lo', '96150', 'นราธิวาส > รือเสาะ > ลาโละ > 96150', 'Narathiwat > Rueso > La Lo > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'บาตง', 'Batong', '96150', 'นราธิวาส > รือเสาะ > บาตง > 96150', 'Narathiwat > Rueso > Batong > 96150'),
  ('นราธิวาส', 'Narathiwat', 'รือเสาะ', 'Rueso', 'โคกสะตอ', 'Khok Sato', '96150', 'นราธิวาส > รือเสาะ > โคกสะตอ > 96150', 'Narathiwat > Rueso > Khok Sato > 96150'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'ศรีบรรพต', 'Si Banphot', '96210', 'นราธิวาส > ศรีสาคร > ศรีบรรพต > 96210', 'Narathiwat > Si Sakhon > Si Banphot > 96210'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'กาหลง', 'Kalong', '96210', 'นราธิวาส > ศรีสาคร > กาหลง > 96210', 'Narathiwat > Si Sakhon > Kalong > 96210'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'ศรีสาคร', 'Si Sakhon', '96210', 'นราธิวาส > ศรีสาคร > ศรีสาคร > 96210', 'Narathiwat > Si Sakhon > Si Sakhon > 96210'),
  ('นราธิวาส', 'Narathiwat', 'ศรีสาคร', 'Si Sakhon', 'เชิงคีรี', 'Choeng Khiri', '96210', 'นราธิวาส > ศรีสาคร > เชิงคีรี > 96210', 'Narathiwat > Si Sakhon > Choeng Khiri > 96210'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'เอราวัณ', 'Erawan', '96160', 'นราธิวาส > แว้ง > เอราวัณ > 96160', 'Narathiwat > Waeng > Erawan > 96160'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'แว้ง', 'Waeng', '96160', 'นราธิวาส > แว้ง > แว้ง > 96160', 'Narathiwat > Waeng > Waeng > 96160'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'ฆอเลาะ', 'Kho Lo', '96160', 'นราธิวาส > แว้ง > ฆอเลาะ > 96160', 'Narathiwat > Waeng > Kho Lo > 96160'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'กายูคละ', 'Kayu Khla', '96160', 'นราธิวาส > แว้ง > กายูคละ > 96160', 'Narathiwat > Waeng > Kayu Khla > 96160'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'โละจูด', 'Lo Chut', '96160', 'นราธิวาส > แว้ง > โละจูด > 96160', 'Narathiwat > Waeng > Lo Chut > 96160'),
  ('นราธิวาส', 'Narathiwat', 'แว้ง', 'Waeng', 'แม่ดง', 'Mae Dong', '96160', 'นราธิวาส > แว้ง > แม่ดง > 96160', 'Narathiwat > Waeng > Mae Dong > 96160'),
  ('นราธิวาส', 'Narathiwat', 'สุคิริน', 'Sukhirin', 'ภูเขาทอง', 'Phu Khao Thong', '96190', 'นราธิวาส > สุคิริน > ภูเขาทอง > 96190', 'Narathiwat > Sukhirin > Phu Khao Thong > 96190'),
  ('นราธิวาส', 'Narathiwat', 'สุคิริน', 'Sukhirin', 'สุคิริน', 'Sukhirin', '96190', 'นราธิวาส > สุคิริน > สุคิริน > 96190', 'Narathiwat > Sukhirin > Sukhirin > 96190'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงโก-ลก', 'Su-ngai Kolok', 'ป่าเสมัส', 'Pa Semat', '96120', 'นราธิวาส > สุไหงโก-ลก > ป่าเสมัส > 96120', 'Narathiwat > Su-ngai Kolok > Pa Semat > 96120'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงโก-ลก', 'Su-ngai Kolok', 'สุไหงโกลก', 'Su-Ngai Ko-Lok', '96120', 'นราธิวาส > สุไหงโก-ลก > สุไหงโกลก > 96120', 'Narathiwat > Su-ngai Kolok > Su-Ngai Ko-Lok > 96120'),
  ('นราธิวาส', 'Narathiwat', 'สุคิริน', 'Sukhirin', 'มาโมง', 'Ma Mong', '96190', 'นราธิวาส > สุคิริน > มาโมง > 96190', 'Narathiwat > Sukhirin > Ma Mong > 96190'),
  ('นราธิวาส', 'Narathiwat', 'สุคิริน', 'Sukhirin', 'ร่มไทร', 'Rom Sai', '96190', 'นราธิวาส > สุคิริน > ร่มไทร > 96190', 'Narathiwat > Sukhirin > Rom Sai > 96190'),
  ('นราธิวาส', 'Narathiwat', 'สุคิริน', 'Sukhirin', 'เกียร์', 'Kia', '96190', 'นราธิวาส > สุคิริน > เกียร์ > 96190', 'Narathiwat > Sukhirin > Kia > 96190'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงโก-ลก', 'Su-ngai Kolok', 'มูโนะ', 'Mu No', '96120', 'นราธิวาส > สุไหงโก-ลก > มูโนะ > 96120', 'Narathiwat > Su-ngai Kolok > Mu No > 96120'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงโก-ลก', 'Su-ngai Kolok', 'ปูโยะ', 'Puyo', '96120', 'นราธิวาส > สุไหงโก-ลก > ปูโยะ > 96120', 'Narathiwat > Su-ngai Kolok > Puyo > 96120'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'ปะลุรู', 'Paluru', '96140', 'นราธิวาส > สุไหงปาดี > ปะลุรู > 96140', 'Narathiwat > Su-ngai Padi > Paluru > 96140'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'สุไหงปาดี', 'Su-Ngai Padi', '96140', 'นราธิวาส > สุไหงปาดี > สุไหงปาดี > 96140', 'Narathiwat > Su-ngai Padi > Su-Ngai Padi > 96140'),
  ('นราธิวาส', 'Narathiwat', 'จะแนะ', 'Chanae', 'จะแนะ', 'Chanae', '96220', 'นราธิวาส > จะแนะ > จะแนะ > 96220', 'Narathiwat > Chanae > Chanae > 96220'),
  ('นราธิวาส', 'Narathiwat', 'จะแนะ', 'Chanae', 'ดุซงญอ', 'Du Song Yo', '96220', 'นราธิวาส > จะแนะ > ดุซงญอ > 96220', 'Narathiwat > Chanae > Du Song Yo > 96220'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'ริโก๋', 'Ri Ko', '96140', 'นราธิวาส > สุไหงปาดี > ริโก๋ > 96140', 'Narathiwat > Su-ngai Padi > Ri Ko > 96140'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'โต๊ะเด็ง', 'To Deng', '96140', 'นราธิวาส > สุไหงปาดี > โต๊ะเด็ง > 96140', 'Narathiwat > Su-ngai Padi > To Deng > 96140'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'สากอ', 'Sako', '96140', 'นราธิวาส > สุไหงปาดี > สากอ > 96140', 'Narathiwat > Su-ngai Padi > Sako > 96140'),
  ('นราธิวาส', 'Narathiwat', 'สุไหงปาดี', 'Su-ngai Padi', 'กาวะ', 'Kawa', '96140', 'นราธิวาส > สุไหงปาดี > กาวะ > 96140', 'Narathiwat > Su-ngai Padi > Kawa > 96140'),
  ('นราธิวาส', 'Narathiwat', 'จะแนะ', 'Chanae', 'ผดุงมาตร', 'Phadung Mat', '96220', 'นราธิวาส > จะแนะ > ผดุงมาตร > 96220', 'Narathiwat > Chanae > Phadung Mat > 96220'),
  ('นราธิวาส', 'Narathiwat', 'จะแนะ', 'Chanae', 'ช้างเผือก', 'Chang Phueak', '96220', 'นราธิวาส > จะแนะ > ช้างเผือก > 96220', 'Narathiwat > Chanae > Chang Phueak > 96220'),
  ('นราธิวาส', 'Narathiwat', 'เจาะไอร้อง', 'Cho-airong', 'จวบ', 'Chuap', '96130', 'นราธิวาส > เจาะไอร้อง > จวบ > 96130', 'Narathiwat > Cho-airong > Chuap > 96130'),
  ('กรุงเทพมหานคร', 'Bangkok', 'ธนบุรี', 'Thon Buri', 'ดาวคะนอง', 'Dawkanong', '10600', 'กรุงเทพมหานคร > ธนบุรี > ดาวคะนอง > 10600', 'Bangkok > Thon Buri > Dawkanong > 10600'),
  ('นราธิวาส', 'Narathiwat', 'เจาะไอร้อง', 'Cho-airong', 'มะรือโบออก', 'Marue Bo Ok', '96130', 'นราธิวาส > เจาะไอร้อง > มะรือโบออก > 96130', 'Narathiwat > Cho-airong > Marue Bo Ok > 96130'),
  ('นราธิวาส', 'Narathiwat', 'เจาะไอร้อง', 'Cho-airong', 'บูกิต', 'Bu Kit', '96130', 'นราธิวาส > เจาะไอร้อง > บูกิต > 96130', 'Narathiwat > Cho-airong > Bu Kit > 96130'),
  ('กรุงเทพมหานคร', 'Bangkok', 'จตุจักร', 'Chatuchak', 'เสนานิคม', 'Sananikom', '10900', 'กรุงเทพมหานคร > จตุจักร > เสนานิคม > 10900', 'Bangkok > Chatuchak > Sananikom > 10900'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บางซื่อ', 'Bang Su', 'วงศ์สว่าง', 'Wongsawang', '10800', 'กรุงเทพมหานคร > บางซื่อ > วงศ์สว่าง > 10800', 'Bangkok > Bang Su > Wongsawang > 10800'),
  ('กรุงเทพมหานคร', 'Bangkok', 'จตุจักร', 'Chatuchak', 'จันทรเกษม', 'Chankaseam', '10900', 'กรุงเทพมหานคร > จตุจักร > จันทรเกษม > 10900', 'Bangkok > Chatuchak > Chankaseam > 10900'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บึงกุ่ม', 'Bung Kum', 'นวมินทร์', 'Nawamin', '10240', 'กรุงเทพมหานคร > บึงกุ่ม > นวมินทร์ > 10240', 'Bangkok > Bung Kum > Nawamin > 10240'),
  ('กรุงเทพมหานคร', 'Bangkok', 'ธนบุรี', 'Thon Buri', 'สำเหร่', 'Samlea', '10600', 'กรุงเทพมหานคร > ธนบุรี > สำเหร่ > 10600', 'Bangkok > Thon Buri > Samlea > 10600'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บึงกุ่ม', 'Bung Kum', 'นวลจันทร์', 'Nualchan', '10240', 'กรุงเทพมหานคร > บึงกุ่ม > นวลจันทร์ > 10240', 'Bangkok > Bung Kum > Nualchan > 10240'),
  ('กรุงเทพมหานคร', 'Bangkok', 'จตุจักร', 'Chatuchak', 'จอมพล', 'Jompol', '10900', 'กรุงเทพมหานคร > จตุจักร > จอมพล > 10900', 'Bangkok > Chatuchak > Jompol > 10900'),
  ('กรุงเทพมหานคร', 'Bangkok', 'จตุจักร', 'Chatuchak', 'จตุจักร', 'Jatujak', '10900', 'กรุงเทพมหานคร > จตุจักร > จตุจักร > 10900', 'Bangkok > Chatuchak > Jatujak > 10900'),
  ('กรุงเทพมหานคร', 'Bangkok', 'วังทองหลาง', 'Wang Thong Lang', 'สะพานสอง', 'Sapansong', '10310', 'กรุงเทพมหานคร > วังทองหลาง > สะพานสอง > 10310', 'Bangkok > Wang Thong Lang > Sapansong > 10310'),
  ('กรุงเทพมหานคร', 'Bangkok', 'คันนายาว', 'Khanna Yao', 'รามอินทรา', 'Ram Intra', '10230', 'กรุงเทพมหานคร > คันนายาว > รามอินทรา > 10230', 'Bangkok > Khanna Yao > Ram Intra > 10230'),
  ('กรุงเทพมหานคร', 'Bangkok', 'ดอนเมือง', 'Don Mueang', 'ดอนเมือง', 'Donmuang', '10210', 'กรุงเทพมหานคร > ดอนเมือง > ดอนเมือง > 10210', 'Bangkok > Don Mueang > Donmuang > 10210'),
  ('กรุงเทพมหานคร', 'Bangkok', 'วังทองหลาง', 'Wang Thong Lang', 'คลองเจ้าคุณสิงห์', 'Klongjaokhunsing', '10310', 'กรุงเทพมหานคร > วังทองหลาง > คลองเจ้าคุณสิงห์ > 10310', 'Bangkok > Wang Thong Lang > Klongjaokhunsing > 10310'),
  ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'บางไทร', 'Bang Sai', 'โพแตง', 'Photeang', '13290', 'พระนครศรีอยุธยา > บางไทร > โพแตง > 13290', 'Phra Nakhon Si Ayutthaya > Bang Sai > Photeang > 13290'),
  ('กรุงเทพมหานคร', 'Bangkok', 'ดอนเมือง', 'Don Mueang', 'สนามบิน', 'Sanambin', '10210', 'กรุงเทพมหานคร > ดอนเมือง > สนามบิน > 10210', 'Bangkok > Don Mueang > Sanambin > 10210'),
  ('กรุงเทพมหานคร', 'Bangkok', 'วังทองหลาง', 'Wang Thong Lang', 'พลับพลา', 'Plabpla', '10310', 'กรุงเทพมหานคร > วังทองหลาง > พลับพลา > 10310', 'Bangkok > Wang Thong Lang > Plabpla > 10310'),
  ('ลพบุรี', 'Lop Buri', 'ท่าวุ้ง', 'Tha Wung', 'บ้านเบิก', 'Banberk', '15150', 'ลพบุรี > ท่าวุ้ง > บ้านเบิก > 15150', 'Lop Buri > Tha Wung > Banberk > 15150'),
  ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'บางปะอิน', 'Bang Pa-in', 'ตลาดเกรียบ', 'Taladkleab', '13160', 'พระนครศรีอยุธยา > บางปะอิน > ตลาดเกรียบ > 13160', 'Phra Nakhon Si Ayutthaya > Bang Pa-in > Taladkleab > 13160'),
  ('สระบุรี', 'Saraburi', 'พระพุทธบาท', 'Phra Phutthabat', 'หนองแก', 'Nhongkea', '18120', 'สระบุรี > พระพุทธบาท > หนองแก > 18120', 'Saraburi > Phra Phutthabat > Nhongkea > 18120'),
  ('ลพบุรี', 'Lop Buri', 'บ้านหมี่', 'Ban Mi', 'เชียงงา', 'Chiangnga', '15110', 'ลพบุรี > บ้านหมี่ > เชียงงา > 15110', 'Lop Buri > Ban Mi > Chiangnga > 15110'),
  ('สระบุรี', 'Saraburi', 'หนองแซง', 'Nong Saeng', 'เขาดิน', 'Khaodin', '18170', 'สระบุรี > หนองแซง > เขาดิน > 18170', 'Saraburi > Nong Saeng > Khaodin > 18170'),
  ('ลพบุรี', 'Lop Buri', 'บ้านหมี่', 'Ban Mi', 'บ้านหมี่', 'Banmee', '15110', 'ลพบุรี > บ้านหมี่ > บ้านหมี่ > 15110', 'Lop Buri > Ban Mi > Banmee > 15110'),
  ('นครราชสีมา', 'Nakhon Ratchasima', 'เมืองนครราชสีมา', 'Mueang Nakhon Ratchasima', 'ในเมือง', 'Naimuang', '30000', 'นครราชสีมา > เมืองนครราชสีมา > ในเมือง > 30000', 'Nakhon Ratchasima > Mueang Nakhon Ratchasima > Naimuang > 30000'),
  ('ระยอง', 'Rayong', 'เมืองระยอง', 'Mueang Rayong', 'ปากน้ำ', 'Paknam', '21000', 'ระยอง > เมืองระยอง > ปากน้ำ > 21000', 'Rayong > Mueang Rayong > Paknam > 21000'),
  ('ปราจีนบุรี', 'Prachin Buri', 'เมืองปราจีนบุรี', 'Mueang Prachin Buri', 'ไม้เค็ด', 'Maiked', '25230', 'ปราจีนบุรี > เมืองปราจีนบุรี > ไม้เค็ด > 25230', 'Prachin Buri > Mueang Prachin Buri > Maiked > 25230'),
  ('ชลบุรี', 'Chon Buri', 'พนัสนิคม', 'Phanat Nikhom', 'นามะตูม', 'Namatoom', '20140', 'ชลบุรี > พนัสนิคม > นามะตูม > 20140', 'Chon Buri > Phanat Nikhom > Namatoom > 20140'),
  ('ระยอง', 'Rayong', 'เมืองระยอง', 'Mueang Rayong', 'ห้วยโป่ง', 'Huaypong', '21150', 'ระยอง > เมืองระยอง > ห้วยโป่ง > 21150', 'Rayong > Mueang Rayong > Huaypong > 21150'),
  ('ตราด', 'Trat', 'เมืองตราด', 'Mueang Trat', 'บางพระ', 'Bangpha', '23000', 'ตราด > เมืองตราด > บางพระ > 23000', 'Trat > Mueang Trat > Bangpha > 23000'),
  ('ศรีสะเกษ', 'Si Sa Ket', 'เมืองศรีสะเกษ', 'Mueang Si Sa Ket', 'โพนเขวา', 'Pon Kewa', '33000', 'ศรีสะเกษ > เมืองศรีสะเกษ > โพนเขวา > 33000', 'Si Sa Ket > Mueang Si Sa Ket > Pon Kewa > 33000'),
  ('นครราชสีมา', 'Nakhon Ratchasima', 'โนนแดง', 'Non Daeng', 'โนนแดง', 'Noen Deang', '30360', 'นครราชสีมา > โนนแดง > โนนแดง > 30360', 'Nakhon Ratchasima > Non Daeng > Noen Deang > 30360'),
  ('ศรีสะเกษ', 'Si Sa Ket', 'เมืองศรีสะเกษ', 'Mueang Si Sa Ket', 'เมืองใต้', 'Muang Tai', '33000', 'ศรีสะเกษ > เมืองศรีสะเกษ > เมืองใต้ > 33000', 'Si Sa Ket > Mueang Si Sa Ket > Muang Tai > 33000'),
  ('อุดรธานี', 'Udon Thani', 'เมืองอุดรธานี', 'Mueang Udon Thani', 'นาข่า', 'Na Kha', '41000', 'อุดรธานี > เมืองอุดรธานี > นาข่า > 41000', 'Udon Thani > Mueang Udon Thani > Na Kha > 41000'),
  ('นครราชสีมา', 'Nakhon Ratchasima', 'เมืองนครราชสีมา', 'Mueang Nakhon Ratchasima', 'บ้านใหม่', 'Banmai', '30000', 'นครราชสีมา > เมืองนครราชสีมา > บ้านใหม่ > 30000', 'Nakhon Ratchasima > Mueang Nakhon Ratchasima > Banmai > 30000'),
  ('นครราชสีมา', 'Nakhon Ratchasima', 'สูงเนิน', 'Sung Noen', 'กุดจิก', 'Kudjik', '30380', 'นครราชสีมา > สูงเนิน > กุดจิก > 30380', 'Nakhon Ratchasima > Sung Noen > Kudjik > 30380'),
  ('ร้อยเอ็ด', 'Roi Et', 'อาจสามารถ', 'At Samat', 'บ้านดู่', 'Bandu', '45160', 'ร้อยเอ็ด > อาจสามารถ > บ้านดู่ > 45160', 'Roi Et > At Samat > Bandu > 45160'),
  ('นครพนม', 'Nakhon Phanom', 'บ้านแพง', 'Ban Phaeng', 'นาเข', 'Nakea', '48140', 'นครพนม > บ้านแพง > นาเข > 48140', 'Nakhon Phanom > Ban Phaeng > Nakea > 48140'),
  ('นครพนม', 'Nakhon Phanom', 'โพนสวรรค์', 'Phon Sawan', 'โพนบก', 'Phonbok', '48190', 'นครพนม > โพนสวรรค์ > โพนบก > 48190', 'Nakhon Phanom > Phon Sawan > Phonbok > 48190'),
  ('มุกดาหาร', 'Mukdahan', 'คำชะอี', 'Khamcha-i', 'บ้านซ่ง', 'Bansong', '49110', 'มุกดาหาร > คำชะอี > บ้านซ่ง > 49110', 'Mukdahan > Khamcha-i > Bansong > 49110'),
  ('กาฬสินธุ์', 'Kalasin', 'สหัสขันธ์', 'Sahatsakhan', 'ภูสิงห์', 'Phusing', '46140', 'กาฬสินธุ์ > สหัสขันธ์ > ภูสิงห์ > 46140', 'Kalasin > Sahatsakhan > Phusing > 46140'),
  ('นครพนม', 'Nakhon Phanom', 'โพนสวรรค์', 'Phon Sawan', 'นาใน', 'Nanai', '48190', 'นครพนม > โพนสวรรค์ > นาใน > 48190', 'Nakhon Phanom > Phon Sawan > Nanai > 48190'),
  ('เชียงใหม่', 'Chiang Mai', 'แม่แตง', 'Mae Taeng', 'สมก๋าย', 'Somkai', '50150', 'เชียงใหม่ > แม่แตง > สมก๋าย > 50150', 'Chiang Mai > Mae Taeng > Somkai > 50150'),
  ('นครพนม', 'Nakhon Phanom', 'เมืองนครพนม', 'Mueang Nakhon Phanom', 'หนองแสง', 'Nhongseang', '48000', 'นครพนม > เมืองนครพนม > หนองแสง > 48000', 'Nakhon Phanom > Mueang Nakhon Phanom > Nhongseang > 48000'),
  ('เชียงใหม่', 'Chiang Mai', 'ฝาง', 'Fang', 'แม่สูน', 'Measoon', '50110', 'เชียงใหม่ > ฝาง > แม่สูน > 50110', 'Chiang Mai > Fang > Measoon > 50110'),
  ('เชียงใหม่', 'Chiang Mai', 'ฝาง', 'Fang', 'แม่ข่า', 'Meakha', '50320', 'เชียงใหม่ > ฝาง > แม่ข่า > 50320', 'Chiang Mai > Fang > Meakha > 50320'),
  ('เชียงใหม่', 'Chiang Mai', 'แม่อาย', 'Mae Ai', 'มะลิกา', 'Malika', '50280', 'เชียงใหม่ > แม่อาย > มะลิกา > 50280', 'Chiang Mai > Mae Ai > Malika > 50280'),
  ('เชียงใหม่', 'Chiang Mai', 'สันทราย', 'San Sai', 'แม่แฝก', 'Meafeak', '50290', 'เชียงใหม่ > สันทราย > แม่แฝก > 50290', 'Chiang Mai > San Sai > Meafeak > 50290'),
  ('เชียงราย', 'Chiang Rai', 'เมืองเชียงราย', 'Mueang Chiang Rai', 'ท่าสุด', 'Thasud', '57100', 'เชียงราย > เมืองเชียงราย > ท่าสุด > 57100', 'Chiang Rai > Mueang Chiang Rai > Thasud > 57100'),
  ('ตาก', 'Tak', 'เมืองตาก', 'Mueang Tak', 'เชียงเงิน', 'Chiangngean', '63000', 'ตาก > เมืองตาก > เชียงเงิน > 63000', 'Tak > Mueang Tak > Chiangngean > 63000'),
  ('อุทัยธานี', 'Uthai Thani', 'หนองขาหย่าง', 'Nong Khayang', 'หลุมเข้า', 'Hlumkao', '61130', 'อุทัยธานี > หนองขาหย่าง > หลุมเข้า > 61130', 'Uthai Thani > Nong Khayang > Hlumkao > 61130'),
  ('ลำปาง', 'Lampang', 'เมืองลำปาง', 'Mueang Lampang', 'สวนดอก', 'Suandok', '52100', 'ลำปาง > เมืองลำปาง > สวนดอก > 52100', 'Lampang > Mueang Lampang > Suandok > 52100'),
  ('แม่ฮ่องสอน', 'Mae Hong Son', 'เมืองแม่ฮ่องสอน', 'Mueang Mae Hong Son', 'ห้วยผา', 'Huaypha', '58000', 'แม่ฮ่องสอน > เมืองแม่ฮ่องสอน > ห้วยผา > 58000', 'Mae Hong Son > Mueang Mae Hong Son > Huaypha > 58000'),
  ('ลำปาง', 'Lampang', 'เมืองลำปาง', 'Mueang Lampang', 'หัวเวียง', 'Huaveang', '52000', 'ลำปาง > เมืองลำปาง > หัวเวียง > 52000', 'Lampang > Mueang Lampang > Huaveang > 52000'),
  ('ลำปาง', 'Lampang', 'เมืองลำปาง', 'Mueang Lampang', 'สบตุ๋ย', 'Sobtui', '52100', 'ลำปาง > เมืองลำปาง > สบตุ๋ย > 52100', 'Lampang > Mueang Lampang > Sobtui > 52100'),
  ('ตาก', 'Tak', 'เมืองตาก', 'Mueang Tak', 'หนองหลวง', 'Nhongluang', '63000', 'ตาก > เมืองตาก > หนองหลวง > 63000', 'Tak > Mueang Tak > Nhongluang > 63000'),
  ('กาญจนบุรี', 'Kanchanaburi', 'เมืองกาญจนบุรี', 'Mueang Kanchanaburi', 'บ้านเหนือ', 'Bannue', '71000', 'กาญจนบุรี > เมืองกาญจนบุรี > บ้านเหนือ > 71000', 'Kanchanaburi > Mueang Kanchanaburi > Bannue > 71000'),
  ('เพชรบูรณ์', 'Phetchabun', 'หล่มสัก', 'Lom Sak', 'หล่มสัก', 'Lomsak', '67110', 'เพชรบูรณ์ > หล่มสัก > หล่มสัก > 67110', 'Phetchabun > Lom Sak > Lomsak > 67110'),
  ('กาญจนบุรี', 'Kanchanaburi', 'เมืองกาญจนบุรี', 'Mueang Kanchanaburi', 'บ้านใต้', 'Bantai', '71000', 'กาญจนบุรี > เมืองกาญจนบุรี > บ้านใต้ > 71000', 'Kanchanaburi > Mueang Kanchanaburi > Bantai > 71000'),
  ('พิจิตร', 'Phichit', 'บางมูลนาก', 'Bang Mun Nak', 'บางมูลนาก', 'Bangmoonnhak', '66120', 'พิจิตร > บางมูลนาก > บางมูลนาก > 66120', 'Phichit > Bang Mun Nak > Bangmoonnhak > 66120'),
  ('ตาก', 'Tak', 'เมืองตาก', 'Mueang Tak', 'หัวเดียด', 'Huadead', '63000', 'ตาก > เมืองตาก > หัวเดียด > 63000', 'Tak > Mueang Tak > Huadead > 63000'),
  ('กระบี่', 'Krabi', 'เมืองกระบี่', 'Mueang Krabi', 'กระบี่ใหญ่', 'Krabiyai', '81000', 'กระบี่ > เมืองกระบี่ > กระบี่ใหญ่ > 81000', 'Krabi > Mueang Krabi > Krabiyai > 81000'),
  ('เพชรบุรี', 'Phetchaburi', 'บ้านลาด', 'Ban Lat', 'สะพานไกร', 'Sapanklai', '76150', 'เพชรบุรี > บ้านลาด > สะพานไกร > 76150', 'Phetchaburi > Ban Lat > Sapanklai > 76150'),
  ('กาญจนบุรี', 'Kanchanaburi', 'บ่อพลอย', 'Bo Phloi', 'หนองกร่าง', 'Nhongklang', '71220', 'กาญจนบุรี > บ่อพลอย > หนองกร่าง > 71220', 'Kanchanaburi > Bo Phloi > Nhongklang > 71220'),
  ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'ปากพนัง', 'Pak Phanang', 'ปากพนัง', 'Pakpanang', '80140', 'นครศรีธรรมราช > ปากพนัง > ปากพนัง > 80140', 'Nakhon Si Thammarat > Pak Phanang > Pakpanang > 80140'),
  ('สุพรรณบุรี', 'Suphan Buri', 'เดิมบางนางบวช', 'Doem Bang Nang Buat', 'ป่าสะแก', 'Pasakea', '72120', 'สุพรรณบุรี > เดิมบางนางบวช > ป่าสะแก > 72120', 'Suphan Buri > Doem Bang Nang Buat > Pasakea > 72120'),
  ('ภูเก็ต', 'Phuket', 'เมืองภูเก็ต', 'Mueang Phuket', 'รัษฎา', 'Ratsada', '83000', 'ภูเก็ต > เมืองภูเก็ต > รัษฎา > 83000', 'Phuket > Mueang Phuket > Ratsada > 83000'),
  ('สุราษฎร์ธานี', 'Surat Thani', 'เกาะพะงัน', 'Ko Pha-ngan', 'เกาะเต่า', 'Kao Tao', '84280', 'สุราษฎร์ธานี > เกาะพะงัน > เกาะเต่า > 84280', 'Surat Thani > Ko Pha-ngan > Kao Tao > 84280'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บางบอน', 'Bang Bon', 'บางบอนเหนือ', 'Bang Bon Nuea', '10150', 'กรุงเทพมหานคร > บางบอน > บางบอนเหนือ > 10150', 'Bangkok > Bang Bon > Bang Bon Nuea > 10150'),
  ('เชียงใหม่', 'Chiang Mai', 'เมืองเชียงใหม่', 'Mueang Chiang Mai', 'แม่เหียะ', 'Mae Hia', '50100', 'เชียงใหม่ > เมืองเชียงใหม่ > แม่เหียะ > 50100', 'Chiang Mai > Mueang Chiang Mai > Mae Hia > 50100'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บางบอน', 'Bang Bon', 'คลองบางพราน', 'Khlong Bang Phran', '10150', 'กรุงเทพมหานคร > บางบอน > คลองบางพราน > 10150', 'Bangkok > Bang Bon > Khlong Bang Phran > 10150'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บางนา', 'Bang Na', 'บางนาใต้', 'Bang Na Tai', '10260', 'กรุงเทพมหานคร > บางนา > บางนาใต้ > 10260', 'Bangkok > Bang Na > Bang Na Tai > 10260'),
  ('กรุงเทพมหานคร', 'Bangkok', 'สะพานสูง', 'Saphan Sung', 'ทับช้าง', 'Tab Chang', '10240', 'กรุงเทพมหานคร > สะพานสูง > ทับช้าง > 10240', 'Bangkok > Saphan Sung > Tab Chang > 10240'),
  ('กรุงเทพมหานคร', 'Bangkok', 'บางบอน', 'Bang Bon', 'บางบอนใต้', 'Bang Bon Tai', '10150', 'กรุงเทพมหานคร > บางบอน > บางบอนใต้ > 10150', 'Bangkok > Bang Bon > Bang Bon Tai > 10150'),
  ('กรุงเทพมหานคร', 'Bangkok', 'สวนหลวง', 'Suan Luang', 'พัฒนาการ', 'Phatthanakan', '10250', 'กรุงเทพมหานคร > สวนหลวง > พัฒนาการ > 10250', 'Bangkok > Suan Luang > Phatthanakan > 10250'),
  ('กรุงเทพมหานคร', 'Bangkok', 'สวนหลวง', 'Suan Luang', 'อ่อนนุช', 'On Nut', '10250', 'กรุงเทพมหานคร > สวนหลวง > อ่อนนุช > 10250', 'Bangkok > Suan Luang > On Nut > 10250'),
  ('กรุงเทพมหานคร', 'Bangkok', 'สะพานสูง', 'Saphan Sung', 'ราษฎร์พัฒนา', 'Rat Phatthana', '10240', 'กรุงเทพมหานคร > สะพานสูง > ราษฎร์พัฒนา > 10240', 'Bangkok > Saphan Sung > Rat Phatthana > 10240')
ON CONFLICT (province_th, district_th, subdistrict_th, postcode) DO UPDATE SET
  province_en = EXCLUDED.province_en,
  district_en = EXCLUDED.district_en,
  subdistrict_en = EXCLUDED.subdistrict_en,
  all_th = EXCLUDED.all_th,
  all_en = EXCLUDED.all_en;

COMMIT;
