BEGIN;

CREATE TABLE IF NOT EXISTS public.pat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_th TEXT NOT NULL,
  province_en TEXT,
  district_th TEXT NOT NULL,
  district_en TEXT,
  subdistrict_th TEXT NOT NULL,
  subdistrict_en TEXT,
  postcode TEXT NOT NULL,
  all_th TEXT,
  all_en TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE VIEW public."PAT" AS
SELECT * FROM public.pat;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pat_unique
  ON public.pat (province_th, district_th, subdistrict_th, postcode);

ALTER TABLE public.pat ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pat_admin_read" ON public.pat;
CREATE POLICY "pat_admin_read" ON public.pat
FOR SELECT
TO authenticated
USING (public.current_role() = 'admin');

DROP POLICY IF EXISTS "pat_admin_write" ON public.pat;
CREATE POLICY "pat_admin_write" ON public.pat
FOR ALL
TO authenticated
USING (public.current_role() = 'admin')
WITH CHECK (public.current_role() = 'admin');

NOTIFY pgrst, 'reload config';

COMMIT;
